// Thai explanations for the Balance Config descriptions shown in the Admin Console tuning page.
// Keys are the exact English `.describe()` strings from schema.ts.

/** Thai text for each English field description: `th` = what it is (short, ≤ 60 chars), `up` = what raising it does (≤ 90 chars). */
export const FIELD_TH: Record<string, { th: string; up: string }> = {
  'Stage end: Bench skills can be removed for free (1) or not (0)': { th: 'ลบสกิลใน Bench ฟรีตอนจบด่าน (1 = ได้, 0 = ไม่ได้)', up: '1 = มีปุ่ม ✕ ลบสกิลสำรองทิ้งได้ ช่อง Bench ว่างรับสกิลใหม่' },
  'Full passive slots: new passives go to the Bench and swap at the Stage end (1) or are not offered (0)': { th: 'ช่อง Passive เต็ม: Passive ใหม่ไปพักใน Bench แล้วสลับตอนจบด่าน (1 = ได้, 0 = ไม่เสนอ Passive ใหม่)', up: '1 = เปลี่ยน Passive ได้ระหว่างรอบ' },
  'Stage end: Skill Points can be bought for Gold (1) or not (0)': { th: 'ซื้อแต้มสกิลด้วย Gold ตอนจบด่าน (1 = เปิด, 0 = ปิด)', up: '1 = มีปุ่มซื้อแต้มสกิลตอนจบด่าน (ราคาดูที่ spCost)' },
  'Kings also drop a chest item (1: two chests per King) or only open the wheel (0)': { th: 'บอสดรอปหีบบนพื้นด้วย (1 = 2 หีบต่อบอส, 0 = หีบเดียว)', up: '1 = ได้หีบเพิ่มอีกใบ ของรางวัลเยอะขึ้น เกมง่ายขึ้น' },
  'Normal monsters shoot (1) or just walk (0); King-summoned turrets always shoot': { th: 'มอนธรรมดายิงกระสุนได้ไหม (1 = ยิง, 0 = เดินอย่างเดียว)', up: '1 = มอนสายยิงยิงใส่ผู้เล่น เกมยากขึ้น (ป้อมที่ King เรียกยิงเสมอ)' },
  'Normal monsters charge (1) or just walk (0)': { th: 'มอนธรรมดาพุ่งชนได้ไหม (1 = พุ่ง, 0 = เดินอย่างเดียว)', up: '1 = มอนสายพุ่งชาร์จใส่ผู้เล่น เกมยากขึ้น' },
  'Shield drop chance (normal monster)': { th: 'โอกาสดรอปโล่ (มอนธรรมดา)', up: 'เจอโล่บ่อยขึ้น เกมง่ายขึ้น' },
  'Shield drop chance (elite monster)': { th: 'โอกาสดรอปโล่ (มอน elite)', up: 'ฆ่า elite แล้วได้โล่บ่อยขึ้น' },
  'Shield absorbs this much damage (× max HP)': { th: 'โล่กันดาเมจได้เท่าไร (× HP สูงสุด)', up: 'โล่รับดาเมจแทนได้มากขึ้นก่อนแตก' },
  'Shield lasts (s)': { th: 'โล่อยู่ได้นานกี่วินาที', up: 'โล่อยู่นานขึ้นก่อนหายไปเอง' },
  'Not used any more (guests pick up shared Gold drops); kept so older versions stay valid': { th: '(ไม่ใช้แล้ว) Gold ต่อการฆ่าของทีมสำหรับเพื่อน', up: 'ไม่มีผล ตอนนี้ทุกคนเก็บ Gold จากของดรอปร่วมกัน' },
  'Shared drops: a heart also heals allies this close to the player who took it': { th: 'ระยะที่หัวใจฮีลเพื่อนรอบตัวคนเก็บด้วย', up: 'เพื่อนที่อยู่ไกลขึ้นก็ได้ฮีลจากหัวใจที่คนอื่นเก็บ' },
  'Level-up / chest: seconds to choose before a pick is made for you (the room keeps playing)': { th: 'เวลาเลือกเลเวลอัป/หีบ ก่อนระบบสุ่มให้ (วินาที)', up: 'มีเวลาเลือกนานขึ้น แต่ยืนในโล่เฉย ๆ นานขึ้น' },
  'Shield bubble radius while choosing (monsters are pushed out)': { th: 'รัศมีโล่ฟองสบู่ตอนกำลังเลือก', up: 'โล่ใหญ่ขึ้น ดันมอนออกไปไกลขึ้น' },
  'Shield stays this long after choosing (s): time to get moving again, still no damage': { th: 'โล่อยู่ต่อหลังเลือกสกิลเสร็จ (วินาที)', up: 'มีเวลาตั้งหลักนานขึ้น เดินได้แต่ยังไม่โดนดาเมจ' },
  'Shield bubble push speed': { th: 'ความเร็วที่โล่ดันมอนออก', up: 'มอนถูกดันออกจากโล่เร็วขึ้น' },
  'A King drops its Realm\'s Weapon (if not owned yet)': { th: 'โอกาสที่ King ดรอป Weapon ของ Realm (ถ้ายังไม่มี)', up: 'โอกาสสูงขึ้น ได้ Weapon จาก King ง่ายขึ้น' },
  'Added per skill level': { th: 'เพิ่มต่อเลเวลสกิล', up: 'ค่าเปลี่ยนมากขึ้นทุกเลเวล (ถ้าติดลบ = ลดลงทุกเลเวล เช่นคูลดาวน์)' },
  'After the first Guardian: Blood Moon chance × in a Realm whose element matches a missing one': { th: 'คูณโอกาส Blood Moon ใน Realm ธาตุที่ยังไม่มี Guardian', up: 'หลังได้ Guardian ตัวแรก จะเจอ Blood Moon ใน Realm ธาตุที่ยังขาดบ่อยขึ้น' },
  'After the first Guardian: Guardian chance in such a Blood Moon': { th: 'โอกาสเจอ Guardian ใน Blood Moon ของ Realm แบบนั้น', up: 'หลังได้ Guardian ตัวแรก โอกาสสูงขึ้น เก็บครบสามตัวเร็วขึ้น' },
  'Ally revive distance': { th: 'ระยะที่ยืนชุบเพื่อนได้', up: 'ยืนห่างเพื่อนได้มากขึ้นก็ยังชุบได้ ชุบง่ายขึ้น' },
  'Angle between bolts (rad)': { th: 'มุมห่างระหว่างกระสุนเงา (เรเดียน)', up: 'กระสุนกางกว้างขึ้น คลุมพื้นที่มากขึ้น แต่ช่องระหว่างลูกกว้างขึ้น' },
  'Angle between bones (rad)': { th: 'มุมห่างระหว่างกระดูก (เรเดียน)', up: 'พัดกระดูกกางกว้างขึ้น คลุมพื้นที่มากขึ้น' },
  'Angle between bubbles (rad)': { th: 'มุมห่างระหว่างฟอง (เรเดียน)', up: 'ฟองกระจายกว้างขึ้น คลุมพื้นที่มากขึ้น' },
  'Angle between spears (rad)': { th: 'มุมห่างระหว่างหอกน้ำแข็ง (เรเดียน)', up: 'หอกกางกว้างขึ้น คลุมพื้นที่มากขึ้น' },
  'Approach when farther than this': { th: 'เดินเข้าหาเมื่ออยู่ไกลกว่าระยะนี้', up: 'ยอมอยู่ห่างได้ไกลขึ้นก่อนจะเดินเข้าหาผู้เล่น' },
  'Armor (flat reduction) at stage 1': { th: 'เกราะ (หักดาเมจแบบคงที่) ที่ด่าน 1', up: 'มอนเกราะหักดาเมจมากขึ้น สกิลที่ตีเบาแทบไม่เข้า' },
  'Armor + per player level': { th: 'เกราะเพิ่มต่อเลเวลผู้เล่น', up: 'ยิ่งเลเวลสูง เกราะมอนยิ่งหนาขึ้นเร็ว' },
  'Armor chance': { th: 'โอกาสเกิดมอนใส่เกราะ (0–1)', up: 'มอนเกราะโผล่บ่อยขึ้น' },
  'Armor chance per stage': { th: 'โอกาสมอนเกราะเพิ่มต่อด่าน', up: 'ด่านหลังๆ มอนเกราะเยอะขึ้นเร็วขึ้น' },
  'Armor × per stage': { th: 'เกราะคูณเพิ่มต่อด่าน', up: 'เกราะหนาขึ้นเร็วมากในด่านหลังๆ' },
  'Armoured Realms: armour chance ×': { th: 'Realm สายเกราะ: คูณโอกาสมอนเกราะ', up: 'ใน Realm สายเกราะ เจอมอนเกราะบ่อยขึ้นอีก' },
  'Armoured Realms: armour from this Chapter': { th: 'Realm สายเกราะ: มีมอนเกราะตั้งแต่ Chapter นี้', up: 'มอนเกราะเริ่มมาช้าลง (Chapter หลังขึ้น)' },
  'Arrival blast radius': { th: 'รัศมีระเบิดตอนสลับที่มาถึง', up: 'ระเบิดกว้างขึ้น หลบยากขึ้น' },
  'At most this × Umbra\'s max HP per Ultimate': { th: 'Ultimate ตี Umbra ได้สูงสุด × HP เต็มของ Umbra', up: 'Ultimate ตัด HP Umbra ได้มากขึ้นต่อครั้ง' },
  'At most this × a King\'s or Guardian\'s max HP per Ultimate': { th: 'Ultimate ตี King/Guardian ได้สูงสุด × HP เต็ม', up: 'Ultimate ตัด HP บอสได้มากขึ้นต่อครั้ง' },
  'Attack interval max (s)': { th: 'พักระหว่างท่า นานสุด (วินาที)', up: 'บอสออกท่าห่างขึ้น เกมง่ายขึ้น' },
  'Attack interval min (s)': { th: 'พักระหว่างท่า สั้นสุด (วินาที)', up: 'บอสออกท่าถี่ได้น้อยลง เกมง่ายขึ้น' },
  'Attack slots, including the Signature Skill': { th: 'ช่องสกิลโจมตี (รวม Signature Skill)', up: 'ถือสกิลโจมตีได้มากขึ้น แรงขึ้นมาก' },
  'Offered in Settings (1) or hidden (0)': { th: 'แสดงให้ผู้เล่นเลือกในหน้าตั้งค่า (1 = แสดง, 0 = ซ่อน)', up: '0 = ซ่อน preset นี้ ผู้เล่นที่เลือกไว้จะกลับไปเล่นแบบสมดุล' },
  'Normal monster HP ×': { th: 'คูณเลือดมอนธรรมดา', up: 'มอนถึกขึ้น ตายช้าลง' },
  'Normal monster damage ×': { th: 'คูณดาเมจมอนธรรมดา', up: 'มอนตีเจ็บขึ้น' },
  'King, Guardian, Rival and Umbra HP ×': { th: 'คูณเลือดบอส (ราชา, Guardian, Rival, Umbra)', up: 'บอสถึกขึ้น สู้นานขึ้น' },
  'King, Guardian, Rival and Umbra damage ×': { th: 'คูณดาเมจบอส (ราชา, Guardian, Rival, Umbra)', up: 'ท่าบอสเจ็บขึ้น' },
  'Spawn rate and swarm size ×': { th: 'คูณอัตราเกิดมอนและขนาดฝูงล้อม', up: 'มอนเยอะขึ้น แน่นขึ้น' },
  'EXP gained ×': { th: 'คูณ EXP ที่ได้', up: 'เลเวลอัปเร็วขึ้น' },
  'Stage length ×': { th: 'คูณความยาวด่าน', up: 'ด่านยาวขึ้น' },
  'Boss move warning time ×': { th: 'คูณเวลาเตือนก่อนท่าบอส', up: 'มีเวลาหลบท่าบอสนานขึ้น เกมง่ายขึ้น' },
  'Pause between King moves ×': { th: 'คูณช่วงพักระหว่างท่าของราชา', up: 'ราชาออกท่าห่างขึ้น เกมง่ายขึ้น' },
  'Player max HP ×': { th: 'คูณเลือดสูงสุดของผู้เล่น', up: 'ผู้เล่นทนขึ้น' },
  'Player speed ×': { th: 'คูณความเร็วผู้เล่น', up: 'วิ่งเร็วขึ้น หลบง่ายขึ้น' },
  'Heart drop chance ×': { th: 'คูณโอกาสดรอปหัวใจ', up: 'ได้ฮีลบ่อยขึ้น' },
  'Ultimate charge time ×': { th: 'คูณเวลาชาร์จท่าไม้ตาย', up: 'ชาร์จช้าลง ใช้ท่าไม้ตายได้น้อยลง' },
  'Director maximum ×': { th: 'คูณเพดานของ Director', up: 'เกมเร่งความกดดันได้สูงขึ้นเมื่อผู้เล่นเล่นสบาย' },
  'Gold earned ×': { th: 'คูณทองที่ได้ในรอบ', up: 'ได้ทองมากขึ้น' },
  'Awakened Signature Skill damage ×': { th: 'ดาเมจ Signature Skill หลัง Awakening (คูณ)', up: 'หลัง Awakening ตีแรงขึ้น' },
  'Skill Line skills given right away when Awakening (in listed order, into the freed slots)': { th: 'จำนวนสกิลสายที่ได้ทันทีตอน Awakening (ใส่ในช่องที่ว่าง)', up: 'Awakening แล้วได้สกิลสายทันทีมากขึ้น ไม่ต้องรอสุ่มเจอ' },
  'Level of the Skill Line skills given at Awakening': { th: 'เลเวลเริ่มต้นของสกิลสายที่ได้ตอน Awakening', up: 'สกิลสายที่ได้แรงตั้งแต่แรก ชดเชย Link ที่เสียไป' },
  'Level-up offer weight × for Skill Line skills after Awakening': { th: 'คูณโอกาสเจอสกิลสายในตัวเลือกเลเวลอัป (หลัง Awakening)', up: 'สกิลสายโผล่ให้เลือกบ่อยขึ้น อัปเต็มได้เร็วขึ้น' },
  'Dive splash radius: monsters this close to the prey are hit too (0 = prey only)': { th: 'รัศมีแรงกระแทกตอนเหยี่ยวโฉบ (0 = โดนแค่เป้า)', up: 'เหยี่ยวโฉบโดนมอนรอบเป้าด้วย เคลียร์ฝูงได้ดีขึ้น' },
  'Back off when nearer than this': { th: 'ถอยหนีเมื่อผู้เล่นเข้าใกล้กว่าระยะนี้', up: 'ถอยตั้งแต่ไกลขึ้น เข้าไปตีระยะประชิดยากขึ้น' },
  'Base crit chance': { th: 'โอกาสคริติคอลพื้นฐาน (0–1)', up: 'ติดคริบ่อยขึ้น ดาเมจเฉลี่ยสูงขึ้น' },
  'Base crit multiplier': { th: 'ตัวคูณดาเมจคริพื้นฐาน', up: 'ติดคริแล้วแรงขึ้น' },
  'Base max HP': { th: 'HP สูงสุดพื้นฐานของผู้เล่น', up: 'ผู้เล่นอึดขึ้น ตายยากขึ้น' },
  'Base pickup range': { th: 'ระยะดูดของพื้นฐาน', up: 'เก็บ EXP/เหรียญได้จากไกลขึ้น' },
  'Base price': { th: 'ราคาเริ่มต้น (Gold)', up: 'อัปเกรดแพงขึ้น ต้องเก็บ Gold นานขึ้น' },
  'Base speed': { th: 'ความเร็วเดินพื้นฐาน', up: 'ผู้เล่นเดินเร็วขึ้น หลบง่ายขึ้น' },
  'Beam half-width (rad)': { th: 'ความกว้างลำเลเซอร์ (ครึ่งมุม, เรเดียน)', up: 'ลำแสงอ้วนขึ้น โดนมอนได้เยอะขึ้น' },
  'Beating Umbra': { th: 'คะแนนเมื่อชนะ Umbra', up: 'ชนะ Umbra แล้วได้คะแนนมากขึ้น' },
  'Bench +1 once this Chapter is behind you': { th: 'Bench +1 ช่อง เมื่อผ่าน Chapter นี้', up: 'ได้ช่อง Bench เพิ่มช้าลง (ต้องไปไกลขึ้น)' },
  'Bench slots at the start of a Run': { th: 'ช่อง Bench ตอนเริ่ม Run', up: 'เก็บสกิลสำรองได้มากขึ้นตั้งแต่ต้น' },
  'Between bolts (s)': { th: 'ช่วงเวลาระหว่างลูกวิญญาณ (วินาที)', up: 'ปล่อยแต่ละลูกห่างขึ้น ท่ายาวขึ้นแต่หลบง่ายขึ้น' },
  'Between books (s)': { th: 'ช่วงเวลาระหว่างหนังสือแต่ละเล่ม (วินาที)', up: 'หนังสือยิงห่างขึ้น หลบง่ายขึ้น' },
  'Between drops (s)': { th: 'ช่วงเวลาระหว่างหยดลาวา (วินาที)', up: 'ลาวาตกห่างขึ้น มีเวลาหลบมากขึ้น' },
  'Between stars (s)': { th: 'ช่วงเวลาระหว่างดาวแต่ละดวง (วินาที)', up: 'ดาวตกห่างขึ้น ดาเมจทยอยมาช้าลง' },
  'Between strikes (s)': { th: 'ช่วงเวลาระหว่างฟ้าผ่าแต่ละครั้ง (วินาที)', up: 'ฟ้าผ่าตามรอยเท้าช้าลง หนีทันง่ายขึ้น' },
  'Between waves (s)': { th: 'ช่วงเวลาระหว่างระลอก (วินาที)', up: 'ระลอกลาวามาห่างขึ้น มีเวลาหลบมากขึ้น' },
  'Blade every (s) while walking': { th: 'ปล่อยใบมีดทุกกี่วินาทีขณะเดิน', up: 'ปล่อยใบมีดห่างขึ้น = ใบมีดน้อยลง ดาเมจรวมลดลง' },
  'Blade radius': { th: 'รัศมีใบมีด', up: 'ใบมีดใหญ่ขึ้น โดนมอนง่ายขึ้น' },
  'Blades when evolved': { th: 'จำนวนใบมีดหลัง Evolution', up: 'ใบมีดหมุนรอบตัวมากขึ้น ป้องกันได้ดีขึ้น' },
  'Blast damage': { th: 'ดาเมจระเบิดตอนฟื้นคืนชีพ', up: 'ระเบิดฆ่ามอนรอบตัวได้มากขึ้น' },
  'Blast radius': { th: 'รัศมีระเบิด', up: 'ระเบิดกินพื้นที่กว้างขึ้น' },
  'Blast × per stage': { th: 'ดาเมจระเบิดคูณเพิ่มต่อด่าน', up: 'ระเบิดแรงขึ้นเร็วในด่านหลังๆ' },
  'Blizzard length (s)': { th: 'พายุหิมะนาน (วินาที)', up: 'ต้องขยับตัวหนีนานขึ้น ยากขึ้น' },
  'Blizzard warning (s)': { th: 'เตือนก่อนพายุหิมะ (วินาที)', up: 'เตือนนานขึ้น เตรียมตัวทัน' },
  'Blood Moon chance': { th: 'โอกาสเกิด Blood Moon (0–1)', up: 'เจอ Blood Moon บ่อยขึ้น' },
  'Blood Moon chance + per miss': { th: 'โอกาส Blood Moon เพิ่มทุกครั้งที่ไม่เกิด', up: 'ไม่เจอนานๆ แล้วโอกาสพุ่งขึ้นเร็วขึ้น' },
  'Blood Moon coin ×': { th: 'คูณเหรียญใน Blood Moon', up: 'Blood Moon ได้เหรียญมากขึ้น' },
  'Blood Moon reveals itself at this fraction of the Stage': { th: 'Blood Moon เผยตัวเมื่อด่านผ่านไปสัดส่วนนี้ (0–1)', up: 'รู้ตัวช้าลงว่าด่านนี้เป็น Blood Moon' },
  'Blood Moon spawn ×': { th: 'คูณอัตราเกิดมอนใน Blood Moon', up: 'Blood Moon มอนแน่นขึ้น ยากขึ้น' },
  'Bolt speed': { th: 'ความเร็วลูกวิญญาณ', up: 'ลูกพุ่งเร็วขึ้น หลบยากขึ้น' },
  'Bone Scythe: normal monsters below this HP fraction are reaped': { th: 'Bone Scythe: มอนธรรมดา HP ต่ำกว่าสัดส่วนนี้ตายทันที', up: 'เก็บมอนที่ HP เหลือน้อยได้มากขึ้น' },
  'Bone pillars': { th: 'จำนวนเสากระดูกรอบกรง', up: 'กรงแน่นขึ้น' },
  'Bones': { th: 'จำนวนกระดูก', up: 'กระดูกเยอะขึ้น หลบยากขึ้น' },
  'Books around you': { th: 'จำนวนหนังสือรอบตัว', up: 'ลูกยิงเยอะขึ้น หลบยากขึ้น' },
  'Boss / Guardian / Umbra HP + per extra player': { th: 'HP บอส/Guardian/Umbra เพิ่มต่อผู้เล่นที่มาเพิ่ม', up: 'เล่นหลายคนแล้วบอสอึดขึ้น' },
  'Boss appears at this fraction of the stage': { th: 'บอสมาเมื่อด่านผ่านไปสัดส่วนนี้ (0–1)', up: 'บอสมาช้าลง เหลือเวลาตีบอสน้อยลง' },
  'Boss coin value': { th: 'มูลค่าเหรียญที่บอสดรอป', up: 'ฆ่าบอสได้ Gold มากขึ้น' },
  'Boss heart heal (× max HP)': { th: 'หัวใจจากบอสฮีล (× HP สูงสุด)', up: 'หัวใจบอสฮีลมากขึ้น' },
  'Bought revive: Gold × Chapter (once per Run, −15% Score)': { th: 'ซื้อชุบชีวิต: Gold × Chapter (ครั้งเดียว, −15% Score)', up: 'ชุบชีวิตแพงขึ้น' },
  'Bouncing orbs': { th: 'จำนวนลูกบอลสายฟ้าเด้งไปมา', up: 'ลูกบอลเยอะขึ้น หลบยากขึ้น' },
  'Breath damage base': { th: 'ดาเมจพ่นไฟ (ค่าตั้งต้น)', up: 'มังกรคู่หูพ่นไฟแรงขึ้น' },
  'Breath damage per player level': { th: 'ดาเมจพ่นไฟเพิ่มต่อเลเวลผู้เล่น', up: 'ยิ่งเลเวลสูง พ่นไฟยิ่งแรง' },
  'Breath damage × per tick': { th: 'ดาเมจพ่นไฟต่อครั้ง (คูณดาเมจชน)', up: 'โดนไฟแล้วเจ็บขึ้น' },
  'Breath duration (s)': { th: 'พ่นไฟนาน (วินาที)', up: 'พ่นนานขึ้น ต้องหลบนานขึ้น' },
  'Breath half-angle (rad)': { th: 'ความกว้างไฟ (ครึ่งมุม, เรเดียน)', up: 'ไฟกว้างขึ้น หลบยากขึ้น' },
  'Breath interval (s)': { th: 'พ่นไฟทุกกี่วินาที', up: 'พ่นไฟห่างขึ้น = คู่หูช่วยได้น้อยลง' },
  'Breath interval minimum': { th: 'พ่นไฟถี่สุดได้แค่ (วินาที)', up: 'ถึงเลเวลสูงก็พ่นถี่ได้น้อยลง' },
  'Breath interval − per pet level': { th: 'พ่นไฟเร็วขึ้นต่อเลเวลคู่หู (วินาที)', up: 'อัปเลเวลคู่หูแล้วพ่นถี่ขึ้นเร็ว' },
  'Breath length': { th: 'ระยะพ่นไฟ', up: 'ไฟพุ่งไปได้ไกลขึ้น' },
  'Breath length per pet level': { th: 'ระยะพ่นไฟเพิ่มต่อเลเวลคู่หู', up: 'อัปคู่หูแล้วไฟยาวขึ้นเร็ว' },
  'Breath targeting range': { th: 'ระยะหาเป้าพ่นไฟ', up: 'คู่หูพ่นใส่มอนที่อยู่ไกลขึ้นได้' },
  'Breath warning (s)': { th: 'เตือนก่อนพ่นไฟ (วินาที)', up: 'เตือนนานขึ้น หลบง่ายขึ้น' },
  'Bubble speed': { th: 'ความเร็วฟอง', up: 'ฟองลอยเร็วขึ้น หลบยากขึ้น' },
  'Bubbles': { th: 'จำนวนฟอง', up: 'ฟองเยอะขึ้น หลบยากขึ้น' },
  'Burning (s)': { th: 'สถานะ Burning (ติดไฟ) นาน (วินาที)', up: 'ติดไฟนานขึ้น ทำ Combo ได้ง่ายขึ้น' },
  'Buy 1 Skill Point at Stage end: Gold × Chapter': { th: 'ราคาซื้อแต้มสกิลตอนจบด่าน (Gold × Chapter)', up: 'แพงขึ้น · มีผลเฉพาะเมื่อเปิด spShop = 1' },
  'Cage radius': { th: 'รัศมีกรงกระดูก', up: 'กรงกว้างขึ้น มีที่ให้เดินมากขึ้น' },
  'Camera zoom for Evolution/Awakening/fusion': { th: 'ซูมกล้องตอน Evolution/Awakening/รวมร่าง', up: 'ซูมใกล้ขึ้น ดูอลังการขึ้น' },
  'Catalyst: Arcane Bolt on any Status, damage ×': { th: 'Catalyst: Arcane Bolt โดนมอนติด Status คูณดาเมจ', up: 'Combo Catalyst แรงขึ้น' },
  'Chain damage base': { th: 'ดาเมจสายฟ้าโซ่ (ค่าตั้งต้น)', up: 'สายฟ้าโซ่แรงขึ้น' },
  'Chain jumps': { th: 'จำนวนครั้งที่สายฟ้ากระโดดต่อ', up: 'สายฟ้าโดนมอนได้หลายตัวขึ้น' },
  'Chain lightning interval (s)': { th: 'ปล่อยสายฟ้าโซ่ทุกกี่วินาที', up: 'ปล่อยห่างขึ้น = ช่วยได้น้อยลง' },
  'Chance of ×1': { th: 'โอกาสได้ ×1 (0–1)', up: 'ได้รางวัลน้อยบ่อยขึ้น (×2, ×3 ลดลง)' },
  'Chance of ×2 (rest is ×3)': { th: 'โอกาสได้ ×2 (ที่เหลือคือ ×3)', up: 'ได้ ×2 บ่อยขึ้น แต่ ×3 น้อยลง' },
  'Chance to get the clone outright': { th: 'โอกาสได้ Shadow Clone ทันที', up: 'ได้ Clone ง่ายขึ้น' },
  'Chapters in a Run (the last one is the Heart Crater)': { th: 'จำนวน Chapter ใน Run (อันสุดท้ายคือ Heart Crater)', up: 'Run ยาวขึ้น' },
  'Charge interval max (s)': { th: 'พักระหว่างพุ่งชน นานสุด (วินาที)', up: 'หมูป่าพุ่งห่างขึ้น ง่ายขึ้น' },
  'Charge interval min (s)': { th: 'พักระหว่างพุ่งชน สั้นสุด (วินาที)', up: 'หมูป่าพุ่งถี่ได้น้อยลง ง่ายขึ้น' },
  'Charge needed': { th: 'เกจที่ต้องเก็บให้เต็มก่อนใช้ Ultimate', up: 'การฆ่าช่วยเติมเกจได้น้อยลง (เวลาเติมเท่าเดิม)' },
  'Charge per boss kill': { th: 'เกจ Ultimate ต่อการฆ่าบอส', up: 'ฆ่าบอสแล้ว Ultimate เต็มเร็วขึ้น' },
  'Charge per elite kill': { th: 'เกจ Ultimate ต่อการฆ่า elite', up: 'ฆ่า elite แล้ว Ultimate เต็มเร็วขึ้น' },
  'Charge per kill': { th: 'เกจ Ultimate ต่อการฆ่ามอน 1 ตัว', up: 'ฆ่ามอนแล้ว Ultimate เต็มเร็วขึ้น' },
  'Charge trigger range': { th: 'ระยะที่หมูป่าเริ่มพุ่งใส่', up: 'หมูป่าพุ่งใส่จากไกลขึ้น' },
  'Chest wheels per King killed': { th: 'จำนวนวงล้อหีบต่อ King ที่ฆ่า', up: 'ได้ของจาก King มากขึ้น' },
  'Chill after being caught (s)': { th: 'ติดหนาว (เดินช้า) หลังโดนท่า (วินาที)', up: 'เดินช้านานขึ้น อันตรายขึ้น' },
  'Choices per level-up': { th: 'จำนวนตัวเลือกตอนเลเวลอัป', up: 'มีตัวเลือกมากขึ้น ได้สกิลที่อยากได้ง่ายขึ้น' },
  'Circle radius': { th: 'รัศมีวง', up: 'วงใหญ่ขึ้น กินพื้นที่มากขึ้น' },
  'Circles per wave': { th: 'จำนวนวงลาวาต่อระลอก', up: 'ลาวาตกเยอะขึ้น หลบยากขึ้น' },
  'Clone damage + per clone level': { th: 'ดาเมจ Clone เพิ่มต่อเลเวล Clone', up: 'อัป Clone แล้วแรงขึ้นเร็ว' },
  'Clone damage fraction': { th: 'ดาเมจ Clone (สัดส่วนของดาเมจเรา)', up: 'Clone ตีแรงขึ้น' },
  'Clone damage fraction cap': { th: 'ดาเมจ Clone สูงสุด (สัดส่วน)', up: 'Clone แรงได้สูงขึ้น' },
  'Coin blast radius': { th: 'รัศมีระเบิดเหรียญปลอม', up: 'เหรียญปลอมระเบิดกว้างขึ้น' },
  'Coin damage ×': { th: 'ดาเมจเหรียญปลอม (คูณ)', up: 'เหรียญปลอมเจ็บขึ้น' },
  'Coin drop chance': { th: 'โอกาสมอนดรอปเหรียญ (0–1)', up: 'ได้เหรียญบ่อยขึ้น Gold มากขึ้น' },
  'Coin value': { th: 'มูลค่าเหรียญธรรมดา', up: 'เก็บเหรียญแล้วได้ Gold มากขึ้น' },
  'Collapse knockback': { th: 'แรงกระเด็นตอนหลุมดำยุบ', up: 'มอนกระเด็นไกลขึ้น' },
  'Collapse multiplier': { th: 'ตัวคูณดาเมจตอนยุบ (หลัง Evolution)', up: 'ยุบแล้วแรงขึ้น' },
  'Cone length': { th: 'ความยาวกรวย', up: 'ท่าพุ่งไปไกลขึ้น หลบยากขึ้น' },
  'Contact damage': { th: 'ดาเมจเมื่อชนผู้เล่น', up: 'โดนชนแล้วเจ็บขึ้น' },
  'Cooldown multiplier': { th: 'ตัวคูณคูลดาวน์หลัง Evolution (<1 = เร็วขึ้น)', up: 'คูลดาวน์นานขึ้น = ยิงช้าลง' },
  'Cooldown reduction': { th: 'ลดคูลดาวน์', up: 'สกิลยิงถี่ขึ้น' },
  'Cooldown reduction cap': { th: 'ลดคูลดาวน์ได้สูงสุด', up: 'สะสมลดคูลดาวน์ได้มากขึ้น ยิงถี่ได้อีก' },
  'Coral Trident: push toward the screen edge': { th: 'Coral Trident: แรงผลักมอนไปทางขอบจอ', up: 'ผลักมอนออกไปไกลขึ้น' },
  'Core damage × per tick': { th: 'ดาเมจตรงกลาง ต่อครั้ง (คูณ)', up: 'ยืนตรงกลางแล้วเจ็บขึ้น' },
  'Core radius': { th: 'รัศมีจุดกลาง', up: 'จุดอันตรายตรงกลางใหญ่ขึ้น' },
  'Crit chance cap': { th: 'โอกาสคริสูงสุด', up: 'สะสมโอกาสคริได้สูงขึ้น' },
  'Cruising: HP above this fraction': { th: 'เล่นสบาย: HP มากกว่าสัดส่วนนี้', up: 'ต้อง HP สูงขึ้น Director ถึงจะเพิ่มความยาก' },
  'Cruising: seconds without being hurt': { th: 'เล่นสบาย: ไม่โดนตีติดต่อกันกี่วินาที', up: 'Director เริ่มเพิ่มความยากช้าลง' },
  'Damage + per pet level': { th: 'ดาเมจเพิ่มต่อเลเวลคู่หู', up: 'อัปคู่หูแล้วแรงขึ้นมาก' },
  'Damage = this × the Chapter\'s normal monster HP (no Might/Power/crit)': { th: 'ดาเมจ = ค่านี้ × HP มอนปกติของ Chapter', up: 'Ultimate แรงขึ้น ฆ่ามอนอึดๆ ได้' },
  'Damage base': { th: 'ดาเมจ (ค่าตั้งต้น)', up: 'คู่หูตีแรงขึ้น' },
  'Damage interval (s)': { th: 'ทำดาเมจทุกกี่วินาที', up: 'ตีห่างขึ้น = ดาเมจรวมน้อยลง' },
  'Damage multiplier': { th: 'ตัวคูณดาเมจหลัง Evolution', up: 'Evolution แล้วตีแรงขึ้น' },
  'Damage per level': { th: 'ดาเมจเพิ่มต่อเลเวล', up: 'อัปแต่ละเลเวลแล้วแรงขึ้นมากขึ้น' },
  'Damage per player level': { th: 'ดาเมจเพิ่มต่อเลเวลผู้เล่น', up: 'ยิ่งเลเวลสูง คู่หูยิ่งแรง' },
  'Damage taken × (1 − this)': { th: 'ลดดาเมจที่โดน (เช่น 0.15 = −15%)', up: 'รับดาเมจน้อยลง อึดขึ้น' },
  'Damage ×': { th: 'ดาเมจท่านี้ (× ดาเมจชนของบอส)', up: 'ท่านี้เจ็บขึ้น' },
  'Damage × King contact damage': { th: 'ดาเมจ = ค่านี้ × ดาเมจชนของ King', up: 'ท่านี้เจ็บขึ้น' },
  'Damage × from the element a Realm resists': { th: 'ดาเมจจากธาตุที่ Realm ต้านทาน (คูณ)', up: 'ต้านทานน้อยลง สกิลธาตุนั้นแรงขึ้น' },
  'Damage × outside a safe circle': { th: 'ดาเมจ × ถ้าอยู่นอกวงปลอดภัย', up: 'เข้าวงไม่ทันแล้วเจ็บขึ้น' },
  'Damage × outside the safe pool': { th: 'ดาเมจ × ถ้าอยู่นอกบ่อปลอดภัย', up: 'เข้าบ่อไม่ทันแล้วเจ็บขึ้น' },
  'Damage × per tick': { th: 'ดาเมจต่อครั้ง (× ดาเมจชน)', up: 'ยืนในท่าแล้วเจ็บขึ้น' },
  'Damaging core radius': { th: 'รัศมีจุดกลางที่ทำดาเมจ', up: 'จุดอันตรายตรงกลางใหญ่ขึ้น' },
  'Dash contact damage ×': { th: 'ดาเมจตอนพุ่งชน (คูณ)', up: 'โดนพุ่งชนแล้วเจ็บขึ้น' },
  'Dash speed': { th: 'ความเร็วพุ่ง', up: 'พุ่งเร็วขึ้น หลบยากขึ้น' },
  'Dash time (s)': { th: 'พุ่งนาน (วินาที)', up: 'พุ่งนานขึ้น ไปได้ไกลขึ้น' },
  'Dash warning (s)': { th: 'เตือนก่อนพุ่ง (วินาที)', up: 'เตือนนานขึ้น หลบง่ายขึ้น' },
  'Dash warning length': { th: 'ความยาวเส้นเตือนการพุ่ง', up: 'เส้นพุ่งยาวขึ้น หลบยากขึ้น' },
  'Default knockback': { th: 'แรงกระเด็นพื้นฐาน', up: 'มอนกระเด็นไกลขึ้น' },
  'Delay before the first ultimate after phase 2 starts (s)': { th: 'หน่วงก่อนท่าไม้ตายแรกหลังเข้าเฟส 2 (วินาที)', up: 'King ใช้ท่าไม้ตายช้าลง' },
  'Delay between meteors (s)': { th: 'ช่วงเวลาระหว่างอุกกาบาตแต่ละลูก (วินาที)', up: 'อุกกาบาตตกห่างขึ้น ดาเมจทยอยมาช้าลง' },
  'Disc speed': { th: 'ความเร็วจาน', up: 'จานบินเร็วขึ้น' },
  'Discs multiplier': { th: 'ตัวคูณจำนวนจาน (หลัง Evolution)', up: 'Evolution แล้วได้จานเยอะขึ้น' },
  'Distance between rows': { th: 'ระยะห่างระหว่างแถวฟ้าผ่า', up: 'แถวห่างขึ้น ช่องหลบกว้างขึ้น' },
  'Distance from the King': { th: 'ระยะห่างจาก King', up: 'ป้อมตั้งห่างจาก King มากขึ้น' },
  'Dive damage base': { th: 'ดาเมจโฉบทิ้งระเบิด (ค่าตั้งต้น)', up: 'โฉบแล้วแรงขึ้น' },
  'Dive damage per player level': { th: 'ดาเมจโฉบเพิ่มต่อเลเวลผู้เล่น', up: 'ยิ่งเลเวลสูง โฉบยิ่งแรง' },
  'Dive interval (s)': { th: 'โฉบทิ้งระเบิดทุกกี่วินาที', up: 'โฉบห่างขึ้น = ช่วยได้น้อยลง' },
  'Dive interval minimum': { th: 'โฉบถี่สุดได้แค่ (วินาที)', up: 'ถึงเลเวลสูงก็โฉบถี่ได้น้อยลง' },
  'Dive interval − per pet level': { th: 'โฉบเร็วขึ้นต่อเลเวลคู่หู (วินาที)', up: 'อัปคู่หูแล้วโฉบถี่ขึ้นเร็ว' },
  'Dive radius': { th: 'รัศมีระเบิดตอนโฉบ', up: 'โฉบโดนมอนกว้างขึ้น' },
  'Dive time (s)': { th: 'เวลาที่เหยี่ยวโฉบถึงเป้า (วินาที)', up: 'โฉบช้าลง ถึงเป้าช้าขึ้น' },
  'Dome radius': { th: 'รัศมีโดม', up: 'โดมใหญ่ขึ้น ผลักมอนได้กว้างขึ้น' },
  'Double-King Stage chance (never announced)': { th: 'โอกาสเจอด่าน King สองตัว (ไม่บอกล่วงหน้า)', up: 'เจอ King คู่บ่อยขึ้น' },
  'Double-King Stages from this Chapter': { th: 'ด่าน King คู่เริ่มได้ตั้งแต่ Chapter นี้', up: 'เจอ King คู่ช้าลง (Chapter หลังขึ้น)' },
  'Dragon arrives at stage fraction': { th: 'มังกรมาเมื่อด่านผ่านไปสัดส่วนนี้ (0–1)', up: 'มังกรมาช้าลง เหลือเวลาสู้น้อยลง' },
  'Dragon chance + per miss': { th: 'โอกาสมังกรเพิ่มทุกครั้งที่ไม่เกิด', up: 'ไม่เจอนานๆ แล้วโอกาสพุ่งขึ้นเร็ว' },
  'Dragon chance inside Blood Moon': { th: 'โอกาสเจอมังกรใน Blood Moon (0–1)', up: 'เจอมังกรบ่อยขึ้น' },
  'Dragon omen at stage fraction': { th: 'ลางบอกเหตุมังกรเมื่อด่านผ่านไปสัดส่วนนี้', up: 'เห็นลางเตือนช้าลง' },
  'Drift speed': { th: 'ความเร็วที่พายุลอยไป', up: 'พายุลอยเร็วขึ้น กวาดพื้นที่มากขึ้น' },
  'Drop per second right after a hit': { th: 'Director ลดลงต่อวินาที ช่วงเพิ่งโดนตี', up: 'โดนตีแล้วเกมผ่อนลงเร็วขึ้น' },
  'Drop per second while struggling': { th: 'Director ลดลงต่อวินาที ตอนเล่นลำบาก', up: 'ตอน HP น้อย เกมผ่อนลงเร็วขึ้น' },
  'Drop radius': { th: 'รัศมีหยดลาวา', up: 'หยดลาวาใหญ่ขึ้น หลบยากขึ้น' },
  'Drops': { th: 'จำนวนหยดลาวา', up: 'ลาวาเยอะขึ้น หลบยากขึ้น' },
  'Duration (s)': { th: 'พ่นนาน (วินาที)', up: 'ท่านานขึ้น ต้องหลบนานขึ้น' },
  'Each King\'s HP × on a double-King Stage': { th: 'HP King แต่ละตัวในด่าน King คู่ (คูณ)', up: 'King คู่อึดขึ้น' },
  'Each further swap in the same Stage end costs × this': { th: 'สลับครั้งถัดไปในจบด่านเดียวกัน ราคาคูณเท่านี้', up: 'สลับหลายครั้งแพงขึ้นเร็ว' },
  'Elite HP ×': { th: 'HP elite (คูณ)', up: 'elite อึดขึ้น' },
  'Elite XP ×': { th: 'EXP จาก elite (คูณ)', up: 'ฆ่า elite ได้ EXP มากขึ้น' },
  'Elite chance per stage': { th: 'โอกาสเกิด elite เพิ่มต่อด่าน', up: 'เจอ elite บ่อยขึ้น' },
  'Elite coin value': { th: 'มูลค่าเหรียญที่ elite ดรอป', up: 'ฆ่า elite ได้ Gold มากขึ้น' },
  'Elite damage ×': { th: 'ดาเมจ elite (คูณ)', up: 'โดน elite ชนแล้วเจ็บขึ้น' },
  'Elite size ×': { th: 'ขนาดตัว elite (คูณ)', up: 'elite ตัวใหญ่ขึ้น' },
  'Elite speed ×': { th: 'ความเร็ว elite (คูณ)', up: 'elite เดินเร็วขึ้น' },
  'Enemies per swarm ring': { th: 'จำนวนมอนต่อฝูงล้อมวง', up: 'ฝูงล้อมใหญ่ขึ้น ยากขึ้น' },
  'Enemy HP + at stage end': { th: 'HP มอนเพิ่มตอนท้ายด่าน (สัดส่วน)', up: 'ท้ายด่านมอนอึดขึ้น' },
  'Enemy HP + per player level': { th: 'HP มอนเพิ่มต่อเลเวลผู้เล่น', up: 'ยิ่งเลเวลสูง มอนยิ่งอึด' },
  'Enemy HP Director base': { th: 'HP มอน: ค่าฐานของสูตร Director', up: 'มอนอึดขึ้นทุกระดับ Director' },
  'Enemy HP per Director point': { th: 'HP มอนเพิ่มต่อ Director 1 แต้ม', up: 'Director สูงแล้วมอนอึดขึ้นมาก' },
  'Enemy HP × per stage': { th: 'HP มอนคูณเพิ่มต่อด่าน', up: 'ด่านหลังๆ มอนอึดขึ้นเร็วมาก' },
  'Enemy cap': { th: 'จำนวนมอนบนจอสูงสุด', up: 'มอนแน่นได้มากขึ้น (เครื่องทำงานหนักขึ้น)' },
  'Enemy cap during swarm': { th: 'จำนวนมอนสูงสุดช่วงฝูงล้อม', up: 'ช่วงฝูงล้อมมอนแน่นได้มากขึ้น' },
  'Enemy cap during swarm on phones/tablets': { th: 'จำนวนมอนสูงสุดช่วงฝูงล้อม บนมือถือ/แท็บเล็ต', up: 'มอนแน่นขึ้นบนมือถือ (อาจกระตุก)' },
  'Enemy cap on phones/tablets': { th: 'จำนวนมอนสูงสุด บนมือถือ/แท็บเล็ต', up: 'มอนแน่นขึ้นบนมือถือ (อาจกระตุก)' },
  'Enemy damage + at stage end': { th: 'ดาเมจมอนเพิ่มตอนท้ายด่าน (สัดส่วน)', up: 'ท้ายด่านมอนตีเจ็บขึ้น' },
  'Enemy damage + per player level': { th: 'ดาเมจมอนเพิ่มต่อเลเวลผู้เล่น', up: 'ยิ่งเลเวลสูง มอนยิ่งตีเจ็บ' },
  'Enemy damage × per stage': { th: 'ดาเมจมอนคูณเพิ่มต่อด่าน', up: 'ด่านหลังๆ มอนตีเจ็บขึ้นเร็ว' },
  'Enemy hit damage random ±': { th: 'ดาเมจมอนสุ่มบวกลบ (สัดส่วน)', up: 'ดาเมจที่โดนแกว่งมากขึ้น' },
  'Enemy speed + per stage': { th: 'ความเร็วมอนเพิ่มต่อด่าน', up: 'ด่านหลังๆ มอนเร็วขึ้น' },
  'Enemy speed random ±': { th: 'ความเร็วมอนสุ่มบวกลบ (สัดส่วน)', up: 'มอนเร็วไม่เท่ากันมากขึ้น' },
  'Expansion time (s)': { th: 'เวลาที่วงขยายจนเต็ม (วินาที)', up: 'วงขยายช้าลง' },
  'Extra bolts': { th: 'กระสุนเพิ่ม (หลัง Evolution)', up: 'ยิงได้หลายลูกขึ้น' },
  'Extra boss HP multiplier per stage': { th: 'HP บอสคูณเพิ่มต่อด่าน', up: 'บอสด่านหลังๆ อึดขึ้นเร็ว' },
  'Extra cyclones': { th: 'พายุเพิ่ม (หลัง Evolution)', up: 'ได้พายุหลายลูกขึ้น' },
  'Extra kills allowed per Chapter reached': { th: 'จำนวนฆ่าที่ยอมเพิ่มต่อ Chapter (กันโกง)', up: 'ตรวจหลวมขึ้น ยอมจำนวนฆ่าได้มากขึ้น' },
  'Extra lances': { th: 'หอกเพิ่ม (หลัง Evolution)', up: 'ยิงหอกได้หลายเล่มขึ้น' },
  'Extra monster HP × per Chapter beyond the last': { th: 'HP มอนคูณเพิ่มต่อ Chapter ที่เลยตอนจบ (Endless)', up: 'Endless ยากขึ้นเร็ว มอนอึดขึ้น' },
  'Extra monster damage × per Chapter beyond the last': { th: 'ดาเมจมอนคูณเพิ่มต่อ Chapter ที่เลยตอนจบ (Endless)', up: 'Endless ยากขึ้นเร็ว มอนตีเจ็บขึ้น' },
  'Extra pierce': { th: 'ทะลุมอนเพิ่ม (หลัง Evolution)', up: 'กระสุนทะลุได้หลายตัวขึ้น' },
  'Extra ring enemies per stage': { th: 'มอนในฝูงล้อมเพิ่มต่อด่าน', up: 'ด่านหลังๆ ฝูงล้อมใหญ่ขึ้นเร็ว' },
  'Extra seconds per stage': { th: 'วินาทีที่เพิ่มต่อด่าน', up: 'ด่านหลังๆ ยาวขึ้น' },
  'Extra spawns/s at stage end': { th: 'มอนเกิดเพิ่มต่อวินาที ตอนท้ายด่าน', up: 'ท้ายด่านมอนแน่นขึ้น ยากขึ้น' },
  'Fake coins': { th: 'จำนวนเหรียญปลอม', up: 'เหรียญกับดักเยอะขึ้น' },
  'Fall time (s)': { th: 'เวลาตกถึงพื้น (วินาที)', up: 'ตกช้าลง มอนอาจเดินพ้นก่อน' },
  'Fan spread (rad)': { th: 'ความกว้างการยิงแบบพัด (เรเดียน)', up: 'กระจายกว้างขึ้น' },
  'Fast Realms: fast monsters speed ×': { th: 'Realm สายเร็ว: คูณความเร็วมอนเร็ว', up: 'มอนตัวเร็วยิ่งเร็วขึ้น' },
  'Fast finish: points per second under the budget': { th: 'จบเร็ว: คะแนนต่อวินาทีที่เร็วกว่าเวลากำหนด', up: 'จบเร็วแล้วได้โบนัสมากขึ้น' },
  'Fast finish: seconds budget': { th: 'จบเร็ว: เวลาที่กำหนด (วินาที)', up: 'ได้โบนัสจบเร็วง่ายขึ้นและมากขึ้น' },
  'Final blast after the pillars (s)': { th: 'ระเบิดตรงกลางหลังเสากระดูก (วินาที)', up: 'ระเบิดช้าลง มีเวลาหนีออกมากขึ้น' },
  'Final blast damage ×': { th: 'ดาเมจระเบิดตรงกลาง (คูณ)', up: 'ระเบิดสุดท้ายเจ็บขึ้น' },
  'Final blast radius': { th: 'รัศมีระเบิดตรงกลาง', up: 'ระเบิดสุดท้ายกว้างขึ้น หนียากขึ้น' },
  'Fireball damage ×': { th: 'ดาเมจลูกไฟ (คูณ)', up: 'โดนลูกไฟแล้วเจ็บขึ้น' },
  'Fireball radius': { th: 'รัศมีลูกไฟ', up: 'ลูกไฟใหญ่ขึ้น หลบยากขึ้น' },
  'Fireball warning (s)': { th: 'เตือนก่อนลูกไฟตก (วินาที)', up: 'เตือนนานขึ้น หลบง่ายขึ้น' },
  'Fireballs per rain': { th: 'จำนวนลูกไฟต่อรอบ', up: 'ลูกไฟเยอะขึ้น หลบยากขึ้น' },
  'Firestorm: fire spreads this far through a Gathered pack': { th: 'Firestorm: ไฟลามในฝูงที่ติด Gathered ได้ไกลเท่านี้', up: 'ไฟลามไกลขึ้น โดนมอนมากขึ้น' },
  'Firestorm: spread damage × the hit': { th: 'Firestorm: ดาเมจที่ลาม (× ดาเมจที่ตี)', up: 'ไฟที่ลามแรงขึ้น' },
  'First attack delay (s)': { th: 'หน่วงก่อนโจมตีครั้งแรก (วินาที)', up: 'มีเวลาตั้งตัวมากขึ้น' },
  'First charge max (s)': { th: 'พุ่งครั้งแรก ช้าสุด (วินาที)', up: 'หมูป่าพุ่งครั้งแรกช้าลงได้' },
  'First charge min (s)': { th: 'พุ่งครั้งแรก เร็วสุด (วินาที)', up: 'หมูป่าไม่พุ่งเร็วเกินไป มีเวลาตั้งตัว' },
  'First move after a King arrives (s)': { th: 'ท่าแรกหลัง King โผล่ (วินาที)', up: 'King เริ่มออกท่าช้าลง' },
  'First shot max (s)': { th: 'ยิงนัดแรก ช้าสุด (วินาที)', up: 'นัดแรกช้าลงได้' },
  'First shot min (s)': { th: 'ยิงนัดแรก เร็วสุด (วินาที)', up: 'นัดแรกไม่เร็วเกินไป มีเวลาตั้งตัว' },
  'First stage with Blood Moon': { th: 'ด่านแรกที่มี Blood Moon ได้', up: 'Blood Moon เริ่มมาช้าลง' },
  'First stage with armored enemies': { th: 'ด่านแรกที่มีมอนเกราะ', up: 'มอนเกราะเริ่มมาช้าลง' },
  'First stage with the dragon': { th: 'ด่านแรกที่มังกรโผล่ได้', up: 'มังกรเริ่มมาช้าลง' },
  'First swarm ring (s)': { th: 'ฝูงล้อมวงแรกมาตอนวินาทีที่', up: 'ฝูงล้อมแรกมาช้าลง' },
  'First target range': { th: 'ระยะหาเป้าแรก', up: 'ยิงใส่มอนที่อยู่ไกลขึ้นได้' },
  'First warning (s)': { th: 'เตือนครั้งแรก (วินาที)', up: 'เตือนนานขึ้น หลบง่ายขึ้น' },
  'Flasks per throw': { th: 'จำนวนขวดต่อการปา (หลัง Evolution)', up: 'ปาได้หลายขวดขึ้น' },
  'Freeze damage ×': { th: 'ดาเมจตอนโดนแช่แข็ง (คูณ)', up: 'ยืนนิ่งแล้วโดนแช่แข็งเจ็บขึ้น' },
  'Frogs': { th: 'จำนวนกบ', up: 'กบพิษเยอะขึ้น' },
  'Frost Aura ticks needed to freeze a monster': { th: 'Frost Aura ต้องโดนกี่ครั้งมอนถึงแข็ง', up: 'แช่แข็งมอนยากขึ้น' },
  'Frost stacks per breath': { th: 'สะสมความเย็นต่อการพ่น 1 ครั้ง', up: 'แช่แข็งมอนได้เร็วขึ้น' },
  'Frozen (s); bosses are only slowed': { th: 'ถูกแช่แข็งนาน (วินาที; บอสแค่ช้าลง)', up: 'มอนแข็งนานขึ้น ทำ Combo ง่ายขึ้น' },
  'Full Stages the Links must have been max level and equipped': { th: 'จำนวนด่านเต็มที่ Link ต้องเลเวลเต็มและใส่อยู่', up: 'Awakening ได้ช้าลง' },
  'Game speed during that slow motion': { th: 'ความเร็วเกมตอนสโลว์โมชัน (0–1)', up: 'สโลว์น้อยลง (ใกล้ความเร็วปกติ)' },
  'Gathered lasts this long after the pull ends (s)': { th: 'สถานะ Gathered อยู่ต่อหลังหยุดดูด (วินาที)', up: 'มีเวลาทำ Combo มากขึ้น' },
  'Gear Cannon: seconds between shots': { th: 'Gear Cannon: ป้อมยิงทุกกี่วินาที', up: 'ป้อมยิงห่างขึ้น = ดาเมจรวมน้อยลง' },
  'Gear Cannon: shot damage × the strike': { th: 'Gear Cannon: ดาเมจต่อนัด (× ดาเมจ Ultimate)', up: 'ป้อมยิงแรงขึ้น' },
  'Gear Cannon: turret lasts (s)': { th: 'Gear Cannon: ป้อมอยู่นาน (วินาที)', up: 'ป้อมอยู่ช่วยนานขึ้น' },
  'Gem pull acceleration': { th: 'แรงเร่งดูดคริสตัล EXP', up: 'คริสตัลพุ่งเข้าหาตัวไวขึ้น' },
  'Gem pull max speed': { th: 'ความเร็วดูดคริสตัลสูงสุด', up: 'คริสตัลวิ่งเข้าหาตัวเร็วขึ้น' },
  'Gems on the ground before merging': { th: 'คริสตัล EXP บนพื้นได้กี่ชิ้นก่อนรวมกัน', up: 'รวมกันช้าลง (เครื่องทำงานหนักขึ้น)' },
  'Glacier Lance: monsters frozen (s); bosses slowed': { th: 'Glacier Lance: มอนถูกแช่แข็ง (วินาที; บอสแค่ช้า)', up: 'มอนแข็งนานขึ้น' },
  'Gold ceiling for Chapter 1 (per Run)': { th: 'เพดาน Gold ต่อ Run ถึง Chapter 1 (กันโกง)', up: 'ตรวจหลวมขึ้น ยอม Gold ได้มากขึ้น' },
  'Gold ceiling × per extra Chapter': { th: 'เพดาน Gold คูณเพิ่มต่อ Chapter (กันโกง)', up: 'Chapter หลังๆ ยอม Gold ได้มากขึ้น' },
  'Gold for beating Umbra when every Weapon is owned': { th: 'Gold เมื่อชนะ Umbra ตอนมี Weapon ครบแล้ว', up: 'ได้ Gold มากขึ้น' },
  'Gold for defeating it': { th: 'Gold เมื่อชนะมัน', up: 'ได้ Gold มากขึ้น' },
  'Gold per level': { th: 'Gold เพิ่มต่อเลเวล', up: 'อัป Greed แล้วได้ Gold มากขึ้น' },
  'Gold when picking up a chest': { th: 'Gold เมื่อเก็บหีบ', up: 'เปิดหีบได้ Gold มากขึ้น' },
  'Grid spacing': { th: 'ระยะห่างของตารางฟ้าผ่า', up: 'จุดผ่าห่างขึ้น หลบง่ายขึ้น' },
  'Grinder: Gathered + sweeper, damage ×': { th: 'Grinder: Gathered + สกิลกวาด คูณดาเมจ', up: 'Combo Grinder แรงขึ้น' },
  'Grip on ice (higher = less slippery)': { th: 'แรงเกาะบนน้ำแข็ง (สูง = ลื่นน้อย)', up: 'ลื่นน้อยลง บังคับง่ายขึ้น' },
  'Grown form at this level': { th: 'ได้ร่างโตเต็มวัยที่เลเวลนี้', up: 'ได้ร่างโตช้าลง' },
  'Grown form: main move size ×': { th: 'ร่างโต: ขนาดท่าหลัก (คูณ)', up: 'ร่างโตแล้วท่าใหญ่ขึ้น' },
  'Guests leave when no snapshot arrives for this long (s)': { th: 'Guest หลุดถ้าไม่ได้ข้อมูลจาก Host นานเท่านี้ (วินาที)', up: 'ทนเน็ตสะดุดได้นานขึ้นก่อนหลุดห้อง' },
  'HP after a bought revive': { th: 'HP หลังซื้อชุบชีวิต (× HP สูงสุด)', up: 'ฟื้นมาพร้อม HP มากขึ้น' },
  'HP after an ally revive': { th: 'HP หลังเพื่อนชุบ (× HP สูงสุด)', up: 'ฟื้นมาพร้อม HP มากขึ้น' },
  'HP after revive': { th: 'HP หลังฟื้น (× HP สูงสุด)', up: 'ฟื้นมาพร้อม HP มากขึ้น' },
  'HP at stage 1': { th: 'HP ที่ด่าน 1', up: 'อึดขึ้น ต้องตีนานขึ้นกว่าจะตาย' },
  'HP fraction where a King enters phase 2 (ultimate unlocked)': { th: 'King เข้าเฟส 2 (ใช้ท่าไม้ตายได้) เมื่อ HP ต่ำกว่านี้', up: 'เข้าเฟส 2 เร็วขึ้น (ตั้งแต่ HP ยังเยอะ)' },
  'HP healed per blocked projectile': { th: 'ฮีล HP ต่อกระสุนที่โล่กันได้', up: 'กันกระสุนแล้วฮีลมากขึ้น' },
  'HP healed when starting the next stage': { th: 'ฮีล HP ตอนเริ่มด่านถัดไป (× HP สูงสุด)', up: 'เริ่มด่านใหม่ด้วย HP มากขึ้น' },
  'HP of a downed player at the next stage': { th: 'HP ของคนที่ล้มเมื่อเข้าด่านถัดไป', up: 'คนที่ล้มกลับมาพร้อม HP มากขึ้น' },
  'HP the Giant leech regains × the damage it deals': { th: 'ปลิงยักษ์ฟื้น HP = ค่านี้ × ดาเมจที่ทำ', up: 'ปลิงดูดเลือดฟื้นมากขึ้น ฆ่ายากขึ้น' },
  'HP × per stage': { th: 'HP คูณเพิ่มต่อด่าน', up: 'ด่านหลังๆ อึดขึ้นเร็ว' },
  'Half angle (rad)': { th: 'ครึ่งมุมกรวย (เรเดียน)', up: 'กรวยกว้างขึ้น หลบยากขึ้น' },
  'Half arc (rad)': { th: 'ครึ่งมุมการฟัน (เรเดียน)', up: 'ฟันกว้างขึ้น โดนมอนมากขึ้น' },
  'Half width': { th: 'ครึ่งความกว้างของเส้น', up: 'เส้นอ้วนขึ้น หลบยากขึ้น' },
  'Haste max level': { th: 'Haste เลเวลสูงสุด', up: 'อัป Haste ได้มากเลเวลขึ้น' },
  'Haste: cooldown reduction per level': { th: 'Haste: ลดคูลดาวน์ต่อเลเวล', up: 'อัป Haste แล้วยิงถี่ขึ้นมากขึ้น' },
  'Hawks': { th: 'จำนวนเหยี่ยว (หลัง Evolution)', up: 'ได้เหยี่ยวหลายตัวขึ้น' },
  'Heart drop chance': { th: 'โอกาสมอนดรอปหัวใจ (0–1)', up: 'ได้ฮีลบ่อยขึ้น ง่ายขึ้น' },
  'Hit interval per enemy (s)': { th: 'ตีมอนตัวเดิมซ้ำได้ทุกกี่วินาที', up: 'ตีซ้ำช้าลง = ดาเมจรวมน้อยลง' },
  'Hit radius': { th: 'ขนาดตัว (รัศมีชน)', up: 'ตัวใหญ่ขึ้น ชนผู้เล่นง่ายขึ้นและโดนสกิลง่ายขึ้น' },
  'Hop length (s)': { th: 'เวลากระโดดแต่ละครั้ง (วินาที)', up: 'กระโดดนานขึ้น ไปได้ไกลขึ้น' },
  'Hop speed': { th: 'ความเร็วตอนกระโดด', up: 'กระโดดเร็วขึ้น เข้าประชิดไวขึ้น' },
  'How far ahead it aims (s of movement)': { th: 'เล็งดักหน้าไกลแค่ไหน (วินาทีของการเดิน)', up: 'ผ่าดักหน้าไกลขึ้น เดินตรงๆ อันตรายขึ้น' },
  'Hunting range': { th: 'ระยะล่าเป้าของเหยี่ยว', up: 'เหยี่ยวโฉบใส่มอนที่อยู่ไกลขึ้นได้' },
  'Ice breath half-angle (rad)': { th: 'ความกว้างลมน้ำแข็ง (ครึ่งมุม, เรเดียน)', up: 'ลมกว้างขึ้น หลบยากขึ้น' },
  'Ice breath interval (s)': { th: 'พ่นลมน้ำแข็งทุกกี่วินาที', up: 'พ่นห่างขึ้น = ช่วยได้น้อยลง' },
  'Ice breath length': { th: 'ระยะพ่นลมน้ำแข็ง', up: 'ลมน้ำแข็งพุ่งไปได้ไกลขึ้น' },
  'Ice pillar ring radius': { th: 'รัศมีวงเสาน้ำแข็ง', up: 'วงเสาใหญ่ขึ้น' },
  'Ice wall damage per touch': { th: 'ดาเมจกำแพงน้ำแข็งต่อการแตะ', up: 'มอนชนกำแพงแล้วเจ็บขึ้น' },
  'Ice wall interval (s)': { th: 'สร้างกำแพงน้ำแข็งทุกกี่วินาที', up: 'สร้างห่างขึ้น = ช่วยได้น้อยลง' },
  'Ice wall lasts (s)': { th: 'กำแพงน้ำแข็งอยู่นาน (วินาที)', up: 'กำแพงกันมอนได้นานขึ้น' },
  'Ice wall length': { th: 'ความยาวกำแพงน้ำแข็ง', up: 'กำแพงยาวขึ้น กันมอนได้มากขึ้น' },
  'Interval (s)': { th: 'ใช้ท่านี้ทุกกี่วินาที', up: 'ใช้ท่าห่างขึ้น ง่ายขึ้น' },
  'Interval minimum': { th: 'ใช้ท่าถี่สุดได้แค่ (วินาที)', up: 'ถึงเลเวลสูงก็ใช้ท่าถี่ได้น้อยลง ง่ายขึ้น' },
  'Interval − per level': { th: 'ใช้ท่าเร็วขึ้นต่อเลเวล (วินาที)', up: 'Rival เลเวลสูงแล้วใช้ท่าถี่ขึ้นเร็ว' },
  'Invulnerability (s)': { th: 'อมตะหลังฟื้น (วินาที)', up: 'ฟื้นแล้วปลอดภัยนานขึ้น' },
  'Invulnerability after a hit (s)': { th: 'อมตะหลังโดนตี (วินาที)', up: 'โดนแล้วมีเวลาไม่รับดาเมจนานขึ้น' },
  'Invulnerable after a bought revive (s)': { th: 'อมตะหลังซื้อชุบชีวิต (วินาที)', up: 'ฟื้นแล้วปลอดภัยนานขึ้น' },
  'Jump range': { th: 'ระยะกระโดดไปมอนตัวถัดไป', up: 'สายฟ้ากระโดดไปมอนที่ไกลขึ้นได้' },
  'Jumps multiplier (rounded)': { th: 'ตัวคูณจำนวนกระโดด (ปัดเศษ, หลัง Evolution)', up: 'Evolution แล้วกระโดดได้หลายตัวขึ้น' },
  'Keen Eye max level': { th: 'Keen Eye เลเวลสูงสุด', up: 'อัป Keen Eye ได้มากเลเวลขึ้น' },
  'Keen Eye: crit chance per level': { th: 'Keen Eye: โอกาสคริเพิ่มต่อเลเวล', up: 'อัปแล้วติดคริบ่อยขึ้นมากขึ้น' },
  'Keen Eye: crit multiplier per level': { th: 'Keen Eye: ตัวคูณคริเพิ่มต่อเลเวล', up: 'อัปแล้วคริแรงขึ้นมากขึ้น' },
  'Kill ceiling per second of real play': { th: 'เพดานจำนวนฆ่าต่อวินาทีที่เล่นจริง (กันโกง)', up: 'ตรวจหลวมขึ้น' },
  'Kills can add at most this × the time rate (1 = at most twice as fast)': { th: 'การฆ่าเติมเกจได้สูงสุด × อัตราเติมจากเวลา', up: 'ฆ่าเยอะแล้ว Ultimate เต็มเร็วขึ้นได้อีก' },
  'King HP × in the account\'s very first Greenvale': { th: 'HP King × ใน Greenvale ครั้งแรกของบัญชี', up: 'Run แรกยากขึ้น (ใกล้ปกติ)' },
  'King damage × in overtime': { th: 'ดาเมจ King ช่วงต่อเวลา (คูณ)', up: 'ช่วงต่อเวลา King ตีเจ็บขึ้น' },
  'King intro card length (s)': { th: 'การ์ดแนะนำ King แสดงนาน (วินาที)', up: 'การ์ดโชว์นานขึ้น' },
  'King reward Gold × Chapter': { th: 'Gold รางวัลจาก King × Chapter', up: 'ฆ่า King ได้ Gold มากขึ้น' },
  'King speed × in overtime': { th: 'ความเร็ว King ช่วงต่อเวลา (คูณ)', up: 'ช่วงต่อเวลา King เร็วขึ้น' },
  'Knockback': { th: 'แรงกระเด็น', up: 'มอนกระเด็นไกลขึ้น' },
  'Knockback left after 1 s': { th: 'แรงกระเด็นที่เหลือหลัง 1 วินาที (0–1)', up: 'มอนไถลนานและไกลขึ้น' },
  'Knockback × on bosses': { th: 'แรงกระเด็นกับบอส (คูณ)', up: 'บอสกระเด็นได้มากขึ้น' },
  'Knockback × on elites': { th: 'แรงกระเด็นกับ elite (คูณ)', up: 'elite กระเด็นได้มากขึ้น' },
  'Lance speed': { th: 'ความเร็วหอก', up: 'หอกพุ่งเร็วขึ้น หลบยากขึ้น' },
  'Landing radius': { th: 'รัศมีจุดตกลงพื้น', up: 'จุดตกกว้างขึ้น หลบยากขึ้น' },
  'Laser positions in the sweep': { th: 'จำนวนตำแหน่งเลเซอร์ในการกวาด', up: 'กวาดได้กว้างขึ้น/นานขึ้น' },
  'Last Chapter with special events (the finale has none)': { th: 'Chapter สุดท้ายที่มีอีเวนต์พิเศษ (ด่านจบไม่มี)', up: 'มีอีเวนต์พิเศษได้ใน Chapter หลังๆ มากขึ้น' },
  'Lasts (s)': { th: 'อยู่นาน (วินาที)', up: 'พื้นน้ำแข็งอยู่นานขึ้น' },
  'Late curve starts after level': { th: 'EXP ช่วงท้ายเริ่มโหดหลังเลเวลนี้', up: 'เลเวลอัปง่ายได้นานขึ้น' },
  'Late curve: × (level − start)²': { th: 'EXP ช่วงท้าย: × (เลเวล − จุดเริ่ม)²', up: 'เลเวลสูงๆ อัปยากขึ้นมาก' },
  'Length': { th: 'ความยาว', up: 'ท่ายาวขึ้น หลบยากขึ้น' },
  'Level offset': { th: 'เลเวลที่เริ่มนับ', up: 'ได้ +1 ช้าลง (ต้องเลเวลสูงขึ้น)' },
  'Level-up offer weight: Companion grows stronger': { th: 'น้ำหนักการ์ดเลเวลอัป: คู่หูแข็งแกร่งขึ้น', up: 'การ์ดอัปคู่หูโผล่บ่อยขึ้น' },
  'Levels for defeating the same Guardian again': { th: 'เลเวลคู่หูที่ได้เมื่อชนะ Guardian ตัวเดิมซ้ำ', up: 'ชนะซ้ำแล้วคู่หูเก่งขึ้นเร็ว' },
  'Levels per +1': { th: 'ทุกกี่เลเวลถึงได้ +1', up: 'ต้องอัปหลายเลเวลกว่าจะ +1 = เพิ่มช้าลง' },
  'Lich Tome: HP healed per monster hit (× max HP)': { th: 'Lich Tome: ฮีล HP ต่อมอนที่โดน (× HP สูงสุด)', up: 'ใช้ Ultimate แล้วฮีลมากขึ้น' },
  'Lich Tome: most HP healed per Ultimate (× max HP)': { th: 'Lich Tome: ฮีลสูงสุดต่อ Ultimate (× HP สูงสุด)', up: 'ฮีลต่อครั้งได้สูงขึ้น' },
  'Lich Tome: pull toward you': { th: 'Lich Tome: แรงดูดมอนเข้าหาตัว', up: 'ดูดมอนเข้ามาแรงขึ้น' },
  'Lifetime (s)': { th: 'อยู่นาน (วินาที)', up: 'หลุมดำอยู่นานขึ้น ดูดและตีได้นานขึ้น' },
  'Light radius around the player in the dark': { th: 'รัศมีแสงรอบตัวตอนมืด', up: 'มองเห็นได้กว้างขึ้น ง่ายขึ้น' },
  'Lightning rows': { th: 'จำนวนแถวฟ้าผ่า', up: 'ฟ้าผ่าหลายแถวขึ้น หลบยากขึ้น' },
  'Lightning strike interval (s)': { th: 'ฟ้าผ่าทุกกี่วินาที', up: 'ผ่าห่างขึ้น = ช่วยได้น้อยลง' },
  'Longest pause between King moves (s)': { th: 'พักระหว่างท่า King นานสุด (วินาที)', up: 'King ออกท่าห่างขึ้น ง่ายขึ้น' },
  'Longest stage (s)': { th: 'ด่านยาวสุด (วินาที)', up: 'ด่านหลังๆ ยาวได้มากขึ้น' },
  'Lower limit': { th: 'ขั้นต่ำ', up: 'ค่าจะไม่ต่ำกว่านี้ เช่นคูลดาวน์เร็วสุดได้แค่นี้' },
  'Magma Maul: knockback × (and Burning)': { th: 'Magma Maul: คูณแรงกระเด็น (และติด Burning)', up: 'มอนกระเด็นไกลขึ้น' },
  'Magnet max level': { th: 'Magnet เลเวลสูงสุด', up: 'อัป Magnet ได้มากเลเวลขึ้น' },
  'Magnet: pickup range per level': { th: 'Magnet: ระยะดูดของเพิ่มต่อเลเวล', up: 'อัปแล้วดูดของได้ไกลขึ้นมากขึ้น' },
  'Max Companion level': { th: 'เลเวลคู่หูสูงสุด', up: 'คู่หูอัปได้สูงขึ้น' },
  'Max HP bonus': { th: 'โบนัส HP สูงสุด', up: 'ตัวละครนี้อึดขึ้น' },
  'Max HP per level': { th: 'HP สูงสุดเพิ่มต่อเลเวล', up: 'อัปแล้วอึดขึ้นมากขึ้น' },
  'Max level': { th: 'เลเวลสูงสุด', up: 'อัปได้มากเลเวลขึ้น เก่งได้สูงขึ้น' },
  'Max-level Links needed (and consumed)': { th: 'จำนวน Link เลเวลเต็มที่ต้องใช้ (และถูกใช้ไป)', up: 'Awakening ยากขึ้น' },
  'Maximum': { th: 'ค่าสูงสุด', up: 'Director ดันความยากได้สูงขึ้น' },
  'Meteors multiplier (rounded)': { th: 'ตัวคูณจำนวนอุกกาบาต (ปัดเศษ, หลัง Evolution)', up: 'Evolution แล้วได้อุกกาบาตเยอะขึ้น' },
  'Might max level': { th: 'Might เลเวลสูงสุด', up: 'อัป Might ได้มากเลเวลขึ้น' },
  'Might: damage per level': { th: 'Might: ดาเมจเพิ่มต่อเลเวล', up: 'อัป Might แล้วแรงขึ้นมากขึ้น' },
  'Minimum': { th: 'ค่าต่ำสุด', up: 'Director ผ่อนความยากได้น้อยลง' },
  'Minimum seconds between two start_run calls': { th: 'เริ่ม Run ใหม่ได้ห่างกันอย่างน้อย (วินาที)', up: 'กันสแปมเข้มขึ้น' },
  'Minis on death': { th: 'สไลม์ลูกที่แตกออกมาตอนตาย', up: 'แตกเป็นลูกเยอะขึ้น' },
  'Minus per King that escaped': { th: 'หักคะแนนต่อ King ที่หนีไป', up: 'ปล่อย King หนีแล้วเสียคะแนนมากขึ้น' },
  'Missing pillars (the way out)': { th: 'ช่องว่างในกรง (ทางออก)', up: 'ทางออกกว้างขึ้น หนีง่ายขึ้น' },
  'Most Gold a one-time legacy save upload may bring': { th: 'Gold สูงสุดที่นำเข้าจากเซฟเก่าได้ (ครั้งเดียว)', up: 'ยอมนำ Gold จากเซฟเก่าเข้ามาได้มากขึ้น' },
  'Only when the player is this close': { th: 'ใช้เมื่อผู้เล่นอยู่ใกล้กว่าระยะนี้', up: 'ใช้ท่านี้ได้จากไกลขึ้น' },
  'Orb damage ×': { th: 'ดาเมจลูกบอลสายฟ้า (คูณ)', up: 'โดนลูกบอลแล้วเจ็บขึ้น' },
  'Orb life (s)': { th: 'ลูกบอลอยู่นาน (วินาที)', up: 'ลูกบอลเด้งอยู่นานขึ้น' },
  'Orb speed': { th: 'ความเร็วลูกบอล', up: 'ลูกบอลเร็วขึ้น หลบยากขึ้น' },
  'Overload radius': { th: 'รัศมีระเบิด Overload', up: 'ระเบิดกว้างขึ้น โดนมอนมากขึ้น' },
  'Overload: Shocked + fire, explosion × the hit': { th: 'Overload: Shocked + ไฟ ระเบิด (× ดาเมจที่ตี)', up: 'Combo Overload แรงขึ้น' },
  'Overtime after the timer while the King lives (s)': { th: 'ต่อเวลาหลังหมดเวลา ถ้า King ยังไม่ตาย (วินาที)', up: 'มีเวลาฆ่า King มากขึ้นก่อนมันหนี' },
  'Page speed': { th: 'ความเร็วหน้ากระดาษ', up: 'กระดาษพุ่งเร็วขึ้น หลบยากขึ้น' },
  'Particle cap (desktop)': { th: 'จำนวนเอฟเฟกต์สูงสุด (คอมพิวเตอร์)', up: 'เอฟเฟกต์อลังการขึ้น เครื่องหนักขึ้น' },
  'Particle cap (phones/tablets)': { th: 'จำนวนเอฟเฟกต์สูงสุด (มือถือ/แท็บเล็ต)', up: 'เอฟเฟกต์เยอะขึ้น มือถืออาจกระตุก' },
  'Passive slots': { th: 'ช่อง Passive', up: 'ถือ Passive ได้มากขึ้น' },
  'Path wobble (rad)': { th: 'มอนเดินส่ายไปมา (เรเดียน)', up: 'มอนเดินส่ายมากขึ้น ไม่พุ่งตรงเข้าหาเรา' },
  'Pause between clear and the results screen (s)': { th: 'พักหลังผ่านด่านก่อนขึ้นหน้าสรุป (วินาที)', up: 'รอนานขึ้นก่อนเห็นหน้าสรุป' },
  'Per Chapter cleared × Chapter number': { th: 'คะแนนต่อ Chapter ที่ผ่าน × เลข Chapter', up: 'ผ่าน Chapter แล้วได้คะแนนมากขึ้น' },
  'Per King killed × Chapter number': { th: 'คะแนนต่อ King ที่ฆ่า × เลข Chapter', up: 'ฆ่า King แล้วได้คะแนนมากขึ้น' },
  'Per elemental Combo': { th: 'คะแนนต่อ Combo ธาตุ', up: 'ทำ Combo แล้วได้คะแนนมากขึ้น' },
  'Per monster': { th: 'คะแนนต่อมอน 1 ตัว', up: 'ฆ่ามอนแล้วได้คะแนนมากขึ้น' },
  'Per-enemy hit cooldown (s)': { th: 'ตีมอนตัวเดิมซ้ำได้ทุกกี่วินาที', up: 'ตีซ้ำช้าลง = ดาเมจรวมน้อยลง' },
  'Pickup range bonus': { th: 'โบนัสระยะดูดของ', up: 'ตัวละครนี้ดูดของได้ไกลขึ้น' },
  'Pillar damage ×': { th: 'ดาเมจเสากระดูก (คูณ)', up: 'โดนเสาแล้วเจ็บขึ้น' },
  'Pillar radius': { th: 'รัศมีเสากระดูก', up: 'เสาใหญ่ขึ้น ที่เดินน้อยลง' },
  'Plague Censer: Poisoned damage per second × the strike': { th: 'Plague Censer: ดาเมจพิษต่อวินาที (× ดาเมจ Ultimate)', up: 'พิษแรงขึ้น' },
  'Player chilled by the breath (s)': { th: 'ผู้เล่นติดหนาว (เดินช้า) หลังโดนลม (วินาที)', up: 'เดินช้านานขึ้น อันตรายขึ้น' },
  'Player hit radius': { th: 'รัศมีตัวผู้เล่น (ที่โดนชน)', up: 'ตัวใหญ่ขึ้น โดนมอนชนง่ายขึ้น' },
  'Poisoned (s)': { th: 'สถานะ Poisoned (ติดพิษ) นาน (วินาที)', up: 'พิษอยู่นานขึ้น ทำ Combo ง่ายขึ้น' },
  'Price × per level': { th: 'ราคาคูณเพิ่มต่อเลเวล', up: 'อัปเลเวลหลังๆ แพงขึ้นเร็ว' },
  'Projectile block radius': { th: 'รัศมีที่โล่กันกระสุนได้', up: 'โล่กันกระสุนได้ง่ายขึ้น' },
  'Projectile life (s)': { th: 'กระสุนอยู่นาน (วินาที)', up: 'กระสุนบินได้ไกลขึ้นก่อนหายไป' },
  'Projectile speed': { th: 'ความเร็วกระสุน', up: 'กระสุนพุ่งเร็วขึ้น' },
  'Puff interval (s)': { th: 'พ่นควันทุกกี่วินาที', up: 'พ่นห่างขึ้น = ดาเมจรวมน้อยลง' },
  'Pull radius': { th: 'รัศมีที่ดูดเข้าไป', up: 'ดูดจากไกลขึ้น หนียากขึ้น' },
  'Pull speed': { th: 'แรงดูด', up: 'ดูดแรงขึ้น' },
  'Pull time (s)': { th: 'ดูดนาน (วินาที)', up: 'ต้องฝืนเดินหนีนานขึ้น' },
  'Push speed': { th: 'แรงผลักสไลม์ลูกตอนแตก', up: 'สไลม์ลูกกระเด็นออกไปไกลขึ้น' },
  'Push-out knockback': { th: 'แรงผลักมอนออกจากโดม', up: 'มอนถูกผลักออกไปไกลขึ้น' },
  'Radius': { th: 'รัศมี', up: 'วงกว้างขึ้น กินพื้นที่มากขึ้น' },
  'Radius multiplier': { th: 'ตัวคูณรัศมีหลัง Evolution', up: 'Evolution แล้ววงใหญ่ขึ้น' },
  'Range': { th: 'ระยะ', up: 'ใช้กับมอนที่อยู่ไกลขึ้นได้' },
  'Re-picks of the same Chapter after an Escape': { th: 'เลือก Realm ใหม่ใน Chapter เดิมได้กี่ครั้งหลัง Escape', up: 'ให้โอกาสแก้ตัวหลัง King หนีได้มากขึ้น' },
  'Real play time needed ≥ this × the length of the Stages cleared': { th: 'เวลาเล่นจริงต้อง ≥ ค่านี้ × ความยาวด่านที่ผ่าน (กันโกง)', up: 'ตรวจเข้มขึ้น เล่นเร็วผิดปกติจะถูกปฏิเสธ' },
  'Recycle distance (× view diagonal)': { th: 'ระยะที่มอนไกลเกินจะถูกย้ายกลับมา (× ทแยงจอ)', up: 'มอนหลุดออกไปได้ไกลขึ้นก่อนถูกย้ายกลับ' },
  'Ring damage ×': { th: 'ดาเมจวงเสาน้ำแข็ง (คูณ)', up: 'โดนวงแล้วเจ็บขึ้น' },
  'Ring expansion (s)': { th: 'เวลาที่วงขยาย (วินาที)', up: 'วงขยายช้าลง หนีทันง่ายขึ้น' },
  'Ring radius': { th: 'รัศมีวง', up: 'วงใหญ่ขึ้น หนียากขึ้น' },
  'Ring radius around the player': { th: 'รัศมีวงรอบตัวผู้เล่น', up: 'วงห่างตัวมากขึ้น' },
  'Ring radius per level': { th: 'รัศมีวงเพิ่มต่อเลเวล', up: 'Rival เลเวลสูงแล้ววงใหญ่ขึ้นเร็ว' },
  'Ring travel time (s)': { th: 'เวลาที่วงวิ่งออกไป (วินาที)', up: 'วงวิ่งช้าลง หลบง่ายขึ้น' },
  'Rise per second while cruising': { th: 'Director เพิ่มขึ้นต่อวินาทีตอนเล่นสบาย', up: 'เล่นเก่งแล้วเกมยากขึ้นเร็วขึ้น' },
  'Rival arrives at stage fraction': { th: 'Rival มาเมื่อด่านผ่านไปสัดส่วนนี้ (0–1)', up: 'Rival มาช้าลง' },
  'Route vote time (s); the host breaks ties': { th: 'เวลาโหวตเลือกเส้นทาง (วินาที; Host ตัดสินถ้าเสมอ)', up: 'มีเวลาโหวตนานขึ้น' },
  'Row damage ×': { th: 'ดาเมจแถวฟ้าผ่า (คูณ)', up: 'โดนฟ้าผ่าแล้วเจ็บขึ้น' },
  'Row warning (s)': { th: 'เตือนก่อนฟ้าผ่าเป็นแถว (วินาที)', up: 'เตือนนานขึ้น หลบง่ายขึ้น' },
  'Run submissions per player per hour': { th: 'ส่งผล Run ได้กี่ครั้งต่อคนต่อชั่วโมง', up: 'ส่งได้บ่อยขึ้น (กันสแปมหลวมขึ้น)' },
  'Safe circle radius': { th: 'รัศมีวงปลอดภัย', up: 'วงปลอดภัยใหญ่ขึ้น หลบง่ายขึ้น' },
  'Safe circles': { th: 'จำนวนวงปลอดภัย', up: 'มีวงให้หลบมากขึ้น ง่ายขึ้น' },
  'Safe circles distance from the player': { th: 'วงปลอดภัยห่างจากผู้เล่น', up: 'ต้องวิ่งไกลขึ้นไปหาวง ยากขึ้น' },
  'Safe pool radius': { th: 'รัศมีบ่อปลอดภัย', up: 'บ่อใหญ่ขึ้น หลบง่ายขึ้น' },
  'Second half after (s)': { th: 'ฟ้าผ่าครึ่งหลังตามมาหลัง (วินาที)', up: 'มีเวลาย้ายที่มากขึ้น' },
  'Second move from this level': { th: 'ได้ท่าที่สองตั้งแต่เลเวลนี้', up: 'ได้ท่าที่สองช้าลง' },
  'Seconds before it escapes': { th: 'เวลาก่อนมันหนีไป (วินาที)', up: 'มีเวลาฆ่ามากขึ้น ง่ายขึ้น' },
  'Seconds between hops': { th: 'กระโดดทุกกี่วินาที', up: 'กระโดดห่างขึ้น เข้าหาช้าลง' },
  'Seconds between kills to keep the Kill Streak': { th: 'ฆ่าห่างกันได้ไม่เกินกี่วินาทีเพื่อรักษา Kill Streak', up: 'รักษา Kill Streak ง่ายขึ้น' },
  'Seconds counted as right after a hit': { th: 'นับว่า "เพิ่งโดนตี" นานกี่วินาที', up: 'Director ผ่อนหลังโดนตีได้นานขึ้น' },
  'Seconds of low FPS before the suggestion': { th: 'FPS ต่ำนานกี่วินาทีถึงแนะนำให้ลดเอฟเฟกต์', up: 'แนะนำช้าลง' },
  'Seconds standing next to a downed ally to revive them': { th: 'ยืนข้างเพื่อนที่ล้มกี่วินาทีถึงชุบได้', up: 'ชุบเพื่อนช้าลง ยากขึ้น' },
  'Seconds to fill from time alone': { th: 'เกจ Ultimate เต็มจากเวลาอย่างเดียวในกี่วินาที', up: 'Ultimate ใช้ได้ห่างขึ้น' },
  'Shadow Rival chance on normal stages': { th: 'โอกาสเจอ Shadow Rival ในด่านปกติ (0–1)', up: 'เจอ Rival บ่อยขึ้น' },
  'Shadow bolt damage ×': { th: 'ดาเมจกระสุนเงา (คูณ)', up: 'โดนกระสุนเงาแล้วเจ็บขึ้น' },
  'Shadow bolt speed': { th: 'ความเร็วกระสุนเงา', up: 'กระสุนเร็วขึ้น หลบยากขึ้น' },
  'Shadow bolts per fan': { th: 'จำนวนกระสุนเงาต่อพัด', up: 'กระสุนเยอะขึ้น หลบยากขึ้น' },
  'Shadow meteor damage ×': { th: 'ดาเมจอุกกาบาตเงา (คูณ)', up: 'โดนอุกกาบาตแล้วเจ็บขึ้น' },
  'Shadow meteor radius': { th: 'รัศมีอุกกาบาตเงา', up: 'อุกกาบาตใหญ่ขึ้น หลบยากขึ้น' },
  'Shadow meteor warning (s)': { th: 'เตือนก่อนอุกกาบาตเงาตก (วินาที)', up: 'เตือนนานขึ้น หลบง่ายขึ้น' },
  'Shadow meteors': { th: 'จำนวนอุกกาบาตเงา', up: 'อุกกาบาตเยอะขึ้น หลบยากขึ้น' },
  'Shards for a guaranteed clone': { th: 'เศษที่ต้องสะสมเพื่อได้ Clone แน่นอน', up: 'ต้องสะสมนานขึ้นกว่าจะได้ Clone' },
  'Share of the Score lost when buying a revive': { th: 'สัดส่วน Score ที่เสียเมื่อซื้อชุบชีวิต', up: 'ซื้อชุบชีวิตแล้วเสียคะแนนมากขึ้น' },
  'Shatter shard radius': { th: 'รัศมีเศษน้ำแข็ง Shatter', up: 'เศษน้ำแข็งกระจายกว้างขึ้น' },
  'Shatter: Frozen + heavy hit, damage ×': { th: 'Shatter: Frozen + ตีหนัก คูณดาเมจ', up: 'Combo Shatter แรงขึ้น' },
  'Shatter: ice shards hit nearby for × the hit': { th: 'Shatter: เศษน้ำแข็งโดนมอนรอบๆ (× ดาเมจที่ตี)', up: 'เศษน้ำแข็งแรงขึ้น' },
  'Shields': { th: 'จำนวนโล่ (หลัง Evolution)', up: 'โล่หมุนรอบตัวมากขึ้น' },
  'Shocked (s)': { th: 'สถานะ Shocked (ติดช็อต) นาน (วินาที)', up: 'ติดช็อตนานขึ้น ทำ Combo ง่ายขึ้น' },
  'Shooting range': { th: 'ระยะยิง', up: 'ยิงจากไกลขึ้นได้' },
  'Shortest pause between King moves (s)': { th: 'พักระหว่างท่า King สั้นสุด (วินาที)', up: 'King ออกท่าถี่ได้น้อยลง ง่ายขึ้น' },
  'Shot interval max (s)': { th: 'ยิงห่างกัน นานสุด (วินาที)', up: 'ยิงห่างขึ้นได้ ง่ายขึ้น' },
  'Shot interval min (s)': { th: 'ยิงห่างกัน สั้นสุด (วินาที)', up: 'ยิงถี่ได้น้อยลง ง่ายขึ้น' },
  'Shot speed': { th: 'ความเร็วกระสุน', up: 'กระสุนเร็วขึ้น หลบยากขึ้น' },
  'Show a "×N KO!" popup every N kills of a streak': { th: 'โชว์ป้าย "×N KO!" ทุกๆ N ฆ่าใน Streak', up: 'ป้ายโผล่ห่างขึ้น' },
  'Sigils per cast': { th: 'จำนวน Sigil ต่อครั้ง (หลัง Evolution)', up: 'วาง Sigil ได้หลายวงขึ้น' },
  'Skeletons': { th: 'จำนวนโครงกระดูก', up: 'โครงกระดูกโผล่เยอะขึ้น' },
  'Skill Points for +1 Companion level': { th: 'Skill Point ที่ใช้อัปคู่หู +1 เลเวล', up: 'อัปคู่หูแพงขึ้น' },
  'Skill Points per King killed': { th: 'Skill Point ที่ได้ต่อ King ที่ฆ่า', up: 'ได้ Skill Point มากขึ้น' },
  'Skill Points: +1 level to a chosen attack Skill': { th: 'Skill Point ที่ใช้: +1 เลเวลสกิลโจมตีที่เลือก', up: 'อัปสกิลด้วยแต้มแพงขึ้น' },
  'Skill Points: banish a Skill/passive from this Run': { th: 'Skill Point ที่ใช้: แบนสกิล/Passive ออกจาก Run', up: 'แบนแพงขึ้น' },
  'Skill Points: reroll the level-up offers': { th: 'Skill Point ที่ใช้: สุ่มตัวเลือกเลเวลอัปใหม่', up: 'สุ่มใหม่แพงขึ้น' },
  'Skill damage bonus': { th: 'โบนัสดาเมจสกิล', up: 'ตัวละครนี้ตีแรงขึ้น' },
  'Skill damage random ±': { th: 'ดาเมจสกิลสุ่มบวกลบ (สัดส่วน)', up: 'ดาเมจแต่ละครั้งแกว่งมากขึ้น' },
  'Skills it uses (of 5)': { th: 'จำนวนสกิลที่ Rival ใช้ (จาก 5)', up: 'Rival มีท่าหลากหลายขึ้น ยากขึ้น' },
  'Slimes spawned': { th: 'จำนวนสไลม์ที่แตกออกมา', up: 'สไลม์เยอะขึ้น' },
  'Slow-motion after a King dies (real seconds)': { th: 'สโลว์โมชันหลัง King ตาย (วินาทีจริง)', up: 'สโลว์นานขึ้น' },
  'Slow-motion time (s)': { th: 'เวลาสโลว์โมชัน (วินาที)', up: 'สโลว์นานขึ้น' },
  'Small heart heal (× max HP)': { th: 'หัวใจเล็กฮีล (× HP สูงสุด)', up: 'เก็บหัวใจแล้วฮีลมากขึ้น' },
  'Soul bolts': { th: 'จำนวนลูกวิญญาณ', up: 'ลูกเยอะขึ้น หลบยากขึ้น' },
  'Spawn distance beyond the view edge': { th: 'มอนเกิดห่างจากขอบจอเท่านี้', up: 'มอนเกิดไกลขึ้น ใช้เวลาเดินมาถึงนานขึ้น' },
  'Spawn multiplier per extra living player': { th: 'คูณอัตราเกิดมอนต่อผู้เล่นที่ยังรอดเพิ่ม', up: 'เล่นหลายคนแล้วมอนแน่นขึ้น' },
  'Spawn rate growth per stage': { th: 'อัตราเกิดมอนเพิ่มต่อด่าน', up: 'ด่านหลังๆ มอนแน่นขึ้นเร็ว' },
  'Spawn rate × in overtime': { th: 'คูณอัตราเกิดมอนช่วงต่อเวลา', up: 'ช่วงต่อเวลามอนแน่นขึ้น' },
  'Spawn rate × in that first Greenvale': { th: 'คูณอัตราเกิดมอนใน Greenvale ครั้งแรก', up: 'Run แรกมอนแน่นขึ้น (ใกล้ปกติ)' },
  'Spawn ring radius': { th: 'รัศมีวงที่สไลม์เกิด', up: 'สไลม์เกิดห่างออกไปมากขึ้น' },
  'Spawn spread': { th: 'ระยะกระจายตอนแตก', up: 'สไลม์ลูกกระจายห่างกันมากขึ้น' },
  'Spawns/s at stage start': { th: 'มอนเกิดต่อวินาที ตอนเริ่มด่าน', up: 'มอนเกิดถี่ขึ้น เกมยากขึ้น' },
  'Spears': { th: 'จำนวนหอก', up: 'หอกเยอะขึ้น หลบยากขึ้น' },
  'Speed': { th: 'ความเร็ว', up: 'เดินเร็วขึ้น ไล่ทันผู้เล่นง่ายขึ้น' },
  'Speed bonus': { th: 'โบนัสความเร็ว', up: 'ตัวละครนี้เดินเร็วขึ้น' },
  'Speed kept by slowed enemies (Frost Aura, Toxic Pool)': { th: 'ความเร็วที่มอนเหลือตอนโดนสโลว์ (0–1)', up: 'สโลว์อ่อนลง มอนเดินเร็วขึ้น' },
  'Speed kept while frozen': { th: 'ความเร็วที่เหลือตอนโดนแช่แข็ง (0–1)', up: 'แช่แข็งได้ผลน้อยลง' },
  'Speed kept while slowed': { th: 'ความเร็วที่เหลือตอนโดนสโลว์ (0–1)', up: 'สโลว์ได้ผลน้อยลง' },
  'Speed penalty': { th: 'ความเร็วที่ลดลง', up: 'ตัวละครนี้เดินช้าลง' },
  'Speed per level': { th: 'ความเร็วเพิ่มต่อเลเวล', up: 'อัปแล้วเดินเร็วขึ้นมากขึ้น' },
  'Speed × while chilled': { th: 'ความเร็วตอนติดหนาว (คูณ)', up: 'ติดหนาวแล้วช้าน้อยลง' },
  'Spin multiplier': { th: 'ตัวคูณความเร็วหมุน (หลัง Evolution)', up: 'ใบมีดหมุนเร็วขึ้น' },
  'Spray time (s)': { th: 'พ่นนาน (วินาที)', up: 'พ่นนานขึ้น ต้องหลบนานขึ้น' },
  'Stage 1 length (s)': { th: 'ความยาวด่าน 1 (วินาที)', up: 'ด่านแรกยาวขึ้น' },
  'Stage-end: wait for everyone to be ready at most (s)': { th: 'จบด่าน: รอทุกคนพร้อมได้นานสุด (วินาที)', up: 'รอเพื่อนได้นานขึ้น' },
  'Stages per rival skill level': { th: 'ทุกกี่ด่านสกิล Rival +1 เลเวล', up: 'Rival เก่งขึ้นช้าลง' },
  'Standing still this long freezes you (s)': { th: 'ยืนนิ่งนานเท่านี้จะโดนแช่แข็ง (วินาที)', up: 'ยืนนิ่งได้นานขึ้น ง่ายขึ้น' },
  'Starting value': { th: 'ค่าเริ่มต้น', up: 'เริ่มเกมยากขึ้น' },
  'Statuses last longer by': { th: 'สถานะอยู่นานขึ้น (สัดส่วน)', up: 'Status ของ Vex อยู่นานขึ้น' },
  'Stored Companions (besides the active one)': { th: 'จำนวนคู่หูที่เก็บไว้ได้ (ไม่รวมตัวที่ใช้)', up: 'เก็บคู่หูสำรองได้มากขึ้น' },
  'Strafe speed ×': { th: 'ความเร็วเดินด้านข้าง (คูณ)', up: 'เดินวนหลบเร็วขึ้น ตียากขึ้น' },
  'Strike delay (s)': { th: 'หน่วงก่อนฟาด (วินาที)', up: 'Ultimate ออกผลช้าลง' },
  'Strike radius': { th: 'รัศมีฟ้าผ่า', up: 'ฟ้าผ่ากว้างขึ้น' },
  'Strikes': { th: 'จำนวนฟ้าผ่า', up: 'ผ่าหลายครั้งขึ้น หลบยากขึ้น' },
  'Struggling: HP below this fraction': { th: 'เล่นลำบาก: HP ต่ำกว่าสัดส่วนนี้', up: 'Director เริ่มผ่อนความยากตั้งแต่ HP ยังเยอะ' },
  'Stun (s); bosses are slowed': { th: 'สตัน (วินาที; บอสแค่ช้าลง)', up: 'มอนมึนนานขึ้น' },
  'Suggest lowering effects when FPS stays under this': { th: 'แนะนำลดเอฟเฟกต์เมื่อ FPS ต่ำกว่านี้', up: 'แนะนำง่ายขึ้น (เครื่องแรงก็โดนแนะนำ)' },
  'Summon only below this many whelps': { th: 'เรียกลูกมังกรได้เมื่อมีน้อยกว่าจำนวนนี้', up: 'มีลูกมังกรพร้อมกันได้มากขึ้น' },
  'Superconduct: Frozen + lightning, armour removed for (s)': { th: 'Superconduct: Frozen + สายฟ้า ลบเกราะนาน (วินาที)', up: 'มอนไม่มีเกราะนานขึ้น' },
  'Swap cost: Gold × Chapter': { th: 'ราคาสลับสกิล: Gold × Chapter', up: 'สลับสกิลแพงขึ้น' },
  'Swarm interval in Blood Moon (s)': { th: 'ฝูงล้อมมาทุกกี่วินาทีใน Blood Moon', up: 'ฝูงล้อมมาห่างขึ้น ง่ายขึ้น' },
  'Swarm ring distance beyond the view edge': { th: 'ฝูงล้อมเกิดห่างจากขอบจอเท่านี้', up: 'ฝูงล้อมเกิดไกลขึ้น มาถึงช้าลง' },
  'Swarm ring interval (s)': { th: 'ฝูงล้อมมาทุกกี่วินาที', up: 'ฝูงล้อมมาห่างขึ้น ง่ายขึ้น' },
  'Sweep time (s)': { th: 'เวลากวาดลำแสง (วินาที)', up: 'กวาดช้าลง' },
  'Swift Boots: speed per level': { th: 'Swift Boots: ความเร็วเพิ่มต่อเลเวล', up: 'อัปแล้วเดินเร็วขึ้นมากขึ้น' },
  'Swift max level': { th: 'Swift Boots เลเวลสูงสุด', up: 'อัป Swift Boots ได้มากเลเวลขึ้น' },
  'Swing time (s)': { th: 'เวลาฟันแต่ละครั้ง (วินาที)', up: 'ฟันช้าลง' },
  'Targeting range': { th: 'ระยะหาเป้า', up: 'ยิงใส่มอนที่อยู่ไกลขึ้นได้' },
  'Telegraph time (s)': { th: 'เวลาเตือนก่อนพุ่ง (วินาที)', up: 'เตือนนานขึ้น หลบง่ายขึ้น' },
  'The same Combo can hit the same monster again after (s)': { th: 'Combo เดิมกับมอนตัวเดิมเกิดซ้ำได้หลัง (วินาที)', up: 'Combo ซ้ำช้าลง ดาเมจรวมน้อยลง' },
  'Thornwhip: monsters rooted (s)': { th: 'Thornwhip: มอนถูกตรึงอยู่กับที่ (วินาที)', up: 'มอนขยับไม่ได้นานขึ้น' },
  'Throw range': { th: 'ระยะปา', up: 'ปาใส่มอนที่อยู่ไกลขึ้นได้' },
  'Throw time (s)': { th: 'เวลาขวดลอยถึงเป้า (วินาที)', up: 'ขวดถึงเป้าช้าลง' },
  'Tier 1: monster HP ×': { th: 'ระดับ 1: HP มอน (คูณ)', up: 'มอนอึดขึ้น' },
  'Tier 1: monster damage ×': { th: 'ระดับ 1: ดาเมจมอน (คูณ)', up: 'มอนตีเจ็บขึ้น' },
  'Tier 1: spawn rate ×': { th: 'ระดับ 1: อัตราเกิดมอน (คูณ)', up: 'มอนแน่นขึ้น' },
  'Tier 2: monster HP ×': { th: 'ระดับ 2: HP มอน (คูณ)', up: 'มอนอึดขึ้น' },
  'Tier 2: monster damage ×': { th: 'ระดับ 2: ดาเมจมอน (คูณ)', up: 'มอนตีเจ็บขึ้น' },
  'Tier 2: spawn rate ×': { th: 'ระดับ 2: อัตราเกิดมอน (คูณ)', up: 'มอนแน่นขึ้น' },
  'Tier 3: monster HP ×': { th: 'ระดับ 3: HP มอน (คูณ)', up: 'มอนอึดขึ้น' },
  'Tier 3: monster damage ×': { th: 'ระดับ 3: ดาเมจมอน (คูณ)', up: 'มอนตีเจ็บขึ้น' },
  'Tier 3: spawn rate ×': { th: 'ระดับ 3: อัตราเกิดมอน (คูณ)', up: 'มอนแน่นขึ้น' },
  'Time between positions (s)': { th: 'เวลาเลื่อนแต่ละตำแหน่ง (วินาที)', up: 'เลเซอร์กวาดช้าลง หนีทันง่ายขึ้น' },
  'Toxic Burst radius': { th: 'รัศมีระเบิด Toxic Burst', up: 'ระเบิดกว้างขึ้น โดนมอนมากขึ้น' },
  'Toxic Burst: Poisoned + fire, remaining poison damage ×': { th: 'Toxic Burst: Poisoned + ไฟ คูณดาเมจพิษที่เหลือ', up: 'Combo Toxic Burst แรงขึ้น' },
  'Tri-Breath damage base per element': { th: 'ดาเมจ Tri-Breath ต่อธาตุ (ค่าตั้งต้น)', up: 'Tri-Breath แรงขึ้น' },
  'Tri-Breath interval (s)': { th: 'พ่น Tri-Breath ทุกกี่วินาที', up: 'พ่นห่างขึ้น = ช่วยได้น้อยลง' },
  'Tri-Breath length': { th: 'ระยะพ่น Tri-Breath', up: 'พ่นไปได้ไกลขึ้น' },
  'Trigger range': { th: 'ระยะที่เริ่มยิง', up: 'ยิงใส่มอนที่อยู่ไกลขึ้นได้' },
  'Turrets': { th: 'จำนวนป้อม', up: 'ป้อมเยอะขึ้น ยากขึ้น' },
  'Ultimate cooldown (s)': { th: 'คูลดาวน์ท่าไม้ตายของ King (วินาที)', up: 'King ใช้ท่าไม้ตายห่างขึ้น ง่ายขึ้น' },
  'Ultimate cooldown × during overtime (ultimate also allowed in phase 1)': { th: 'คูณคูลดาวน์ท่าไม้ตายช่วงต่อเวลา (ใช้ได้ตั้งแต่เฟส 1)', up: 'ช่วงต่อเวลาใช้ท่าไม้ตายห่างขึ้น' },
  'Ultimate cooldown × in the darkened-heart phase': { th: 'คูณคูลดาวน์ท่าไม้ตายในเฟสมืด', up: 'Umbra ใช้ท่าไม้ตายห่างขึ้น' },
  'Ultimate warning time (s)': { th: 'เวลาเตือนก่อนท่าไม้ตาย (วินาที)', up: 'เตือนนานขึ้น หลบง่ายขึ้น' },
  'Umbra HP + per King that escaped': { th: 'HP Umbra เพิ่มต่อ King ที่หนีไป', up: 'ปล่อย King หนีแล้ว Umbra อึดขึ้นมาก' },
  'Umbra using a defeated King\'s ultimate: damage ×': { th: 'Umbra ใช้ท่าไม้ตายของ King: คูณดาเมจ', up: 'ท่าที่ขโมยมาเจ็บขึ้น' },
  'Umbra: darkened heart below this HP (the screen goes dark)': { th: 'Umbra เข้าเฟสมืด (จอมืด) เมื่อ HP ต่ำกว่านี้', up: 'เข้าเฟสมืดเร็วขึ้น (ตั้งแต่ HP ยังเยอะ)' },
  'Umbra: stolen King ultimates below this HP': { th: 'Umbra ใช้ท่าไม้ตายที่ขโมยมาเมื่อ HP ต่ำกว่านี้', up: 'เข้าเฟสนี้เร็วขึ้น (ตั้งแต่ HP ยังเยอะ)' },
  'Unlock price': { th: 'ราคาปลดล็อก (Gold)', up: 'ปลดล็อกตัวละครนี้แพงขึ้น' },
  'Upper limit': { th: 'เพดานสูงสุด', up: 'ค่าขึ้นไปได้สูงขึ้นก่อนตัน' },
  'Value at level offset': { th: 'ค่าตั้งต้น (ที่เลเวลเริ่มนับ)', up: 'ได้จำนวนมากขึ้นทุกเลเวล' },
  'Value before levels': { th: 'ค่าตั้งต้น (เลเวล 0)', up: 'ค่าเริ่มต้นสูงขึ้นทุกเลเวล' },
  'Visible enemies needed': { th: 'ต้องเห็นมอนบนจออย่างน้อยกี่ตัวถึงใช้', up: 'ใช้สกิลนี้น้อยลง (รอให้มอนเยอะก่อน)' },
  'Vitality max level': { th: 'Vitality เลเวลสูงสุด', up: 'อัป Vitality ได้มากเลเวลขึ้น' },
  'Vitality: instant heal on pick': { th: 'Vitality: ฮีลทันทีตอนเลือก', up: 'เลือกแล้วฮีลมากขึ้น' },
  'Vitality: max HP per level': { th: 'Vitality: HP สูงสุดเพิ่มต่อเลเวล', up: 'อัปแล้วอึดขึ้นมากขึ้น' },
  'Volley interval (s)': { th: 'ยิงลูกศรแต่ละชุดทุกกี่วินาที', up: 'ยิงห่างขึ้น = ดาเมจรวมน้อยลง' },
  'Warning (s)': { th: 'เวลาเตือนก่อนโจมตี (วินาที)', up: 'เตือนนานขึ้น = ท่าออกช้าลง หลบง่ายขึ้น' },
  'Warning length': { th: 'ความยาวเส้นเตือน', up: 'ท่ายาวขึ้น หลบยากขึ้น' },
  'Warning line length': { th: 'ความยาวเส้นเตือน', up: 'ท่ายาวขึ้น หลบยากขึ้น' },
  'Wave damage ×': { th: 'ดาเมจคลื่น (คูณ)', up: 'โดนคลื่นแล้วเจ็บขึ้น' },
  'Wave radius': { th: 'รัศมีคลื่น', up: 'คลื่นกว้างขึ้น หนียากขึ้น' },
  'Wave time (s)': { th: 'เวลาคลื่น (วินาที)', up: 'คลื่นช้าลง/นานขึ้น' },
  'Wave travel time (s)': { th: 'เวลาที่คลื่นวิ่งออกไป (วินาที)', up: 'คลื่นวิ่งช้าลง หลบง่ายขึ้น' },
  'Waves': { th: 'จำนวนระลอก', up: 'ระลอกเยอะขึ้น ท่ายาวขึ้น' },
  'Weight × for upgrading the Signature Skill': { th: 'คูณน้ำหนักการ์ดอัป Signature Skill', up: 'การ์ดอัป Signature Skill โผล่บ่อยขึ้น' },
  'Weight: new skill': { th: 'น้ำหนัก: สกิลใหม่', up: 'การ์ดสกิลใหม่โผล่บ่อยขึ้น' },
  'Weight: passive': { th: 'น้ำหนัก: Passive', up: 'การ์ด Passive โผล่บ่อยขึ้น' },
  'Weight: upgrade an owned skill': { th: 'น้ำหนัก: อัปสกิลที่มีอยู่', up: 'การ์ดอัปสกิลเดิมโผล่บ่อยขึ้น' },
  'Whelps per summon': { th: 'จำนวนลูกมังกรต่อการเรียก', up: 'ลูกมังกรเยอะขึ้น ยากขึ้น' },
  'XP': { th: 'EXP ที่ดรอป', up: 'ฆ่าแล้วได้ EXP มากขึ้น เลเวลอัปเร็วขึ้น' },
  'XP gems a boss drops': { th: 'จำนวนคริสตัล EXP ที่บอสดรอป', up: 'ฆ่าบอสได้ EXP มากขึ้น' },
  'XP gems a dragon/rival drops': { th: 'จำนวนคริสตัล EXP ที่มังกร/Rival ดรอป', up: 'ฆ่ามังกร/Rival ได้ EXP มากขึ้น' },
  'XP per level': { th: 'EXP เพิ่มต่อเลเวล', up: 'อัป Wisdom แล้วได้ EXP มากขึ้น' },
  'XP to level: constant': { th: 'EXP ที่ต้องใช้อัปเลเวล: ค่าคงที่', up: 'ทุกเลเวลอัปช้าลง' },
  'XP to level: × level': { th: 'EXP ที่ต้องใช้อัปเลเวล: × เลเวล', up: 'ยิ่งเลเวลสูงยิ่งอัปช้าลง' },
  'XP to level: × level²': { th: 'EXP ที่ต้องใช้อัปเลเวล: × เลเวล²', up: 'เลเวลสูงอัปช้าลงมาก' },
  'Zoom moment length (s)': { th: 'ช่วงซูมกล้องนาน (วินาที)', up: 'ซูมค้างนานขึ้น' },
  'Share of monsters that come from the wave front instead of anywhere around (0 = all around)': { th: 'สัดส่วนมอนที่มาจากทิศคลื่นหลัก (0 = มารอบตัวแบบเดิม)', up: 'มอนมาทางเดียวกันมากขึ้น มีทางหนีชัดขึ้น' },
  'Wave front width (degrees)': { th: 'ความกว้างของคลื่นหลัก (องศา)', up: 'คลื่นแผ่กว้างขึ้น ทางหนีแคบลง' },
  'Seconds before the wave front moves to another side': { th: 'คลื่นหลักเปลี่ยนทิศทุกกี่วินาที', up: 'คลื่นอยู่ทิศเดิมนานขึ้น เปลี่ยนทิศน้อยลง' },
  'The next wave front turns at least this many degrees': { th: 'คลื่นถัดไปหมุนไปอย่างน้อยกี่องศา', up: 'คลื่นใหม่มาจากอีกฝั่งชัดขึ้น (180 = ฝั่งตรงข้าม)' },
  'Quiet seconds each time the wave front moves (0 = none)': { th: 'ช่วงพักหายใจตอนคลื่นเปลี่ยนทิศ (วินาที, 0 = ไม่มี)', up: 'พักนานขึ้น มีเวลาเก็บ EXP' },
  'Spawn rate × during the quiet seconds': { th: 'อัตราเกิดมอนช่วงพักหายใจ (× ปกติ)', up: 'ช่วงพักมีมอนมากขึ้น พักน้อยลง' },
  'Monsters left far behind reappear on the wave front (1) or anywhere around (0)': { th: 'มอนที่ตามไม่ทันวาร์ปไปฝั่งคลื่น (1) หรือที่ไหนก็ได้ (0)', up: '1 = วิ่งหนีแล้วไม่โดนมอนเก่าดักข้างหน้า' },
  'Swarms on normal Stages come as two arcs from the wave front\'s sides (1) or a full ring (0)': { th: 'ฝูงล้อมมาเป็นก้ามปู 2 ฝั่ง (1) หรือวงแหวนเต็มรอบ (0)', up: '1 = ฝูงล้อมเหลือช่องหนีด้านหลัง (Blood Moon ยังเป็นวงเต็ม)' },
  'Width of each swarm arc (degrees)': { th: 'ความกว้างของก้ามปูแต่ละฝั่ง (องศา)', up: 'ก้ามปูกว้างขึ้น ช่องหนีแคบลง' },
  'A new Stage moves the Director this share of the way back to its starting value (0 = keeps it)': { th: 'เริ่มด่านใหม่ Director ถอยกลับไปหาค่าเริ่มต้นเท่านี้ (0 = คงเดิม)', up: 'ด่านใหม่เริ่มเบาลง ไม่แบกความกดดันจากด่านก่อน' },
};

/** Thai names for object / group descriptions. */
export const GROUP_TH: Record<string, string> = {
  'Anti-cheat tier 0 (server checks)': 'กันโกงขั้นพื้นฐาน (เซิร์ฟเวอร์ตรวจ)',
  'Arcade Score': 'คะแนน Arcade (Score)',
  'Armor crab': 'ปูเกราะ (Armor crab)',
  'Attack skills: level formulas and evolutions': 'สกิลโจมตี: สูตรตามเลเวลและ Evolution',
  'Aura radius': 'รัศมีออร่า',
  'Awakening': 'Awakening (ปลุกพลัง)',
  'Bash damage': 'ดาเมจกระแทกโล่',
  'Bat': 'ค้างคาว (Bat)',
  'Beam length': 'ความยาวลำแสง',
  'Bench and Stage-end swaps': 'Bench และการสลับสกิลตอนจบด่าน',
  'Blade lasts (s)': 'ใบมีดอยู่นาน (วินาที)',
  'Blades': 'จำนวนใบมีด',
  'Blast radius': 'รัศมีระเบิด',
  'Blood Moon Guardians': 'Guardian ใน Blood Moon',
  'Bog Queen': 'Bog Queen',
  'Bog Queen ultimate: Gossip Swamp': 'ท่าไม้ตาย Bog Queen: Gossip Swamp',
  'Bog Queen: call poison frogs': 'Bog Queen: เรียกกบพิษ',
  'Bog Queen: poison spit cone': 'Bog Queen: พ่นพิษเป็นกรวย',
  'Bolts per cast': 'จำนวนกระสุนต่อครั้ง',
  'Bone King': 'Bone King',
  'Bone King ultimate: Lonely Crypt': 'ท่าไม้ตาย Bone King: Lonely Crypt',
  'Bone King: bone fan': 'Bone King: ปากระดูกเป็นพัด',
  'Bone King: raise skeletons around the player': 'Bone King: ปลุกโครงกระดูกรอบผู้เล่น',
  'Bram': 'Bram (อัศวิน)',
  'Bram line (survival): Aegis Dome': 'สาย Bram (เอาตัวรอด): Aegis Dome',
  'Bram line: Judgement Pillar': 'สาย Bram: Judgement Pillar',
  'Bram line: Sacred Blades': 'สาย Bram: Sacred Blades',
  'Bram: Holy Shield': 'Bram: Holy Shield (สกิลประจำตัว)',
  'Chain jumps': 'จำนวนครั้งที่สายฟ้ากระโดด',
  'Chance a monster dying inside becomes a big EXP crystal': 'โอกาสที่มอนตายในวงกลายเป็นคริสตัล EXP ใหญ่',
  'Changes applied when the skill evolves': 'สิ่งที่เปลี่ยนเมื่อสกิล Evolution',
  'Clockwork soldier': 'ทหารไขลาน (Clockwork soldier)',
  'Cloud wisp': 'ภูตเมฆ (Cloud wisp)',
  'Co-op': 'เล่นร่วมกัน (Co-op)',
  'Collapse damage': 'ดาเมจตอนหลุมดำยุบ',
  'Combos': 'Combo ธาตุ',
  'Companion: Frost': 'คู่หู: Frost',
  'Companion: Inferno (breath; dive bomb from level 3)': 'คู่หู: Inferno (พ่นไฟ; โฉบทิ้งระเบิดตั้งแต่เลเวล 3)',
  'Companion: Storm': 'คู่หู: Storm',
  'Companions': 'คู่หู (Companion)',
  'Cooldown (s)': 'คูลดาวน์ (วินาที)',
  'Cyclones per cast': 'จำนวนพายุต่อครั้ง',
  'Damage': 'ดาเมจ',
  'Damage per puff': 'ดาเมจต่อการพ่นควัน',
  'Damage per star': 'ดาเมจต่อดาว',
  'Damage per tick': 'ดาเมจต่อครั้ง (tick)',
  'Damage per volley': 'ดาเมจต่อชุดลูกศร',
  'Director (adaptive pressure)': 'Director (ปรับความยากอัตโนมัติ)',
  'Discs per cast': 'จำนวนจานต่อครั้ง',
  'Dive damage': 'ดาเมจโฉบ',
  'Drops and pickups': 'ของดรอปและการเก็บของ',
  'Duration (s)': 'อยู่นาน (วินาที)',
  'EXP of that crystal': 'EXP ของคริสตัลนั้น',
  'Endless mode (after Umbra)': 'Endless (หลังชนะ Umbra)',
  'Enemies pierced': 'จำนวนมอนที่ทะลุได้',
  'Enemy scaling': 'ความเก่งของมอนตามด่าน',
  'Eye Caster': 'Eye Caster (มอนยิงไกล)',
  'Fire bat': 'ค้างคาวไฟ (Fire bat)',
  'First Run (easier Greenvale)': 'Run แรก (Greenvale แบบง่าย)',
  'Flying tome': 'หนังสือบิน (Flying tome)',
  'Frost Dragon': 'Frost Dragon',
  'Frost Dragon (Guardian)': 'Frost Dragon (Guardian)',
  'Frost King': 'Frost King',
  'Frost King ultimate: Absolute Throne': 'ท่าไม้ตาย Frost King: Absolute Throne',
  'Frost King: slippery ice floor': 'Frost King: พื้นน้ำแข็งลื่น',
  'Frost King: three ice spears': 'Frost King: หอกน้ำแข็งสามเล่ม',
  'Ghost': 'ผี (Ghost)',
  'Giant leech': 'ปลิงยักษ์ (Giant leech)',
  'Golem King': 'Golem King',
  'Golem King ultimate: PROTOCOL: PURGE': 'ท่าไม้ตาย Golem King: PROTOCOL: PURGE',
  'Golem King: deploy turrets': 'Golem King: วางป้อมปืน',
  'Golem King: straight laser': 'Golem King: เลเซอร์เส้นตรง',
  'Griffin chick': 'ลูกกริฟฟิน (Griffin chick)',
  'Haunted armor': 'ชุดเกราะผีสิง (Haunted armor)',
  'Heal × max HP': 'ฮีล (× HP สูงสุด)',
  'Heart Crack difficulty tiers (unlocked by beating Umbra)': 'ระดับความยาก Heart Crack (ปลดล็อกเมื่อชนะ Umbra)',
  'Heroes': 'Hero (ตัวละคร)',
  'Ice bat': 'ค้างคาวน้ำแข็ง (Ice bat)',
  'Ice slime': 'สไลม์น้ำแข็ง (Ice slime)',
  'In-Run economy': 'เศรษฐกิจใน Run',
  'Inferno Dragon': 'Inferno Dragon',
  'Inferno Dragon (Guardian)': 'Inferno Dragon (Guardian)',
  'Invulnerable (s)': 'อมตะ (วินาที)',
  'Iron spider': 'แมงมุมเหล็ก (Iron spider)',
  'Jellyfish': 'แมงกะพรุน (Jellyfish)',
  'Jumps': 'จำนวนครั้งที่สายฟ้ากระโดด',
  'Kill Streak': 'Kill Streak (ฆ่าต่อเนื่อง)',
  'King Slime': 'King Slime',
  'King Slime ultimate: Royal Splash': 'ท่าไม้ตาย King Slime: Royal Splash',
  'King Slime: leap slam': 'King Slime: กระโดดทุบ',
  'King Slime: split off slimes': 'King Slime: แตกสไลม์ออกมา',
  'King moves: two telegraphed moves, ultimate below phaseAt HP': 'ท่าของ King: ท่ามีเตือน 2 ท่า + ท่าไม้ตายเมื่อ HP ต่ำ',
  'Kit': 'Kit (นักธนู)',
  'Kit line (survival): Gale Step': 'สาย Kit (เอาตัวรอด): Gale Step',
  'Kit line: Arrow Rain': 'สาย Kit: Arrow Rain',
  'Kit line: Thunder Hawk': 'สาย Kit: Thunder Hawk',
  'Kit: Hawk Companion': 'Kit: Hawk Companion (สกิลประจำตัว)',
  'Lances per cast': 'จำนวนหอกต่อครั้ง',
  'Lantern ghost': 'ผีตะเกียง (Lantern ghost)',
  'Lasts (s)': 'อยู่นาน (วินาที)',
  'Lava rock': 'หินลาวา (Lava rock)',
  'Level curve': 'EXP ที่ต้องใช้อัปเลเวล',
  'Level-up offers': 'ตัวเลือกตอนเลเวลอัป',
  'Lich Queen': 'Lich Queen',
  'Lich Queen ultimate: Requiem': 'ท่าไม้ตาย Lich Queen: Requiem',
  'Lich Queen: soul spiral': 'Lich Queen: เกลียววิญญาณ',
  'Lich Queen: swap places with a monster': 'Lich Queen: สลับที่กับมอน',
  'Lyra': 'Lyra (จอมเวท)',
  'Lyra line (survival): Time Warp': 'สาย Lyra (เอาตัวรอด): Time Warp',
  'Lyra line: Mana Nova': 'สาย Lyra: Mana Nova',
  'Lyra line: Starfall': 'สาย Lyra: Starfall',
  'Lyra: Arcane Sigil': 'Lyra: Arcane Sigil (สกิลประจำตัว)',
  'Magma King': 'Magma King',
  'Magma King ultimate: ERUPTION!!': 'ท่าไม้ตาย Magma King: ERUPTION!!',
  'Magma King: ground-slam ring wave': 'Magma King: ทุบพื้นเป็นคลื่นวง',
  'Magma King: lava drops in a ring': 'Magma King: หยดลาวาเป็นวง',
  'Meteors per cast': 'จำนวนอุกกาบาตต่อครั้ง',
  'Mini slime': 'สไลม์จิ๋ว (Mini slime)',
  'Mummy': 'มัมมี่ (Mummy)',
  'Mushroom': 'เห็ด (Mushroom)',
  'Orbit radius': 'รัศมีวงโคจร',
  'Passive skills': 'Passive',
  'Permanent shop': 'ร้านค้าถาวร',
  'Player': 'ผู้เล่น',
  'Poison frog': 'กบพิษ (Poison frog)',
  'Poison frog hops': 'การกระโดดของกบพิษ',
  'Pools per cast': 'จำนวนบ่อพิษต่อครั้ง',
  'Presentation (client only; never changes the simulation)': 'การแสดงผล (ฝั่งเครื่องผู้เล่น; ไม่เปลี่ยนตัวเกม)',
  'Radius': 'รัศมี',
  'Radius (monsters inside are slowed like Frost Aura)': 'รัศมี (มอนในวงช้าลงเหมือน Frost Aura)',
  'Reach': 'ระยะฟัน',
  'Realm traits and resistances': 'ลักษณะ Realm และการต้านทานธาตุ',
  'Rival bolt': 'Rival: กระสุนเวท',
  'Rival lance': 'Rival: หอก',
  'Rival lightning': 'Rival: ฟ้าผ่า',
  'Rival meteor': 'Rival: อุกกาบาต',
  'Rival nova': 'Rival: วงระเบิด',
  'Salamander': 'ซาลาแมนเดอร์ (Salamander)',
  'Sand King': 'Sand King',
  'Sand King ultimate: Quicksand Vault': 'ท่าไม้ตาย Sand King: Quicksand Vault',
  'Sand King: burrow and burst out under the player': 'Sand King: มุดดินแล้วโผล่ใต้ผู้เล่น',
  'Sand King: sandstorm line': 'Sand King: พายุทรายเส้นตรง',
  'Sand slime': 'สไลม์ทราย (Sand slime)',
  'Sawfish': 'ปลาฉนาก (Sawfish)',
  'Scorpion': 'แมงป่อง (Scorpion)',
  'Second Wind revive': 'ฟื้นคืนชีพ Second Wind',
  'Seconds taken off every Skill cooldown': 'ลดคูลดาวน์ทุกสกิล (วินาที)',
  'Shadow Clone': 'Shadow Clone (ร่างเงา)',
  'Shadow Rival': 'Shadow Rival (คู่ปรับเงา)',
  'Shields': 'จำนวนโล่',
  'Skeleton': 'โครงกระดูก (Skeleton)',
  'Skeleton Archer': 'โครงกระดูกนักธนู (Skeleton Archer)',
  'Slime': 'สไลม์ (Slime)',
  'Snowman': 'มนุษย์หิมะ (Snowman)',
  'Spawner': 'การเกิดมอนสเตอร์',
  'Special events': 'อีเวนต์พิเศษ',
  'Spin speed (rad/s)': 'ความเร็วหมุน (เรเดียน/วินาที)',
  'Splash damage': 'ดาเมจกระจาย',
  'Splash radius': 'รัศมีกระจาย',
  'Split Slime': 'Split Slime (สไลม์แตกตัว)',
  'Spore cap': 'เห็ดสปอร์ (Spore cap)',
  'Sporelet': 'สปอร์จิ๋ว (Sporelet)',
  'Stage flow': 'ลำดับและเวลาในด่าน',
  'Stars': 'จำนวนดาว',
  'Statuses left by Skills': 'Status ที่สกิลทิ้งไว้บนมอน',
  'Storm Dragon': 'Storm Dragon',
  'Storm Dragon (Guardian)': 'Storm Dragon (Guardian)',
  'Storm King': 'Storm King',
  'Storm King ultimate: Look, I Can Fly!': 'ท่าไม้ตาย Storm King: Look, I Can Fly!',
  'Storm King: lightning on your footsteps': 'Storm King: ฟ้าผ่าตามรอยเท้า',
  'Storm King: straight swoop': 'Storm King: โฉบเป็นเส้นตรง',
  'Storm bird': 'นกพายุ (Storm bird)',
  'Three-headed Dragon': 'มังกรสามหัว (Three-headed Dragon)',
  'Throw distance': 'ระยะขว้าง',
  'Tide Queen': 'Tide Queen',
  'Tide Queen ultimate: Siren Song': 'ท่าไม้ตาย Tide Queen: Siren Song',
  'Tide Queen: pushing wave cone': 'Tide Queen: คลื่นผลักเป็นกรวย',
  'Tide Queen: slow bubbles': 'Tide Queen: ฟองลอยช้า',
  'Treasure chest wheel': 'วงล้อหีบสมบัติ',
  'Turn speed': 'ความเร็วหมุน',
  'Turret': 'ป้อมปืน (Turret)',
  'Ultimate (Judgement)': 'Ultimate (Judgement)',
  'Umbra (placeholder)': 'Umbra (ค่าชั่วคราว)',
  'Umbra, the final King': 'Umbra บอสสุดท้าย',
  'Vex': 'Vex (นักเล่นแร่แปรธาตุ)',
  'Vex line (survival): Elixir Rain': 'สาย Vex (เอาตัวรอด): Elixir Rain',
  'Vex line: Cauldron': 'สาย Vex: Cauldron',
  'Vex line: Transmute (EXP, never Gold)': 'สาย Vex: Transmute (ได้ EXP ไม่ใช่ Gold)',
  'Vex: Volatile Flask': 'Vex: Volatile Flask (สกิลประจำตัว)',
  'Wave radius': 'รัศมีคลื่น',
  'Weapons (change only the Ultimate)': 'Weapon (เปลี่ยนแค่รูปแบบ Ultimate)',
  'Whelp': 'ลูกมังกร (Whelp)',
  'Wild Boar': 'Wild Boar (หมูป่าพุ่งชน)',
  'World Lumora': 'World Lumora',
  'Difficulty presets (solo; Balanced = this config as is)': 'Preset ความยาก (เล่นเดี่ยว; สมดุล = config นี้ตามเดิม)',
  'Preset: Relaxed': 'Preset: เพลินๆ',
  'Preset: Easy': 'Preset: ง่าย',
  'Preset: Challenge': 'Preset: ท้าทาย',
  'Preset: Hard': 'Preset: ยาก',
  'Preset: Blitz': 'Preset: เทพไว',
};
