// Website-only text (Thai / English). Game names and descriptions (skills, heroes, Realms…)
// come from packages/i18n through `g()` so the site always matches the game.
// Keep it simple: short sentences, everyday words, one idea per line.

type Pair = { th: string; en: string };

export const TXT = {
  // ── shell ──────────────────────────────────────────────
  'nav.home': { th: 'หน้าแรก', en: 'Home' },
  'nav.guide': { th: 'วิธีเล่น', en: 'How to Play' },
  'nav.skills': { th: 'สกิล & คอมโบ', en: 'Skills & Combos' },
  'nav.world': { th: 'โลก Lumora', en: 'World' },
  'nav.updates': { th: 'อัปเดต', en: 'Updates' },
  'nav.play': { th: 'เล่นเลย', en: 'PLAY' },
  'nav.menu': { th: 'เมนู', en: 'Menu' },
  'nav.lang': { th: 'EN', en: 'ไทย' },
  'nav.langAria': { th: 'Switch to English', en: 'เปลี่ยนเป็นภาษาไทย' },
  'foot.tag': { th: 'เกมเอาตัวรอดแนวพิกเซล เล่นฟรีบนเว็บ', en: 'A free pixel-art survival game for the web' },
  'foot.play': { th: 'เล่นเกม', en: 'Play the game' },
  'foot.privacy': { th: 'นโยบายความเป็นส่วนตัว', en: 'Privacy' },
  'foot.source': { th: 'ซอร์สโค้ด (GitHub)', en: 'Source code (GitHub)' },
  'foot.data': { th: 'ตัวเลขในเว็บนี้ดึงจากโค้ดเกมจริง อาจปรับตามการบาลานซ์', en: 'Numbers on this site come straight from the game code and may change with balance updates.' },

  // ── home ───────────────────────────────────────────────
  'home.title': { th: 'Pixel Horde — เกมเอาตัวรอดแนวพิกเซล เล่นฟรีบนเว็บ', en: 'Pixel Horde — a free pixel-art survival game' },
  'home.lead': {
    th: 'มอนสเตอร์บุกมาเป็นฝูง สกิลของคุณยิงเองอัตโนมัติ<br>คุณแค่ <b>เดินหลบ</b> เก็บคริสตัล แล้ว <b>เลือกพลังใหม่</b> ให้แรงขึ้นเรื่อย ๆ',
    en: 'Monsters swarm in hordes. Your skills fire on their own —<br>you just <b>move</b>, grab crystals and <b>pick new powers</b>.',
  },
  'home.cta': { th: 'เล่นฟรีเลย', en: 'PLAY FREE' },
  'home.cta2': { th: 'ดูวิธีเล่น', en: 'How to play' },
  'home.b1': { th: 'ฟรี 100%', en: '100% free' },
  'home.b2': { th: 'ไม่ต้องติดตั้ง', en: 'No install' },
  'home.b3': { th: 'คอม & มือถือ', en: 'PC & phone' },
  'home.b4': { th: 'เล่นกับเพื่อน 4 คน', en: 'Co-op up to 4' },
  'home.b5': { th: 'ไทย / English', en: 'Thai / English' },
  'home.scroll': { th: 'เลื่อนลง', en: 'Scroll' },

  'home.how.h': { th: 'เล่นง่ายใน 3 ขั้น', en: 'Easy as 1-2-3' },
  'home.how.1h': { th: 'เดิน', en: 'Move' },
  'home.how.1p': { th: 'ใช้ WASD / ลูกศร หรือแตะลากบนมือถือ ไม่มีปุ่มโจมตีให้กด!', en: 'WASD / arrow keys, or touch and drag on a phone. There is no attack button!' },
  'home.how.2h': { th: 'สกิลยิงเอง', en: 'Skills fire by themselves' },
  'home.how.2p': { th: 'ลูกไฟ สายฟ้า ดาบบิน… ทุกสกิลทำงานเองอัตโนมัติ หน้าที่คุณคือหลบให้รอด', en: 'Fireballs, lightning, flying blades… everything auto-fires. Your job is to stay alive.' },
  'home.how.3h': { th: 'เลเวลอัป & เลือก', en: 'Level up & pick' },
  'home.how.3p': { th: 'เก็บคริสตัล EXP สีฟ้า พอเลเวลอัปก็เลือก 1 ใน 3 พลัง แล้วสร้างสายของคุณเอง', en: 'Collect blue EXP crystals. Each level-up, pick 1 of 3 powers and build your own style.' },

  'home.shots.h': { th: 'ภาพจากเกมจริง', en: 'Straight from the game' },
  'home.shots.p': { th: 'ภาพทั้งหมดจับจากเกมจริง ไม่ได้ตกแต่ง', en: 'Every picture is a real, unedited capture from the game.' },
  'shot.title': { th: 'หน้าเริ่มเกม', en: 'Title screen' },
  'shot.play': { th: 'ฝูงมอนรุมเข้ามา', en: 'The horde closes in' },
  'shot.level': { th: 'เลเวลอัป: เลือก 1 ใน 3', en: 'Level up: pick 1 of 3' },
  'shot.king': { th: 'ราชามาแล้ว! ดูพื้นที่เตือนสีแดง', en: 'The King arrives — watch the red warnings' },
  'shot.moon': { th: 'Blood Moon: มอน ×2.3 เหรียญ ×2', en: 'Blood Moon: ×2.3 monsters, ×2 Gold' },
  'shot.realm': { th: 'ดินแดนใหม่ มอนใหม่ ราชาใหม่', en: 'New Realms, new monsters, new Kings' },
  'shot.hero': { th: 'เลือกฮีโร่และอาวุธ', en: 'Pick your Hero and Weapon' },
  'shot.dragon': { th: 'มังกรผู้พิทักษ์', en: 'A Guardian dragon' },

  'home.heroes.h': { th: 'ฮีโร่ 4 คน 4 สไตล์', en: '4 Heroes, 4 play styles' },
  'home.heroes.p': { th: 'แต่ละคนมีสกิลประจำตัวที่ติดตัวตลอด และตื่นพลังเป็นร่างใหม่ได้', en: 'Each Hero has a Signature Skill that never leaves, and can Awaken into a new form.' },
  'home.heroes.more': { th: 'ดูฮีโร่ทั้งหมด →', en: 'Meet the Heroes →' },
  'home.sig': { th: 'สกิลประจำตัว', en: 'Signature' },
  'home.free': { th: 'ฟรี', en: 'Free' },

  'home.feat.h': { th: 'มีอะไรให้เล่นบ้าง', en: 'What is inside' },
  'home.f.combo.h': { th: 'คอมโบธาตุ', en: 'Element Combos' },
  'home.f.combo.p': { th: 'แช่แข็งแล้วทุบให้แตก! สกิลต่างธาตุโดนมอนตัวเดียวกันจะระเบิดเพิ่ม 7 แบบ', en: 'Freeze it, then smash it! Mix elements on one monster for 7 bonus reactions.' },
  'home.f.kings.h': { th: 'ราชา 10 องค์ + Umbra', en: '10 Kings + Umbra' },
  'home.f.kings.p': { th: 'ทุกดินแดนมีราชาพร้อมท่าไม้ตายและบทพูดกวน ๆ ปราบให้ทันก่อนมันหนี', en: 'Every Realm has a King with big moves and silly lines. Beat it before it escapes.' },
  'home.f.route.h': { th: 'เลือกเส้นทางเอง', en: 'Choose your route' },
  'home.f.route.p': { th: '8 Chapter ต่อรอบ เลือกดินแดนถัดไปเอง 1 ใน 2 ทุกครั้ง เล่นกี่รอบก็ไม่ซ้ำ', en: '8 Chapters per Run. Pick 1 of 2 Realms each time, so no two Runs are the same.' },
  'home.f.moon.h': { th: 'Blood Moon & มังกร', en: 'Blood Moon & dragons' },
  'home.f.moon.p': { th: 'คืนพระจันทร์เลือด มอนทะลัก แต่เงินคูณ 2 บางคืนมีมังกรผู้พิทักษ์ ปราบได้มาเป็นสัตว์คู่ใจ', en: 'On a Blood Moon, monsters flood in but Gold doubles. Some nights a Guardian dragon comes — beat it to tame it.' },
  'home.f.coop.h': { th: 'เล่นกับเพื่อน', en: 'Play with friends' },
  'home.f.coop.p': { th: 'สร้างห้อง ส่งลิงก์ให้เพื่อน เล่นด้วยกันได้สูงสุด 4 คน ของที่ดรอปแบ่งกันทั้งทีม', en: 'Make a room, send the link, play with up to 4. Drops are shared by the whole team.' },
  'home.f.weapon.h': { th: 'อาวุธ & ท่าไม้ตาย', en: 'Weapons & Ultimates' },
  'home.f.weapon.p': { th: 'สะสมอาวุธ 11 ชิ้น แต่ละชิ้นเปลี่ยนหน้าตาท่าไม้ตาย (กด SPACE)', en: 'Collect 11 Weapons. Each one changes how your Ultimate (SPACE) looks and works.' },
  'home.f.board.h': { th: 'อันดับ & Season', en: 'Leaderboards & Seasons' },
  'home.f.board.p': { th: 'ทำคะแนนขึ้นกระดานอันดับ ปลดล็อกความสำเร็จ ฉายา และเหรียญตรา', en: 'Climb the board, unlock achievements, Titles and badges.' },
  'home.f.save.h': { th: 'เล่นออฟไลน์ได้', en: 'Plays offline too' },
  'home.f.save.p': { th: 'เล่นคนเดียวได้แม้ไม่มีเน็ต ผูก Google ไว้เพื่อเก็บเซฟข้ามเครื่อง', en: 'Solo works without internet. Link Google to keep your save on every device.' },

  'home.realms.h': { th: '11 ดินแดนของ Lumora', en: 'The 11 Realms of Lumora' },
  'home.realms.p': { th: 'หัวใจแห่ง Lumora แตกเป็นเสี่ยง ๆ เศษของมันทำให้ราชาทุกดินแดนคลั่ง ออกเดินทางไปเอาคืนมา!', en: 'The Heart of Lumora has shattered. Its shards drove every Realm\'s King mad. Go and take them back!' },
  'home.realms.more': { th: 'สำรวจโลก Lumora →', en: 'Explore Lumora →' },

  'home.end.h': { th: 'พร้อมรับมือฝูงมอนหรือยัง?', en: 'Ready for the horde?' },
  'home.end.p': { th: 'กดปุ่มเดียว เล่นได้ทันทีบนเบราว์เซอร์', en: 'One click and you are in — right in your browser.' },

  // ── guide ──────────────────────────────────────────────
  'guide.title': { th: 'วิธีเล่น — Pixel Horde', en: 'How to Play — Pixel Horde' },
  'guide.h': { th: 'วิธีเล่นแบบเข้าใจง่าย', en: 'How to play, the easy way' },
  'guide.p': { th: 'อ่าน 5 นาทีเข้าใจทั้งเกม ทุกหัวข้อมีภาพ และหลายอันกดเล่นได้', en: 'Everything in five minutes. Every part has pictures, and many you can click and try.' },
  'guide.toc': { th: 'สารบัญ', en: 'Contents' },
  'guide.try': { th: 'ลองกด', en: 'Try it' },

  'g.controls.h': { th: 'ปุ่มควบคุม', en: 'Controls' },
  'g.controls.p': { th: 'เกมนี้ <b>ไม่มีปุ่มโจมตี</b> สกิลยิงเองทั้งหมด คุณแค่เดินหลบและเก็บของ', en: 'There is <b>no attack button</b>. Skills fire on their own; you move and collect.' },
  'g.k.move': { th: 'เดิน', en: 'Move' },
  'g.k.ult': { th: 'ท่าไม้ตาย (เมื่อเกจเต็ม)', en: 'Ultimate (when full)' },
  'g.k.pause': { th: 'พักเกม', en: 'Pause' },
  'g.k.mute': { th: 'ปิดเสียง', en: 'Mute' },
  'g.k.phone': { th: 'มือถือ: แตะค้างแล้วลากไปทางที่จะเดิน ปุ่ม ULT อยู่มุมขวาล่าง', en: 'Phone: touch, hold and drag where you want to go. The ULT button sits bottom-right.' },
  'g.k.demo': { th: 'ลองกดปุ่มลูกศร / WASD ตรงนี้ (หรือลากในกรอบ)', en: 'Try WASD / arrows here (or drag inside the box)' },

  'g.goal.h': { th: 'เป้าหมายของหนึ่งรอบ (Run)', en: 'The goal of a Run' },
  'g.goal.p': { th: 'หนึ่งรอบมี <b>8 Chapter</b> เริ่มที่ Greenvale จบที่ Heart Crater ระหว่างทางเลือกดินแดนเอง 1 ใน 2 ทุก Chapter ผ่าน Chapter ได้เมื่อ <b>ปราบราชา</b> ของดินแดนนั้น', en: 'A Run has <b>8 Chapters</b>: start in Greenvale, end at the Heart Crater. In between you pick 1 of 2 Realms each time. A Chapter is cleared when its <b>King is defeated</b>.' },
  'g.goal.note': { th: 'ความยากขึ้นกับ <b>เลข Chapter</b> ไม่ใช่ดินแดน ดินแดนแค่เปลี่ยนชนิดมอน ลักษณะเด่น และธาตุที่มอนทน', en: 'Difficulty follows the <b>Chapter number</b>, not the Realm. A Realm only changes the monsters, their traits and the element they resist.' },
  'g.goal.click': { th: 'กดที่ดินแดนเพื่อดูว่าเจออะไรบ้าง', en: 'Click a Realm to see what lives there' },
  'g.goal.end': { th: 'ชนะ Umbra = ช่วย Lumora สำเร็จ! แล้วเล่นต่อโหมด Endless ได้', en: 'Beat Umbra and Lumora is saved! Then keep going in Endless Mode.' },
  'g.goal.pick': { th: 'เลือก 1 ใน 2', en: 'pick 1 of 2' },
  'g.goal.lost': { th: 'ตายเมื่อไหร่ รอบนั้นจบ ของทุกอย่างในรอบหายหมด <b>ยกเว้น Gold</b> ที่เอาไปอัปเกรดถาวรได้', en: 'If you fall, the Run ends. Everything from that Run is lost <b>except Gold</b>, which buys permanent upgrades.' },

  'g.stage.h': { th: 'ในหนึ่งด่านเกิดอะไรบ้าง', en: 'What happens in a Stage' },
  'g.stage.p': { th: 'แต่ละ Chapter คือด่านจับเวลา 1 ด่าน มอนจะเยอะขึ้นเรื่อย ๆ ตามเวลา ลากแถบเพื่อดูแต่ละช่วง', en: 'Each Chapter is one timed Stage. Monsters keep growing in number. Drag the slider to see each moment.' },
  'g.stage.ch': { th: 'Chapter', en: 'Chapter' },
  'g.stage.len': { th: 'ด่านนี้ยาว {s} วินาที', en: 'This Stage lasts {s} s' },
  'g.stage.t0': { th: '<b>เริ่มด่าน</b> มอนยังน้อย เก็บคริสตัลและเลเวลอัปให้ไว', en: '<b>Start.</b> Few monsters yet. Grab crystals and level up fast.' },
  'g.stage.t1': { th: '<b>ฝูงเริ่มหนา</b> ทุก ๆ 18 วินาทีจะมีมอนล้อมเป็นวงกลม หาช่องหนีไว้', en: '<b>The horde thickens.</b> Every 18 s monsters appear in a ring around you — find the gap.' },
  'g.stage.t2': { th: '<b>ราชามาแล้ว!</b> (ที่ 55% ของเวลา) มีลูกศรขอบจอชี้ทาง ดูพื้นที่สีแดงก่อนมันโจมตี', en: '<b>The King arrives!</b> (at 55% of the time). An arrow at the screen edge points to it. Red areas show where it will hit.' },
  'g.stage.t3': { th: '<b>ราชาเหลือครึ่งเลือด</b> ปลดท่าไม้ตาย มีป้ายเตือนประมาณ 1 วินาทีก่อนโดน', en: '<b>King at half HP:</b> its ultimate move unlocks, with about 1 second of warning.' },
  'g.stage.t4': { th: '<b>หมดเวลาแต่ราชายังไม่ตาย = ต่อเวลา 45 วิ</b> ราชาโกรธ วิ่งเร็วขึ้น มอนทะลัก', en: '<b>Time is up but the King lives = 45 s of overtime.</b> The King is angry and faster; monsters pour in.' },
  'g.stage.t5': { th: '<b>ยังไม่ตายอีก = ราชาหนี!</b> ไม่ได้รางวัลราชา บอสสุดท้าย Umbra แข็งขึ้น แต่คุณเลือกดินแดนอื่นแทนใน Chapter เดิมได้ 1 ครั้ง', en: '<b>Still alive = the King escapes!</b> No King rewards, and the final boss Umbra grows stronger — but you may try another Realm for the same Chapter once.' },
  'g.stage.win': { th: 'ปราบราชาได้ = ผ่านด่าน! ได้หีบสมบัติ + Skill Point และฟื้น HP 40% ตอนเริ่มด่านถัดไป', en: 'King defeated = Stage clear! You get a chest, a Skill Point and 40% HP back before the next Stage.' },

  'g.exp.h': { th: 'คริสตัล EXP และเลเวลอัป', en: 'EXP crystals and levelling up' },
  'g.exp.p': { th: 'มอนตายแล้วทิ้ง <b>คริสตัล EXP</b> (เศษของหัวใจแห่ง Lumora) เดินไปเก็บ พอหลอดเต็มก็เลเวลอัป เกมหยุดให้คุณเลือก 1 ใน 3', en: 'Beaten monsters drop <b>EXP crystals</b> (shards of the Heart of Lumora). Walk over them; when the bar is full you level up and the game pauses so you can pick 1 of 3.' },
  'g.exp.new': { th: 'สกิลใหม่', en: 'New skill' },
  'g.exp.newp': { th: 'ได้การโจมตีใหม่', en: 'a new attack' },
  'g.exp.up': { th: 'อัปสกิลเดิม', en: 'Upgrade a skill' },
  'g.exp.upp': { th: 'แรงขึ้น เยอะขึ้น', en: 'stronger, more of it' },
  'g.exp.pas': { th: 'พาสซีฟ', en: 'Passive' },
  'g.exp.pasp': { th: 'ค่าสถานะเพิ่ม เช่น เร็วขึ้น HP เพิ่ม', en: 'stat boost like speed or HP' },
  'g.exp.try': { th: 'ลองเลือกการ์ดดูสิ', en: 'Pick a card' },
  'g.exp.picked': { th: 'เลือก {name}! ในเกมจริงตัวเลือกสุ่มใหม่ทุกครั้ง', en: 'You picked {name}! In the game the choices are random every time.' },
  'g.exp.curve': { th: 'EXP ที่ต้องใช้แต่ละเลเวล', en: 'EXP needed per level' },
  'g.exp.drops': { th: 'ของที่ดรอป', en: 'Things you pick up' },
  'g.drop.gem': { th: 'คริสตัล EXP', en: 'EXP crystal' },
  'g.drop.coin': { th: 'Gold', en: 'Gold' },
  'g.drop.heart': { th: 'หัวใจ ฟื้น HP', en: 'Heart: heals' },
  'g.drop.shield': { th: 'โล่ กันดาเมจครั้งถัดไป', en: 'Shield: blocks the next hits' },
  'g.drop.chest': { th: 'หีบสมบัติ', en: 'Treasure chest' },

  'g.slots.h': { th: 'ช่องสกิล: ถือได้เท่าไหร่', en: 'Skill slots: what you can carry' },
  'g.slots.p': { th: 'ถือ <b>สกิลโจมตี 4 ช่อง</b> (ช่องแรกล็อกเป็นสกิลประจำตัวฮีโร่) <b>พาสซีฟ 3 ช่อง</b> และ <b>Bench</b> ไว้เก็บสกิลสำรอง', en: 'You hold <b>4 attack slots</b> (the first is locked to your Hero\'s Signature Skill), <b>3 passive slots</b>, and a <b>Bench</b> for spare skills.' },
  'g.slots.atk': { th: 'ช่องโจมตี', en: 'Attack slots' },
  'g.slots.pas': { th: 'ช่องพาสซีฟ', en: 'Passive slots' },
  'g.slots.bench': { th: 'Bench', en: 'Bench' },
  'g.slots.lock': { th: 'ล็อก', en: 'locked' },
  'g.slots.benchp': { th: 'สกิลใน Bench ไม่ยิง และจะถูกเสนอให้ฝึก (+1 เลเวล) ก็ต่อเมื่อไม่มีอย่างอื่นให้อัปแล้ว ตอนจบด่านสลับเข้าช่องโจมตีได้ (จ่าย Gold) หรือลบทิ้งฟรี พอช่องพาสซีฟเต็ม พาสซีฟใหม่ก็มาพักใน Bench แล้วสลับกับช่องพาสซีฟได้เหมือนกัน Bench เริ่มที่ 1 ช่อง และ +1 หลังผ่าน Chapter 2 และ 4', en: 'Bench skills do not fire; they are offered for training (+1 level) only once nothing else is left to upgrade. At a Stage end you can swap one into an attack slot (costs Gold) or remove it for free. Once the passive slots are full, new passives wait on the Bench too and swap into a passive slot the same way. The Bench starts with 1 slot, +1 after Chapters 2 and 4.' },

  'g.evo.h': { th: 'วิวัฒน์ (Evolution)', en: 'Evolution' },
  'g.evo.p': { th: 'อัปสกิลจน <b>เต็มเลเวล</b> + มี <b>พาสซีฟคู่ของมัน</b> อย่างน้อย 1 เลเวล → ตอนเลเวลอัปจะมีการ์ด <b>EVOLVE!</b> ให้เลือก สกิลกลายร่างเป็นเวอร์ชันแรงกว่ามาก', en: 'Max out a skill + own <b>its paired passive</b> (any level) → an <b>EVOLVE!</b> card shows up on level-up. The skill turns into a much stronger form.' },
  'g.evo.more': { th: 'ดูคู่วิวัฒน์ทั้งหมด →', en: 'See every evolution →' },

  'g.combo.h': { th: 'คอมโบธาตุ', en: 'Element Combos' },
  'g.combo.p': { th: 'บางสกิล <b>ทิ้งสถานะ</b> ไว้บนมอน (แข็ง, ไหม้, ช็อต, ติดพิษ, ถูกดูดรวม) ถ้าสกิลอีกอันมาโดนมอนตัวนั้น จะเกิด <b>คอมโบ</b> ดาเมจเพิ่มหรือระเบิดใส่ตัวรอบ ๆ เกิดเองอัตโนมัติ', en: 'Some skills <b>leave a Status</b> on monsters (Frozen, Burning, Shocked, Poisoned, Gathered). When another skill hits that monster, a <b>Combo</b> fires — bonus damage or a blast. It all happens automatically.' },
  'g.combo.ex': { th: 'ตัวอย่าง: Frost Aura ทำให้แข็ง → Meteor ตีแรงลงไป → <b>SHATTER!</b> ดาเมจ ×{x} และเศษน้ำแข็งกระเด็นโดนตัวข้าง ๆ', en: 'Example: Frost Aura freezes → Meteor lands a heavy hit → <b>SHATTER!</b> ×{x} damage, and ice shards hit nearby monsters.' },
  'g.combo.more': { th: 'เปิดห้องทดลองคอมโบ →', en: 'Open the Combo Lab →' },

  'g.ult.h': { th: 'ท่าไม้ตาย (Ultimate) และอาวุธ', en: 'Ultimate and Weapons' },
  'g.ult.p': { th: 'เกจ ULT เติมเองตามเวลา (เต็มใน 60 วิ ฆ่ามอนช่วยให้เร็วขึ้นได้ถึง ~30 วิ) กด <b>SPACE</b> หรือปุ่ม ULT → กวาดมอนธรรมดาทั้งจอ แต่ใส่บอสได้แค่ส่วนหนึ่ง', en: 'The ULT gauge fills over time (60 s, or down to ~30 s with kills). Press <b>SPACE</b> or ULT to wipe ordinary monsters on screen; bosses only take a slice.' },
  'g.ult.w': { th: '<b>อาวุธ</b> ไม่เพิ่มค่าพลัง แต่ <b>เปลี่ยนร่างท่าไม้ตาย</b> เช่น แช่แข็ง รากไม้ตรึง หรือเก็บวิญญาณ ได้จากการชนะ Umbra หรือ (โอกาสน้อย) จากราชาของดินแดนนั้น เลือกก่อนเริ่มรอบ', en: 'A <b>Weapon</b> never adds stats — it <b>changes the form of your Ultimate</b>: freeze, root, reap and more. Win one by beating Umbra, or (rarely) from that Realm\'s King. Pick it before a Run.' },

  'g.chest.h': { th: 'หีบสมบัติ: วงล้อนำโชค', en: 'Treasure chest: the lucky wheel' },
  'g.chest.p': { th: 'ปราบราชาได้หีบ 1 ใบ เปิดแล้ววงล้อหมุน ได้อัปเกรดฟรี ×1, ×2 หรือ ×3 ครั้ง', en: 'A King gives one chest. Open it and the wheel spins for ×1, ×2 or ×3 free upgrades.' },
  'g.chest.spin': { th: 'หมุนวงล้อ!', en: 'SPIN!' },
  'g.chest.won': { th: 'ได้อัปเกรดฟรี ×{n}!', en: '×{n} free upgrades!' },
  'g.chest.odds': { th: 'โอกาส: ×1 = {a}% · ×2 = {b}% · ×3 = {c}%', en: 'Odds: ×1 = {a}% · ×2 = {b}% · ×3 = {c}%' },
  'g.chest.stats': { th: 'หมุนไปแล้ว {n} ครั้ง', en: '{n} spins so far' },

  'g.kings.h': { th: 'ราชา (บอส)', en: 'Kings (bosses)' },
  'g.kings.p': { th: 'ราชาทุกองค์มี <b>2 ท่าปกติ</b> และ <b>ท่าไม้ตาย</b> เมื่อเลือดต่ำกว่าครึ่ง ทุกท่ามี <b>พื้นที่สีแดงเตือนก่อน</b> เสมอ เห็นแดง = เดินออก!', en: 'Every King has <b>2 normal moves</b> and an <b>ultimate move</b> below half HP. Every move shows a <b>red warning area first</b>. See red = walk out!' },
  'g.kings.warn': { th: 'ลองหลบ: กดพื้นที่ที่ <b>ไม่แดง</b> ก่อนเวลาหมด', en: 'Dodge it: click a spot that is <b>not red</b> before time runs out' },
  'g.kings.safe': { th: 'รอด! 👍', en: 'Safe! 👍' },
  'g.kings.hit': { th: 'โดนเต็ม ๆ! ลองใหม่', en: 'Ouch! Try again' },
  'g.kings.again': { th: 'อีกรอบ', en: 'Again' },
  'g.kings.say': { th: 'ราชาพูดเยอะ:', en: 'Kings love to talk:' },

  'g.events.h': { th: 'ด่านพิเศษ', en: 'Special events' },
  'g.events.p': { th: 'ตั้งแต่ Chapter 2–7 บางด่านจะกลายเป็นด่านพิเศษ ไม่บอกล่วงหน้า!', en: 'From Chapter 2 to 7 a Stage may turn special — without warning!' },
  'g.ev.moon.h': { th: 'Blood Moon', en: 'Blood Moon' },
  'g.ev.moon.p': { th: 'ฟ้าเป็นสีแดง มอนเกิด ×{s} แต่ Gold ×{c} และได้หีบโบนัสตอนจบด่าน ยิ่งไม่เจอนาน โอกาสยิ่งสูง', en: 'The sky turns red: ×{s} monsters, but ×{c} Gold and a bonus chest at the end. The longer since the last one, the likelier it gets.' },
  'g.ev.dragon.h': { th: 'มังกรผู้พิทักษ์', en: 'Guardian dragons' },
  'g.ev.dragon.p': { th: 'บางคืน Blood Moon (Chapter 3+) มีมังกรมา 1 ใน 3 ตัว ปราบได้มันจะมาเป็น <b>สัตว์คู่ใจ</b> ช่วยสู้ เก็บได้ 3 ตัว ปราบครบ 3 ตัวในรอบเดียว = รวมร่างเป็น <b>มังกร 3 หัว</b>!', en: 'Some Blood Moons (Chapter 3+) bring 1 of 3 dragons. Beat it and it becomes your <b>Companion</b>. Beat all 3 in one Run and fuse them into the <b>Three-headed Dragon</b>!' },
  'g.ev.rival.h': { th: 'Shadow Rival', en: 'Shadow Rival' },
  'g.ev.rival.p': { th: 'ร่างเงาหน้าตาเหมือนคุณ ใช้สกิลคล้ายคุณ มีเวลา 35 วิ ชนะได้ = ได้ร่างโคลนช่วยยิง หรือเศษเงา (3 เศษ = ร่างโคลน)', en: 'A shadow wearing your face, using skills like yours. You have 35 s. Win for a Shadow Clone that copies your casts, or a shard (3 shards = a clone).' },
  'g.ev.double.h': { th: 'ราชา 2 องค์', en: 'Double King' },
  'g.ev.double.p': { th: 'Chapter 4+ มีโอกาสเจอราชา 2 องค์พร้อมกัน เลือดคนละ 70% ได้รางวัลทั้งคู่', en: 'From Chapter 4, two Kings may show up at once, each at 70% HP. You get both rewards.' },

  'g.sp.h': { th: 'Skill Point', en: 'Skill Points' },
  'g.sp.p': { th: 'ได้จาก <b>ราชา</b> เท่านั้น ใช้ตอนเลเวลอัป:', en: 'Only <b>Kings</b> give them. Spend them on level-up:' },
  'g.sp.reroll': { th: '<b>สุ่มใหม่</b> — ไม่ชอบตัวเลือก สุ่มการ์ดใหม่ (1 SP)', en: '<b>Reroll</b> — new cards if you dislike these (1 SP)' },
  'g.sp.banish': { th: '<b>แบน</b> — ตัดสกิลที่ไม่อยากได้ออกจากรอบนี้ (1 SP)', en: '<b>Banish</b> — remove a skill from this Run (1 SP)' },
  'g.sp.up': { th: '<b>+1 เลเวล</b> — อัปสกิลที่เลือกทันที (2 SP)', en: '<b>+1 level</b> — raise a chosen skill now (2 SP)' },

  'g.awaken.h': { th: 'ตื่นพลัง (Awakening)', en: 'Awakening' },
  'g.awaken.p': { th: 'สกิลทั่วไป 12 ตัวแบ่งเป็น 4 สาย ฮีโร่ทุกคนหยิบได้ทุกสกิล แต่สกิลใน <b>สายของตัวเอง</b> จะนับเป็น <b>Link</b>', en: 'The 12 general skills are split into 4 Lines. Any Hero can take any skill, but skills from <b>their own Line</b> count as <b>Links</b>.' },
  'g.awaken.rule': { th: 'เงื่อนไข: สกิลประจำตัว <b>วิวัฒน์แล้ว</b> + Link <b>2 ใน 3</b> เต็มเลเวลและอยู่ในช่องโจมตีมาแล้ว 1 ด่าน → ตอนจบด่านจะถามว่าจะตื่นพลังไหม รับ = เปลี่ยนร่าง สกิลประจำตัวแรงขึ้น Link ยังอยู่ครบ ได้ช่องสกิลโจมตีเพิ่ม 1 ช่องพร้อมสกิลตื่นพลังตัวแรก และอีก 2 ตัวจะมาให้เลือกตอนเลเวลอัป (ปฏิเสธ = หมดสิทธิ์ในรอบนั้น)', en: 'Needs: your Signature Skill <b>evolved</b> + <b>2 of 3</b> Links at max level, equipped for at least one Stage → at a Stage end you are asked. Accept = your form changes and your Signature grows stronger; your Links stay, and you get an extra attack slot holding your first Awakened skill, with 2 more joining the level-up choices. (Decline = no second chance that Run.)' },
  'g.awaken.more': { th: 'ดูสายของแต่ละฮีโร่ →', en: 'See each Hero\'s Line →' },

  'g.gold.h': { th: 'Gold, ร้านค้า และฮีโร่', en: 'Gold, the Shop and Heroes' },
  'g.gold.p': { th: '<b>Gold</b> คือของอย่างเดียวที่อยู่ข้ามรอบ ได้จากมอนและราชา เข้ากระเป๋าตอนผ่านด่านหรือตาย ใช้ซื้อ:', en: '<b>Gold</b> is the only thing that survives a Run. It comes from monsters and Kings, and goes to your wallet on a Stage clear or when you fall. Spend it on:' },
  'g.gold.shop': { th: 'อัปเกรดถาวร (ร้านค้า)', en: 'Permanent upgrades (Shop)' },
  'g.gold.heroes': { th: 'ปลดล็อกฮีโร่', en: 'Unlock Heroes' },
  'g.gold.run': { th: 'ในรอบ: สลับสกิล Bench และซื้อชีวิตเพิ่ม 1 ครั้ง (คะแนน −15%)', en: 'Inside a Run: Bench swaps and one bought revive (−15% Score)' },

  'g.coop.h': { th: 'เล่นกับเพื่อน (Co-op)', en: 'Co-op with friends' },
  'g.coop.p': { th: 'สูงสุด 4 คน ต่อผ่านลิงก์เดียว ไม่ต้องสมัครสมาชิก', en: 'Up to 4 players over one link — no sign-up needed.' },
  'g.coop.1': { th: 'คนหนึ่งกด <b>เล่นด้วยกัน → สร้างห้อง</b> ได้รหัสห้อง 4–6 ตัว', en: 'One player taps <b>Co-op → Create room</b> and gets a 4–6 letter code.' },
  'g.coop.2': { th: 'กด <b>คัดลอกลิงก์ชวน</b> ส่งให้เพื่อน (หรือบอกรหัส)', en: 'Tap <b>Copy invite link</b> and send it (or just share the code).' },
  'g.coop.3': { th: 'ทุกคนกด <b>พร้อม</b> โฮสต์กดเริ่ม ลุย!', en: 'Everyone taps <b>Ready</b>, the host starts. Go!' },
  'g.coop.rules': { th: 'กติกาทีม', en: 'Team rules' },
  'g.coop.r1': { th: 'EXP, Gold และหีบ ได้ทั้งทีม ใครเก็บก็ได้เหมือนกัน', en: 'EXP, Gold and chests go to the whole team, whoever picks them up.' },
  'g.coop.r2': { th: 'เกมไม่หยุดตอนเลือกการ์ด คนที่กำลังเลือกอยู่ในฟองโล่ ไม่โดนดาเมจ มีเวลา 10 วิ', en: 'The game never pauses: whoever is choosing sits in a shield bubble (no damage) for up to 10 s.' },
  'g.coop.r3': { th: 'เพื่อนล้ม? ยืนข้าง ๆ 3 วินาทีเพื่อชุบ', en: 'A friend is down? Stand next to them for 3 s to revive.' },
  'g.coop.r4': { th: 'หัวใจที่เก็บได้ ฮีลเพื่อนที่อยู่ใกล้ด้วย', en: 'A heart you grab also heals nearby friends.' },

  'g.tips.h': { th: 'เคล็ดลับมือใหม่', en: 'Beginner tips' },
  'g.tip.1': { th: 'อย่ายืนนิ่ง! เดินเป็นวงกว้าง ๆ ให้มอนตามเป็นแถว', en: 'Never stand still! Walk in big circles so monsters trail behind you.' },
  'g.tip.2': { th: 'ช่วงแรกเน้นเก็บคริสตัล เลเวลไวคือรอดง่าย', en: 'Early on, grab crystals. Levelling fast is how you survive.' },
  'g.tip.3': { th: 'เลือกสกิลที่ทิ้งสถานะ + สกิลที่ปลดคอมโบ เช่น Frost Aura + Meteor', en: 'Pair a skill that leaves a Status with one that triggers it, like Frost Aura + Meteor.' },
  'g.tip.4': { th: 'เก็บท่าไม้ตายไว้ใช้ตอนโดนล้อม หรือตอนราชามา', en: 'Save your Ultimate for when you are surrounded, or for the King.' },
  'g.tip.5': { th: 'หน้าเลือกดินแดนบอก "สกิลที่ได้เปรียบ" ดูก่อนเลือก', en: 'The route screen shows "Skills with the advantage" — check it before you choose.' },
  'g.tip.6': { th: 'มือใหม่ลอง Bram (อัศวินโล่) ทนที่สุด กันกระสุนได้', en: 'New? Try Bram, the shield knight: toughest, and blocks bullets.' },

  // ── skills page ────────────────────────────────────────
  'sk.title': { th: 'สกิล & คอมโบ — Pixel Horde', en: 'Skills & Combos — Pixel Horde' },
  'sk.h': { th: 'สกิล คอมโบ และการวิวัฒน์', en: 'Skills, Combos and Evolutions' },
  'sk.p': { th: 'ตารางสกิลทั้งหมด กดดูตัวเลขแต่ละเลเวล และลองจับคู่สกิลเพื่อดูว่าเกิดคอมโบอะไร', en: 'Every skill in one place. Check the numbers at each level, and pair skills to see which Combos they make.' },
  'sk.tab.table': { th: 'ตารางสกิล', en: 'Skill table' },
  'sk.tab.lab': { th: 'ห้องทดลองคอมโบ', en: 'Combo Lab' },
  'sk.tab.evo': { th: 'ตารางวิวัฒน์', en: 'Evolutions' },
  'sk.tab.lines': { th: 'สายฮีโร่ & ตื่นพลัง', en: 'Hero Lines' },
  'sk.f.all': { th: 'ทั้งหมด', en: 'All' },
  'sk.f.general': { th: 'สกิลทั่วไป', en: 'General' },
  'sk.f.signature': { th: 'สกิลประจำตัว', en: 'Signature' },
  'sk.f.line': { th: 'สกิลตื่นพลัง', en: 'Awakened' },
  'sk.f.search': { th: 'ค้นหาสกิล…', en: 'Search skills…' },
  'sk.f.el': { th: 'ธาตุ', en: 'Element' },
  'sk.none': { th: 'ไม่พบสกิลที่ตรงกัน', en: 'No skill matches' },
  'sk.lv': { th: 'เลเวล', en: 'Level' },
  'sk.evoOn': { th: 'แบบวิวัฒน์', en: 'Evolved' },
  'sk.cd': { th: 'คูลดาวน์', en: 'Cooldown' },
  'sk.dmg': { th: 'ดาเมจ', en: 'Damage' },
  'sk.count': { th: 'จำนวน', en: 'Count' },
  'sk.radius': { th: 'รัศมี', en: 'Radius' },
  'sk.jumps': { th: 'กระโดด', en: 'Jumps' },
  'sk.pierce': { th: 'ทะลุ', en: 'Pierce' },
  'sk.dur': { th: 'ระยะเวลา', en: 'Duration' },
  'sk.len': { th: 'ความยาว', en: 'Length' },
  'sk.range': { th: 'ระยะ', en: 'Range' },
  'sk.boom': { th: 'ระเบิด', en: 'Collapse' },
  'sk.speed': { th: 'ความเร็วหมุน', en: 'Spin speed' },
  'sk.sec': { th: 'วิ', en: 's' },
  'sk.max': { th: 'เต็ม Lv {n}', en: 'Max Lv {n}' },
  'sk.evoWith': { th: 'วิวัฒน์ด้วย', en: 'Evolves with' },
  'sk.noEvo': { th: 'ไม่มีวิวัฒน์ (สกิลตื่นพลังแรงอยู่แล้ว)', en: 'No evolution (Awakened skills are strong already)' },
  'sk.leaves': { th: 'ทิ้งสถานะ', en: 'Leaves' },
  'sk.triggers': { th: 'ปลดคอมโบ', en: 'Triggers' },
  'sk.lineOf': { th: 'นับเป็น Link ของ', en: 'Link for' },
  'sk.sigOf': { th: 'สกิลประจำตัวของ', en: 'Signature of' },
  'sk.awOf': { th: 'สกิลตื่นพลังของ', en: 'Awakened skill of' },
  'sk.pairs': { th: 'เข้าคอมโบกับ', en: 'Combos with' },
  'sk.passives': { th: 'พาสซีฟ 6 แบบ', en: 'The 6 passives' },
  'sk.pasEvo': { th: 'ใช้วิวัฒน์', en: 'Evolves' },

  'lab.h': { th: 'ห้องทดลองคอมโบ', en: 'Combo Lab' },
  'lab.p': { th: 'เลือก 2 สกิล แล้วดูว่าเกิดคอมโบอะไร (ลำดับไม่สำคัญ สกิลไหนทิ้งสถานะก่อนก็ได้)', en: 'Pick two skills and see which Combos they make (order does not matter — either may leave the Status).' },
  'lab.a': { th: 'สกิล A', en: 'Skill A' },
  'lab.b': { th: 'สกิล B', en: 'Skill B' },
  'lab.none': { th: 'คู่นี้ไม่เกิดคอมโบ ลองคู่อื่นดู', en: 'No Combo for this pair. Try another!' },
  'lab.how': { th: '{a} ทิ้ง <b>{status}</b> → {b} {tag} ตีโดน → <b>{combo}</b>', en: '{a} leaves <b>{status}</b> → {b} lands a {tag} hit → <b>{combo}</b>' },
  'lab.anyStatus': { th: 'สถานะใดก็ได้', en: 'any Status' },
  'lab.random': { th: 'สุ่มคู่ที่คอมโบ', en: 'Random combo pair' },
  'lab.matrix': { th: 'ตารางคอมโบทุกคู่', en: 'Every pair at a glance' },
  'lab.matrixP': { th: 'ช่องที่มีสี = คู่นี้เกิดคอมโบ กดช่องเพื่อโหลดเข้าห้องทดลอง', en: 'A coloured cell = that pair makes a Combo. Click it to load it into the lab.' },
  'lab.statuses': { th: 'สถานะ 5 แบบ', en: 'The 5 Statuses' },
  'lab.combos': { th: 'คอมโบ 7 แบบ', en: 'The 7 Combos' },
  'lab.cd': { th: 'คอมโบเดิมเกิดซ้ำบนมอนตัวเดิมได้ทุก {s} วินาที · ดาเมจจากคอมโบไม่ปลดคอมโบต่อ', en: 'The same Combo can hit the same monster again after {s} s · Combo damage never starts another Combo' },
  'lab.madeBy': { th: 'สกิลที่ทำได้', en: 'Skills that do it' },
  'lab.recipe': { th: 'สูตร', en: 'Recipe' },

  'el.none': { th: 'ไม่มีธาตุ', en: 'No element' },
  'st.frozen.d': { th: 'หยุดนิ่ง {s} วิ (บอสแค่ช้าลง) Frost Aura โดนครบ {n} ครั้งจะแข็ง', en: 'Stuck for {s} s (bosses only slow). Frost Aura freezes after {n} ticks.' },
  'st.gathered.d': { th: 'ถูกดูดเข้ามากองรวมกัน อยู่ต่ออีก {s} วิหลังดูดเสร็จ', en: 'Pulled into a pack; lasts {s} s after the pull ends.' },
  'st.burning.d': { th: 'ติดไฟ {s} วิ', en: 'On fire for {s} s.' },
  'st.shocked.d': { th: 'มีไฟฟ้าค้าง {s} วิ', en: 'Charged with lightning for {s} s.' },
  'st.poisoned.d': { th: 'โดนพิษ {s} วิ เสียเลือดต่อเนื่อง', en: 'Poisoned for {s} s, losing HP over time.' },

  'cb.shatter': { th: 'แข็ง + ตีแรง → ดาเมจ ×{m} และเศษน้ำแข็งโดนตัวรอบ ๆ', en: 'Frozen + heavy hit → ×{m} damage, and ice shards hit monsters around it' },
  'cb.firestorm': { th: 'ถูกดูดรวม + ไฟ → ไฟลามทั้งกอง ทุกตัวติดไฟ', en: 'Gathered + fire → fire spreads through the whole pack and sets it Burning' },
  'cb.overload': { th: 'ช็อต + ไฟ → ระเบิดไฟฟ้า ×{m} ของดาเมจ', en: 'Shocked + fire → an electric blast worth ×{m} of the hit' },
  'cb.superconduct': { th: 'แข็ง + สายฟ้า → ลบเกราะมอน {s} วิ', en: 'Frozen + lightning → strips the monster\'s armour for {s} s' },
  'cb.toxicBurst': { th: 'ติดพิษ + ไฟ → พิษที่เหลือระเบิดออกมาทีเดียว ×{m}', en: 'Poisoned + fire → all remaining poison bursts at once, ×{m}' },
  'cb.grinder': { th: 'ถูกดูดรวม + ตัวกวาด → ดาเมจ ×{m}', en: 'Gathered + sweeper → ×{m} damage' },
  'cb.catalyst': { th: 'Arcane Bolt โดนมอนที่มีสถานะใดก็ได้ → ดาเมจ ×{m}', en: 'Arcane Bolt on a monster with any Status → ×{m} damage' },

  'evo.h': { th: 'ตารางวิวัฒน์: สกิลเต็ม + พาสซีฟคู่', en: 'Evolutions: max skill + paired passive' },
  'evo.p': { th: 'แต่ละแถวคือสูตร กดที่แถวเพื่อดูรายละเอียดสกิล', en: 'Each row is a recipe. Click a row to see the skill.' },
  'evo.skill': { th: 'สกิล (เต็มเลเวล)', en: 'Skill (max level)' },
  'evo.passive': { th: 'พาสซีฟคู่', en: 'Passive' },
  'evo.result': { th: 'ได้', en: 'Becomes' },
  'evo.byPassive': { th: 'มองจากพาสซีฟ: พาสซีฟนี้ปลดวิวัฒน์ของ…', en: 'By passive: this passive evolves…' },

  'lines.h': { th: 'สายฮีโร่และการตื่นพลัง', en: 'Hero Lines and Awakening' },
  'lines.p': { th: 'สกิลประจำตัว → วิวัฒน์ → Link 2 ใน 3 เต็ม → ตื่นพลัง → สกิลตื่นพลังใหม่ 3 ตัว', en: 'Signature → evolve → max 2 of 3 Links → Awaken → 3 new Awakened skills' },
  'lines.sig': { th: 'สกิลประจำตัว', en: 'Signature' },
  'lines.links': { th: 'Link (สกิลในสาย)', en: 'Links (Line skills)' },
  'lines.form': { th: 'ร่างตื่นพลัง', en: 'Awakened form' },
  'lines.new': { th: 'สกิลใหม่หลังตื่นพลัง', en: 'New skills after Awakening' },
  'lines.survive': { th: 'เอาตัวรอด', en: 'survival' },

  // ── world page ─────────────────────────────────────────
  'w.title': { th: 'โลก Lumora — Pixel Horde', en: 'The World of Lumora — Pixel Horde' },
  // ── updates (changelog) ──
  'up.title': { th: 'อัปเดต — Pixel Horde', en: 'Updates — Pixel Horde' },
  'up.h': { th: 'อัปเดตเกม', en: 'Game Updates' },
  'up.p': { th: 'ทุกครั้งที่เกมเปลี่ยน อ่านได้ที่นี่ ทั้งของใหม่ การแก้บั๊ก และการปรับสมดุล แยกตามหมวดให้ดูง่าย', en: 'Every change to the game: new things, fixes and balance updates, sorted by topic.' },
  'up.all': { th: 'ทั้งหมด', en: 'All' },
  'up.loading': { th: 'กำลังโหลด…', en: 'Loading…' },
  'up.error': { th: 'โหลดรายการอัปเดตไม่ได้ ลองรีเฟรชอีกครั้ง', en: "Couldn't load the updates. Try refreshing." },
  'up.empty': { th: 'ยังไม่มีอัปเดตในหมวดนี้', en: 'No updates of this kind yet.' },
  'up.config': { th: 'ค่าสมดุล v{v}', en: 'Balance v{v}' },
  'up.small': { th: 'ปรับค่าเล็กน้อย', en: 'Small adjustments' },
  'w.h': { th: 'โลก Lumora', en: 'The World of Lumora' },
  'w.p': { th: 'ฮีโร่ ดินแดน ราชา มังกร และมอนสเตอร์ทุกตัว', en: 'Heroes, Realms, Kings, dragons and every monster.' },
  'w.story.h': { th: 'เรื่องราว', en: 'The story' },
  'w.story.p': { th: '<b>หัวใจแห่ง Lumora</b> คือคริสตัลที่ค้ำจุนโลกทั้งใบ จนวันหนึ่ง <b>Umbra</b> เงามืดที่เกิดจากด้านมืดของหัวใจเอง ทุบมันแตกกระจาย เศษชิ้นใหญ่ตกไปอยู่ในมือ <b>ราชา</b> ของแต่ละดินแดนจนพวกเขาคลั่ง และเศษเล็ก ๆ ทำให้มอนสเตอร์รวมตัวเป็นฝูง<br>ฮีโร่ 4 คนจึงออกเดินทางเพื่อเก็บเศษหัวใจคืนมาให้ครบ', en: 'The <b>Heart of Lumora</b> is the crystal that keeps the world alive — until <b>Umbra</b>, a shadow born from the Heart\'s own dark side, shattered it. Large shards fell to the <b>Kings</b> of each Realm and drove them mad; the small ones drove monsters into hordes.<br>Four Heroes set out to bring every shard home.' },
  'w.heroes': { th: 'ฮีโร่', en: 'Heroes' },
  'w.realms': { th: 'ดินแดน', en: 'Realms' },
  'w.guardians': { th: 'มังกรผู้พิทักษ์', en: 'Guardians' },
  'w.bestiary': { th: 'สมุดมอนสเตอร์', en: 'Bestiary' },
  'w.role': { th: 'บทบาท', en: 'Role' },
  'w.bonus': { th: 'ค่าติดตัว', en: 'Bonus' },
  'w.unlock': { th: 'ปลดล็อก', en: 'Unlock' },
  'w.form': { th: 'ร่างตื่นพลัง', en: 'Awakened form' },
  'w.line': { th: 'สาย Link', en: 'Link Line' },
  'w.mobs': { th: 'มอนประจำถิ่น', en: 'Monsters' },
  'w.king': { th: 'ราชา', en: 'King' },
  'w.traits': { th: 'ลักษณะเด่น', en: 'Traits' },
  'w.resist': { th: 'ทนธาตุ (ดาเมจ −50%)', en: 'Resists (−50% damage)' },
  'w.noResist': { th: 'ไม่มี', en: 'None' },
  'w.noTraits': { th: 'ไม่มี (ดินแดนสอนเล่น)', en: 'None (the tutorial Realm)' },
  'w.advice': { th: 'สกิลที่ได้เปรียบ', en: 'Skills with the advantage' },
  'w.weapon': { th: 'อาวุธที่ดรอป', en: 'Weapon drop' },
  'w.moves': { th: 'ท่าของราชา', en: 'King moves' },
  'w.ult': { th: 'ท่าไม้ตาย', en: 'ultimate' },
  'w.chapter1': { th: 'Chapter 1 เสมอ', en: 'Always Chapter 1' },
  'w.chapter8': { th: 'Chapter 8 ด่านสุดท้าย', en: 'Chapter 8, the finale' },
  'w.chapterMid': { th: 'Chapter 2–7 (เลือกได้)', en: 'Chapters 2–7 (by choice)' },
  'w.drag.p': { th: 'มังกร 3 ตัวที่แยกออกจากผู้พิทักษ์ 3 หัวตัวเดิมของหัวใจ เจอได้ในคืน Blood Moon ปราบแล้วกลายเป็นสัตว์คู่ใจ (เลเวล 1–5 ในรอบ)', en: 'Three dragons torn from the Heart\'s original three-headed guardian. Found on Blood Moon nights; beat one and it becomes your Companion (levels 1–5 in a Run).' },
  'w.drag.inferno': { th: 'ลมหายใจไฟเป็นรูปกรวย พุ่งชน ฝนลูกไฟ เรียกลูกมังกร', en: 'Fire breath cone, dash, fireball rain, calls whelps.' },
  'w.drag.frost': { th: 'ลมหายใจน้ำแข็ง วงเสาน้ำแข็ง พายุหิมะ (หยุดเดิน = แข็ง!)', en: 'Ice breath, ice-pillar ring, blizzard (stand still = frozen!).' },
  'w.drag.storm': { th: 'แถวสายฟ้า ลูกไฟฟ้าเด้งไปมา พุ่งชนเร็วมาก', en: 'Lightning rows, bouncing orbs, a very fast dash.' },
  'w.best.p': { th: 'วางเมาส์ / แตะที่มอนเพื่ออ่านเรื่องของมัน', en: 'Hover or tap a monster to read about it.' },
  'w.best.filter': { th: 'ดินแดน', en: 'Realm' },
  'w.best.counter': { th: 'มอนแก้ทาง (โผล่ได้ทุกดินแดน)', en: 'Counter monsters (any Realm)' },
  'w.best.event': { th: 'บอสพิเศษ', en: 'Special bosses' },
} satisfies Record<string, Pair>;

export type TextKey = keyof typeof TXT;
