// Heart Crater: Umbra, the shadow of the Heart (40×40: idle ×2 + wind-up) — draft for the owner's review.
import { OUTLINE, type RealmSprites } from '../types';

const UMBRA_A: string[] = [
  "........................................",
  "....K..............................K....",
  "...KdK............................KdK...",
  "...KdK............................KdK...",
  "...KddK..........................KddK...",
  "....KddK........................KddK....",
  "....KdddK.......KKKKKKKK.......KdddK....",
  ".....KdddK....KKddddddddKK....KdddK.....",
  ".....KddddKKKKddddDddDddddKKKKddddK.....",
  "......KdddddddddDDddddDDdddddddddK......",
  "......KddddddddDddd..dddDddddddddK......",
  ".......KdddddddDddddddddDdddddddK.......",
  ".......KddddKKKKKKKKKKKKKKKKddddK.......",
  ".......KdddKrrrKddddddddKrrrKdddK.......",
  ".......KdddKrRrKddddddddKrRrKdddK.......",
  ".......KddddKKKddddddddddKKKddddK.......",
  ".......KddddddddddddddddddddddddK.......",
  "........KddddddddKKKKKKddddddddK........",
  "......KKdddddddKKppppppKKdddddddKK......",
  ".....KdddddddddKpPPppPPpKdddddddddK.....",
  "....KddddddddddKpPWPPWPpKddddddddddK....",
  "...KddddKddddddKpPPPPPPpKddddddKddddK...",
  "..KddddK.KdddddKppPPPPppKdddddK.KddddK..",
  "..KdddK..KddddddKppppppKddddddK..KdddK..",
  ".KdddK...KdddddddKKKKKKdddddddK...KdddK.",
  ".KddK....KddddddddddddddddddddK....KddK.",
  "KddK.....KddddddddddddddddddddK.....KddK",
  "KdK......KddddddddDddDddddddddK......KdK",
  "KK......KdddddddddDddDdddddddddK......KK",
  "........KddddddddDddddDddddddddK........",
  ".......KdddddddddDddddDdddddddddK.......",
  ".......KddddddddDddddddDddddddddK.......",
  "......KdddddddddDddddddDdddddddddK......",
  "......KddddddddDddddddddDddddddddK......",
  ".....KdddddddddDddddddddDdddddddddK.....",
  ".....KddddddddDddddddddddDddddddddK.....",
  "....KdKddKddKddKddddddddKddKddKddKdK....",
  "....KK.KK.KK.KK.KKddddKK.KK.KK.KK.KK....",
  "..................KKKK..................",
  "........................................",
];

const UMBRA_B: string[] = [
  "........................................",
  "........................................",
  "....K..............................K....",
  "...KdK............................KdK...",
  "...KdK............................KdK...",
  "...KddK..........................KddK...",
  "....KddK........................KddK....",
  "....KdddK.......KKKKKKKK.......KdddK....",
  ".....KdddK....KKddddddddKK....KdddK.....",
  ".....KddddKKKKddddDddDddddKKKKddddK.....",
  "......KdddddddddDDddddDDdddddddddK......",
  "......KddddddddDddd..dddDddddddddK......",
  ".......KdddddddDddddddddDdddddddK.......",
  ".......KddddKKKKKKKKKKKKKKKKddddK.......",
  ".......KdddKrrrKddddddddKrrrKdddK.......",
  ".......KdddKrRrKddddddddKrRrKdddK.......",
  ".......KddddKKKddddddddddKKKddddK.......",
  ".......KddddddddddddddddddddddddK.......",
  "........KddddddddKKKKKKddddddddK........",
  "......KKdddddddKKppppppKKdddddddKK......",
  ".....KdddddddddKpPPppPPpKdddddddddK.....",
  "....KddddddddddKpPWPPWPpKddddddddddK....",
  "...KddddKddddddKpPPPPPPpKddddddKddddK...",
  "..KddddK.KdddddKppPPPPppKdddddK.KddddK..",
  "..KdddK..KddddddKppppppKddddddK..KdddK..",
  ".KdddK...KdddddddKKKKKKdddddddK...KdddK.",
  ".KddK....KddddddddddddddddddddK....KddK.",
  "KddK.....KddddddddddddddddddddK.....KddK",
  "KdK......KddddddddDddDddddddddK......KdK",
  "KK......KdddddddddDddDdddddddddK......KK",
  "........KddddddddDddddDddddddddK........",
  ".......KdddddddddDddddDdddddddddK.......",
  ".......KddddddddDddddddDddddddddK.......",
  "......KdddddddddDddddddDdddddddddK......",
  "......KddddddddDddddddddDddddddddK......",
  ".....KdddddddddDddddddddDdddddddddK.....",
  ".....KddddddddDddddddddddDddddddddK.....",
  "....KdKddKddKddKddddddddKddKddKddKdK....",
  "....KK.KK.KK.KK.KKddddKK.KK.KK.KK.KK....",
  "..................KKKK..................",
];

const UMBRA_W: string[] = [
  "...KdK............................KdK...",
  "...KdK............................KdK...",
  "...KddK..........................KddK...",
  "....KddK........................KddK....",
  "....KdddK.......KKKKKKKK.......KdddK....",
  ".....KdddK....KKddddddddKK....KdddK.....",
  ".....KddddKKKKddddDddDddddKKKKddddK.....",
  "......KdddddddddDDddddDDdddddddddK......",
  "......KddddddddDddd..dddDddddddddK......",
  ".......KdddddddDddddddddDdddddddK.......",
  ".......KddddKKKKKKKKKKKKKKKKddddK.......",
  ".......KdddKrrrKddddddddKrrrKdddK.......",
  ".......KdddKrRrKddddddddKrRrKdddK.......",
  ".......KddddKKKddddddddddKKKddddK.......",
  ".......KddddddddddddddddddddddddK.......",
  "........KddddddddKKKKKKddddddddK........",
  "......KKdddddddKKppppppKKdddddddKK......",
  ".....KdddddddddKpPPppPPpKdddddddddK.....",
  "....KddddddddddKpPWPPWPpKddddddddddK....",
  "...KddddKddddddKpPPPPPPpKddddddKddddK...",
  "..KddddK.KdddddKppPPPPppKdddddK.KddddK..",
  "..KdddK..KddddddKppppppKddddddK..KdddK..",
  ".KdddK...KdddddddKKKKKKdddddddK...KdddK.",
  ".KddK....KddddddddddddddddddddK....KddK.",
  "KddK.....KddddddddddddddddddddK.....KddK",
  "KdK......KddddddddDddDddddddddK......KdK",
  "KK......KdddddddddDddDdddddddddK......KK",
  "........KddddddddDddddDddddddddK........",
  ".......KdddddddddDddddDdddddddddK.......",
  ".......KddddddddDddddddDddddddddK.......",
  "......KdddddddddDddddddDdddddddddK......",
  "......KddddddddDddddddddDddddddddK......",
  ".....KdddddddddDddddddddDdddddddddK.....",
  ".....KddddddddDddddddddddDddddddddK.....",
  "....KdKddKddKddKddddddddKddKddKddKdK....",
  "....KK.KK.KK.KK.KKddddKK.KK.KK.KK.KK....",
  "..................KKKK..................",
  "........................................",
  "........................................",
  "........................................",
];

export const CRATER: RealmSprites = {
  realm: 'crater',
  palette: [OUTLINE, '#2a1f3d', '#4a2d80', '#6a4aa0', '#ff2a5c', '#ff8aa8', '#ffc0d0', '#ffffff', '#b07cff'],
  ground: 4,
  sprites: {
    umbra: { frames: [UMBRA_A, UMBRA_B, UMBRA_W], pal: { K: OUTLINE, d: '#2a1f3d', D: '#4a2d80', r: '#ff2a5c', R: '#ffffff', p: '#b0203c', P: '#ff2a5c', W: '#ffc0d0' }, note: 'Umbra 40×40 (idle ×2, wind-up)' },
  },
};
