// Deepdark (cave): bat, Skeleton Archer, ghost, Bone King (skeletons are raised by the King).
import { OUTLINE, type RealmSprites } from '../types';

/** Pad a 12-wide body to the 14-wide crown. */
export const pad1 = (rows: string[]): string[] => rows.map((r) => '.' + r + '.');

export const GHOST: string[] = [
  "....KKKK....",
  "..KKwwwwKK..",
  ".KwwwwwwwwK.",
  "KwwwwwwwwwwK",
  "KwwKKwwKKwwK",
  "KwwKKwwKKwwK",
  "KwwwwwwwwwwK",
  "KwwwwKKwwwwK",
  "KwwwwwwwwwwK",
  "KwwwwwwwwwwK",
  "KwwwKwwKwwwK",
  ".KK.K.KK.KK.",
];
export const SKEL: string[] = [
  "...KKKKKK...",
  "..KwwwwwwK..",
  ".KwwwwwwwwK.",
  ".KwKKwwKKwK.",
  ".KwKKwwKKwK.",
  ".KwwwwwwwwK.",
  "..KwKwKwKK..",
  "...KKKKKK...",
  "....KwwK....",
  "..KKwwwwKK..",
  ".KwKwKKwKwK.",
  "..K.KwwK.K..",
  "...KwK.KwK..",
  "...KK...KK..",
];

/** Skeleton Archer (ticket 35): bow on its left side. */
const ARCHER: string[] = [
  "...KKKKKK.....",
  "..KwwwwwwK....",
  ".KwKKwwKKwK...",
  ".KwKKwwKKwK.K.",
  ".KwwwwwwwwK.Kb",
  "..KwKwKwKK..Kb",
  "...KKKKKK...Kb",
  "..KKwwwwKK.KbK",
  ".KwKwKKwKwKKbK",
  "..K.KwwK.KwKb.",
  "...KwK.KwK.Kb.",
  "...KK...KK..K.",
];

const KBONE_A: string[] = [
  "................................",
  "...........K...KK...K...........",
  "..........KYK.KYYK.KYK..........",
  "..........KYYKYYYYKYYK..........",
  "..........KYYYYYYYYYYK..........",
  ".........KKKKKKKKKKKKKK.........",
  "........KwwwwwwWWwwwwwwK........",
  ".......KwwwwwwWWWWwwwwwwK.......",
  "......KwwKKKKwwwwwwKKKKwwK......",
  "......KwKKrrKKwwwwKKrrKKwK......",
  "......KwKKrrKKwwwwKKrrKKwK......",
  "......KwwKKKKwwwwwwKKKKwwK......",
  ".......KwwwwwKKwwKKwwwwwK.......",
  "........KwwKwKwKKwKwKwwK........",
  ".........KKKKKKKKKKKKKK.........",
  ".....KKK...KwwKwwKwwK...KKK.....",
  "....KwwwK.KKKKKKKKKKKK.KwwwK....",
  "...KwwKwwKwwwwwwwwwwwwKwwKwwK...",
  "...KwKKwwKKKKKKKKKKKKKKwwKKwK...",
  "..KwK.KwwKwwwwwwwwwwwwKwwK.KwK..",
  "..KwK..KwKKKKKKKKKKKKKKwK..KwK..",
  ".KwK...KwKwwwwwwwwwwwwKwK...KwK.",
  ".KwwK..KwKKKKKKKKKKKKKKwK..KwwK.",
  "KwwwK...KwwwwwKKKKwwwwwK...KwwwK",
  "KKKK....KKKwwwK..KwwwKKK....KKKK",
  "...........KwK....KwK...........",
  "..........KwwK....KwwK..........",
  ".........KwwK......KwwK.........",
  "........KwwK........KwwK........",
  "........KKKK........KKKK........",
  "................................",
  "................................",
];

const KBONE_B: string[] = [
  "................................",
  "................................",
  "...........K...KK...K...........",
  "..........KYK.KYYK.KYK..........",
  "..........KYYKYYYYKYYK..........",
  "..........KYYYYYYYYYYK..........",
  ".........KKKKKKKKKKKKKK.........",
  "........KwwwwwwWWwwwwwwK........",
  ".......KwwwwwwWWWWwwwwwwK.......",
  "......KwwKKKKwwwwwwKKKKwwK......",
  "......KwKKrrKKwwwwKKrrKKwK......",
  "......KwKKrrKKwwwwKKrrKKwK......",
  "......KwwKKKKwwwwwwKKKKwwK......",
  ".......KwwwwwKKwwKKwwwwwK.......",
  "........KwwKwKwKKwKwKwwK........",
  ".........KKKKKKKKKKKKKK.........",
  ".....KKK...KwwKwwKwwK...KKK.....",
  "....KwwwK.KKKKKKKKKKKK.KwwwK....",
  "...KwwKwwKwwwwwwwwwwwwKwwKwwK...",
  "...KwKKwwKKKKKKKKKKKKKKwwKKwK...",
  "..KwK.KwwKwwwwwwwwwwwwKwwK.KwK..",
  "..KwK..KwKKKKKKKKKKKKKKwK..KwK..",
  ".KwK...KwKwwwwwwwwwwwwKwK...KwK.",
  ".KwwK..KwKKKKKKKKKKKKKKwK..KwwK.",
  "KwwwK...KwwwwwKKKKwwwwwK...KwwwK",
  "KKKK....KKKwwwK..KwwwKKK....KKKK",
  "...........KwK....KwK...........",
  "..........KwwK....KwwK..........",
  ".........KwwK......KwwK.........",
  "........KwwK........KwwK........",
  "........KKKK........KKKK........",
  "................................",
];

const KBONE_W: string[] = [
  "..........KYK.KYYK.KYK..........",
  "..........KYYKYYYYKYYK..........",
  "..........KYYYYYYYYYYK..........",
  ".........KKKKKKKKKKKKKK.........",
  "........KwwwwwwWWwwwwwwK........",
  ".......KwwwwwwWWWWwwwwwwK.......",
  "......KwwKKKKwwwwwwKKKKwwK......",
  "......KwKKrrKKwwwwKKrrKKwK......",
  "......KwKKrrKKwwwwKKrrKKwK......",
  "......KwwKKKKwwwwwwKKKKwwK......",
  ".......KwwwwwKKwwKKwwwwwK.......",
  "........KwwKwKwKKwKwKwwK........",
  ".........KKKKKKKKKKKKKK.........",
  ".....KKK...KwwKwwKwwK...KKK.....",
  "....KwwwK.KKKKKKKKKKKK.KwwwK....",
  "...KwwKwwKwwwwwwwwwwwwKwwKwwK...",
  "...KwKKwwKKKKKKKKKKKKKKwwKKwK...",
  "..KwK.KwwKwwwwwwwwwwwwKwwK.KwK..",
  "..KwK..KwKKKKKKKKKKKKKKwK..KwK..",
  ".KwK...KwKwwwwwwwwwwwwKwK...KwK.",
  ".KwwK..KwKKKKKKKKKKKKKKwK..KwwK.",
  "KwwwK...KwwwwwKKKKwwwwwK...KwwwK",
  "KKKK....KKKwwwK..KwwwKKK....KKKK",
  "...........KwK....KwK...........",
  "..........KwwK....KwwK..........",
  ".........KwwK......KwwK.........",
  "........KwwK........KwwK........",
  "........KKKK........KKKK........",
  "................................",
  "................................",
  "................................",
  "................................",
];

export const DEEPDARK: RealmSprites = {
  realm: 'deepdark',
  palette: [OUTLINE, '#8a5ad6', '#ff4b5c', '#e9f1ff', '#f0ece0', '#d8d0ff', '#ffd23f'],
  ground: 2,
  sprites: {
    ghost: { frames: [GHOST], pal: { K: OUTLINE, w: '#e9f1ff' } },
    skel: { frames: [SKEL], pal: { K: OUTLINE, w: '#f0ece0' } },
    archer: { frames: [ARCHER], pal: { K: OUTLINE, w: '#f0ece0', b: '#8a5a3a' }, note: 'Skeleton Archer (draft for review)' },
    bossC: { frames: [KBONE_A, KBONE_B, KBONE_W], pal: { K: OUTLINE, w: '#e8e0f8', W: '#b8b0d8', r: '#ff4b5c', Y: '#ffd23f' }, note: 'Bone King 32×32 (idle ×2, wind-up) — draft for review' },
  },
};
