// Duskhold (haunted castle, dark): flying tome, lantern ghost, haunted armor, Lich Queen.
// Tickets 36–38 art: drafts for the owner's review in the Sprite Lab.
import { OUTLINE, type RealmSprites } from '../types';

const BOOK1: string[] = [
  "KKKK......KKKK",
  "KppKK....KKppK",
  "KpwwpK..KpwwpK",
  "KpwwwpKKpwwwpK",
  "KpwwwwpKwwwwpK",
  "KpwwwwpKwwwwpK",
  "KpwwwwpKwwwwpK",
  ".KppwwpKwwppK.",
  "..KKKpKKpKKK..",
  "......KK......",
];

const BOOK2: string[] = [
  "..............",
  "KKK........KKK",
  "KpKKK....KKKpK",
  "KpwwpKKKKpwwpK",
  "KpwwwpKKpwwwpK",
  "KpwwwwpKwwwwpK",
  "KpwwwwpKwwwwpK",
  ".KppwwpKwwppK.",
  "..KKKpKKpKKK..",
  "......KK......",
];

const LANTERN1: string[] = [
  ".....KK.....",
  "....KwwK....",
  "...KKKKKK...",
  "..KgKyyKgK..",
  "..KgyYYygK..",
  "..KgyYYygK..",
  "..KgKyyKgK..",
  "...KKKKKK...",
  "..KwwwwwwK..",
  ".KwKwwwwKwK.",
  ".KwwwwwwwwK.",
  "..KwKwwKwK..",
  "...K.KK.K...",
];

const LANTERN2: string[] = [
  ".....KK.....",
  "....KwwK....",
  "...KKKKKK...",
  "..KgKyyKgK..",
  "..KgyYYygK..",
  "..KgyYYygK..",
  "..KgKyyKgK..",
  "...KKKKKK...",
  "..KwwwwwwK..",
  ".KwKwwwwKwK.",
  ".KwwwwwwwwK.",
  "..KwwKKwwK..",
  "...KK..KK...",
];

const HARMOR: string[] = [
  "....KKKKKK....",
  "...KaaaaaaK...",
  "...KaKrrKaK...",
  "...KaaaaaaK...",
  "..KKKKKKKKKK..",
  ".KaaKaaaaKaaK.",
  "KaaaKaAAaKaaaK",
  "KaKaKaAAaKaKaK",
  "KaKaKaaaaKaKaK",
  "KKKKKaaaaKKKKK",
  "....KaKKaK....",
  "....KaK.KaK...",
  "...KKK...KKK..",
];

const LICH_A: string[] = [
  "................................",
  "...........K...KK...K...........",
  "..........KpK.KppK.KpK..........",
  "..........KppKppppKppK..........",
  "..........KppppppppppK..........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KkkkkkkkKKkkkkkkkK.......",
  "......KkkKwwwwwwwwwwwwKkkK......",
  "......KkKwwwwwwwwwwwwwwKkK......",
  "......KkKwKKwwwwwwwwKKwKkK......",
  "......KkKwKrKwwwwwwKrKwKkK......",
  "......KkKwwwwwwwwwwwwwwKkK......",
  "......KkkKwwKKKwwKKKwwKkkK......",
  ".....KkkkkKwwwwwwwwwwKkkkkK.....",
  "....KkkkkkkKKKKKKKKKKkkkkkkK....",
  "...KkkkkkkkkpppPPpppkkkkkkkkK...",
  "...KkkkkkkkppPppppPppkkkkkkkK...",
  "..KkkKkkkkppppppppppppkkkkKkkK..",
  "..KkK.KkkkkpppPppPpppkkkkK.KkK..",
  ".KkK..KkkkkppppPPppppkkkkK..KkK.",
  ".KwK..KkkkkkpppPPpppkkkkkK..KwK.",
  ".KwwK.KkkkkkpppPPpppkkkkkK.KwwK.",
  "..KK..KkkkkkkppppppkkkkkkK..KK..",
  "......KkkkkkkkppppkkkkkkkK......",
  ".....KkkkkkkkkkppkkkkkkkkkK.....",
  ".....KkkkkkkkkkKKkkkkkkkkkK.....",
  "....KkkkkkkkkkkKKkkkkkkkkkkK....",
  "....KkkkkkkkkkkKKkkkkkkkkkkK....",
  "...KkkkkkkkkkkkKKkkkkkkkkkkkK...",
  "...KKKKKKKKKKKKKKKKKKKKKKKKKK...",
  "................................",
  "................................",
];

const LICH_B: string[] = [
  "................................",
  "................................",
  "...........K...KK...K...........",
  "..........KpK.KppK.KpK..........",
  "..........KppKppppKppK..........",
  "..........KppppppppppK..........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KkkkkkkkKKkkkkkkkK.......",
  "......KkkKwwwwwwwwwwwwKkkK......",
  "......KkKwwwwwwwwwwwwwwKkK......",
  "......KkKwKKwwwwwwwwKKwKkK......",
  "......KkKwKrKwwwwwwKrKwKkK......",
  "......KkKwwwwwwwwwwwwwwKkK......",
  "......KkkKwwKKKwwKKKwwKkkK......",
  ".....KkkkkKwwwwwwwwwwKkkkkK.....",
  "....KkkkkkkKKKKKKKKKKkkkkkkK....",
  "...KkkkkkkkkpppPPpppkkkkkkkkK...",
  "...KkkkkkkkppPppppPppkkkkkkkK...",
  "..KkkKkkkkppppppppppppkkkkKkkK..",
  "..KkK.KkkkkpppPppPpppkkkkK.KkK..",
  ".KkK..KkkkkppppPPppppkkkkK..KkK.",
  ".KwK..KkkkkkpppPPpppkkkkkK..KwK.",
  ".KwwK.KkkkkkpppPPpppkkkkkK.KwwK.",
  "..KK..KkkkkkkppppppkkkkkkK..KK..",
  "......KkkkkkkkppppkkkkkkkK......",
  ".....KkkkkkkkkkppkkkkkkkkkK.....",
  ".....KkkkkkkkkkKKkkkkkkkkkK.....",
  "....KkkkkkkkkkkKKkkkkkkkkkkK....",
  "....KkkkkkkkkkkKKkkkkkkkkkkK....",
  "...KkkkkkkkkkkkKKkkkkkkkkkkkK...",
  "...KKKKKKKKKKKKKKKKKKKKKKKKKK...",
  "................................",
];

const LICH_W: string[] = [
  "..........KpK.KppK.KpK..........",
  "..........KppKppppKppK..........",
  "..........KppppppppppK..........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KkkkkkkkKKkkkkkkkK.......",
  "......KkkKwwwwwwwwwwwwKkkK......",
  "......KkKwwwwwwwwwwwwwwKkK......",
  "......KkKwKKwwwwwwwwKKwKkK......",
  "......KkKwKrKwwwwwwKrKwKkK......",
  "......KkKwwwwwwwwwwwwwwKkK......",
  "......KkkKwwKKKwwKKKwwKkkK......",
  ".....KkkkkKwwwwwwwwwwKkkkkK.....",
  "....KkkkkkkKKKKKKKKKKkkkkkkK....",
  "...KkkkkkkkkpppPPpppkkkkkkkkK...",
  "...KkkkkkkkppPppppPppkkkkkkkK...",
  "..KkkKkkkkppppppppppppkkkkKkkK..",
  "..KkK.KkkkkpppPppPpppkkkkK.KkK..",
  ".KkK..KkkkkppppPPppppkkkkK..KkK.",
  ".KwK..KkkkkkpppPPpppkkkkkK..KwK.",
  ".KwwK.KkkkkkpppPPpppkkkkkK.KwwK.",
  "..KK..KkkkkkkppppppkkkkkkK..KK..",
  "......KkkkkkkkppppkkkkkkkK......",
  ".....KkkkkkkkkkppkkkkkkkkkK.....",
  ".....KkkkkkkkkkKKkkkkkkkkkK.....",
  "....KkkkkkkkkkkKKkkkkkkkkkkK....",
  "....KkkkkkkkkkkKKkkkkkkkkkkK....",
  "...KkkkkkkkkkkkKKkkkkkkkkkkkK...",
  "...KKKKKKKKKKKKKKKKKKKKKKKKKK...",
  "................................",
  "................................",
  "................................",
  "................................",
];

export const DUSKHOLD: RealmSprites = {
  realm: 'duskhold',
  palette: [OUTLINE, '#b07cff', '#e9e0ff', '#ffd23f', '#6a6a8a', '#8a8aaa', '#3a2a5a', '#e8434f', '#5a3a2a'],
  ground: 10,
  sprites: {
    book: { frames: [BOOK1, BOOK2], pal: { K: OUTLINE, p: '#8a4a6a', w: '#fff4e0' } },
    lantern: { frames: [LANTERN1, LANTERN2], pal: { K: OUTLINE, w: '#e9e0ff', g: '#5a3a2a', y: '#ffd23f', Y: '#fff4b0' } },
    harmor: { frames: [HARMOR], pal: { K: OUTLINE, a: '#6a6a8a', A: '#b07cff', r: '#b07cff' } },
    bossL: { frames: [LICH_A, LICH_B, LICH_W], pal: { K: OUTLINE, k: '#3a2a5a', w: '#e9e0ff', r: '#e8434f', p: '#b07cff', P: '#e0c8ff' }, note: 'Lich Queen 32×32 (idle ×2, wind-up)' },
  },
};
