// Emberforge (volcano, fire): fire bat, salamander, lava rock, Magma King.
// Tickets 36–38 art: drafts for the owner's review in the Sprite Lab.
import { OUTLINE, type RealmSprites } from '../types';
import { BAT1, BAT2 } from './greenvale';

const SALA1: string[] = [
  "..........KKKK..",
  ".........KooooK.",
  "..K.....KoYKooK.",
  ".KoK...KoooooK..",
  "KooKKKKoooooK...",
  "KoyyyooooooK....",
  ".KoooooooooK....",
  "..KKoKKKoKK.....",
  "...KoK.KoK......",
  "...KK..KK.......",
];

const SALA2: string[] = [
  "..........KKKK..",
  ".........KooooK.",
  "..K.....KoYKooK.",
  ".KoK...KoooooK..",
  "KooKKKKoooooK...",
  "KoyyyooooooK....",
  ".KoooooooooK....",
  "..KKoKKKoKK.....",
  "....KoK.KoK.....",
  "....KK..KK......",
];

const LAVAROCK: string[] = [
  "....KKKKKK....",
  "..KKrRRrrrKK..",
  ".KrRRrrorrrrK.",
  ".KrRrrooorrrK.",
  "KrrrrroYorrrrK",
  "KrKKrrrorrKKrK",
  "KrKYKrrrrKYKrK",
  "KrrrrrrrrrrrrK",
  "KrroorrrrrrorK",
  ".KrrorrrroorK.",
  "..KKrrrrrrKK..",
  "....KKKKKK....",
];

const MAGMA_A: string[] = [
  "................................",
  "..........K....KK....K..........",
  ".........KYK..KYYK..KYK.........",
  ".........KYYKKYYYYKKYYK.........",
  ".........KYYYYYYYYYYYYK.........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KrrrrrrrRRrrrrrrrK.......",
  "......KrrRrrrrrrrrrrrrRrrK......",
  "......KrRrrrrrrrrrrrrrrRrK......",
  "......KrrKKKrrrrrrrrKKKrrK......",
  "......KrKYYoKrrrrrrKoYYKrK......",
  "......KrrKKKrrrrrrrrKKKrrK......",
  "......KrrrrrrKKKKKKrrrrrrK......",
  ".......KrrrrKooooooKrrrrK.......",
  "....KKKKKrrrrKKKKKKrrrrKKKKK....",
  "...KrrrrrKrrrrrrrrrrrrKrrrrrK...",
  "..KrRRrrrrKrroorroorrKrrrrRRrK..",
  "..KrRrrKrrrKoYYooYYoKrrrKrrRrK..",
  ".KrrrrKKrrrKoYYYYYYoKrrrKKrrrrK.",
  ".KrrrK.KrrrKooYYYYooKrrrK.KrrrK.",
  ".KrrK..KrrrrKooooooKrrrrK..KrrK.",
  ".KrrK..KrrrrrKKKKKKrrrrrK..KrrK.",
  "KooK...KrrrrrrrKKrrrrrrrK...KooK",
  "KoYoK..KrrrrrrrKKrrrrrrrK..KoYoK",
  "KooYK..KrrrorrrKKrrrorrrK..KYooK",
  ".KKK...KrrroorrKKrroorrrK...KKK.",
  ".......KrrrrrrrKKrrrrrrrK.......",
  "........KrrrrrrKKrrrrrrK........",
  "........KrrrKKKKKKKKrrrK........",
  ".......KrrrK........KrrrK.......",
  "......KrroK..........KorrK......",
  "......KKKKK..........KKKKK......",
];

const MAGMA_B: string[] = [
  "................................",
  "................................",
  "..........K....KK....K..........",
  ".........KYK..KYYK..KYK.........",
  ".........KYYKKYYYYKKYYK.........",
  ".........KYYYYYYYYYYYYK.........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KrrrrrrrRRrrrrrrrK.......",
  "......KrrRrrrrrrrrrrrrRrrK......",
  "......KrRrrrrrrrrrrrrrrRrK......",
  "......KrrKKKrrrrrrrrKKKrrK......",
  "......KrKYYoKrrrrrrKoYYKrK......",
  "......KrrKKKrrrrrrrrKKKrrK......",
  "......KrrrrrrKKKKKKrrrrrrK......",
  ".......KrrrrKooooooKrrrrK.......",
  "....KKKKKrrrrKKKKKKrrrrKKKKK....",
  "...KrrrrrKrrrrrrrrrrrrKrrrrrK...",
  "..KrRRrrrrKrroorroorrKrrrrRRrK..",
  "..KrRrrKrrrKoYYooYYoKrrrKrrRrK..",
  ".KrrrrKKrrrKoYYYYYYoKrrrKKrrrrK.",
  ".KrrrK.KrrrKooYYYYooKrrrK.KrrrK.",
  ".KrrK..KrrrrKooooooKrrrrK..KrrK.",
  ".KrrK..KrrrrrKKKKKKrrrrrK..KrrK.",
  "KooK...KrrrrrrrKKrrrrrrrK...KooK",
  "KoYoK..KrrrrrrrKKrrrrrrrK..KoYoK",
  "KooYK..KrrrorrrKKrrrorrrK..KYooK",
  ".KKK...KrrroorrKKrroorrrK...KKK.",
  ".......KrrrrrrrKKrrrrrrrK.......",
  "........KrrrrrrKKrrrrrrK........",
  "........KrrrKKKKKKKKrrrK........",
  ".......KrrrK........KrrrK.......",
  "......KrroK..........KorrK......",
];

const MAGMA_W: string[] = [
  ".........KYK..KYYK..KYK.........",
  ".........KYYKKYYYYKKYYK.........",
  ".........KYYYYYYYYYYYYK.........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KrrrrrrrRRrrrrrrrK.......",
  "......KrrRrrrrrrrrrrrrRrrK......",
  "......KrRrrrrrrrrrrrrrrRrK......",
  "......KrrKKKrrrrrrrrKKKrrK......",
  "......KrKYYoKrrrrrrKoYYKrK......",
  "......KrrKKKrrrrrrrrKKKrrK......",
  "......KrrrrrrKKKKKKrrrrrrK......",
  ".......KrrrrKooooooKrrrrK.......",
  "....KKKKKrrrrKKKKKKrrrrKKKKK....",
  "...KrrrrrKrrrrrrrrrrrrKrrrrrK...",
  "..KrRRrrrrKrroorroorrKrrrrRRrK..",
  "..KrRrrKrrrKoYYooYYoKrrrKrrRrK..",
  ".KrrrrKKrrrKoYYYYYYoKrrrKKrrrrK.",
  ".KrrrK.KrrrKooYYYYooKrrrK.KrrrK.",
  ".KrrK..KrrrrKooooooKrrrrK..KrrK.",
  ".KrrK..KrrrrrKKKKKKrrrrrK..KrrK.",
  "KooK...KrrrrrrrKKrrrrrrrK...KooK",
  "KoYoK..KrrrrrrrKKrrrrrrrK..KoYoK",
  "KooYK..KrrrorrrKKrrrorrrK..KYooK",
  ".KKK...KrrroorrKKrroorrrK...KKK.",
  ".......KrrrrrrrKKrrrrrrrK.......",
  "........KrrrrrrKKrrrrrrK........",
  "........KrrrKKKKKKKKrrrK........",
  ".......KrrrK........KrrrK.......",
  "......KrroK..........KorrK......",
  "......KKKKK..........KKKKK......",
  "................................",
  "................................",
];

export const EMBERFORGE: RealmSprites = {
  realm: 'emberforge',
  palette: [OUTLINE, '#ff6a2a', '#ffd23f', '#ff8a3d', '#5a3a3a', '#7a4a3a', '#d8342c', '#3a2424'],
  ground: 5,
  sprites: {
    fbat: { frames: [BAT1, BAT2], pal: { K: OUTLINE, p: '#d8342c', r: '#ffd23f' } },
    sala: { frames: [SALA1, SALA2], pal: { K: OUTLINE, o: '#ff8a3d', y: '#ffd23f', Y: '#fff4e0' } },
    lavarock: { frames: [LAVAROCK], pal: { K: OUTLINE, r: '#5a3a3a', R: '#7a5a4a', o: '#ff6a2a', Y: '#ffd23f' } },
    bossE: { frames: [MAGMA_A, MAGMA_B, MAGMA_W], pal: { K: OUTLINE, r: '#6a3a2a', R: '#8a5a3a', o: '#ff6a2a', Y: '#ffd23f' }, note: 'Magma King 32×32 (idle ×2, wind-up)' },
  },
};
