// Frostpeak (snow): ice slime, ice bat, snowman, Frost King.
import { OUTLINE, type RealmSprites } from '../types';
import { SLIME } from './common';
import { BAT1, BAT2 } from './greenvale';
const SNOWM: string[] = [
  "....KKKK....",
  "...KwwwwK...",
  "..KwKwwKwK..",
  "..KwwoowwK..",
  "...KwwwwK...",
  "..KKrrrrKK..",
  ".KwwwwwwwwK.",
  "KwwwwKwwwwwK",
  "KwwwwwwwwwwK",
  "KwwwwKwwwwwK",
  ".KwwwwwwwwK.",
  "..KKKKKKKK..",
];

const KFROST_A: string[] = [
  "................................",
  "..........K....KK....K..........",
  ".........KcK..KccK..KcK.........",
  ".........KccK.KccK.KccK.........",
  ".........KccKKccccKKccK.........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KwwwwwwwWWwwwwwwwK.......",
  "......KwwKKwwwwwwwwwwKKwwK......",
  "......KwKbbKwwwwwwwwKbbKwK......",
  "......KwwKKwwwwwwwwwwKKwwK......",
  "......KwwwwwwKooooKwwwwwwK......",
  "......KwwwwwwwKooKwwwwwwwK......",
  ".......KwwwwwwwKKwwwwwwwK.......",
  "........KKwwwwwwwwwwwwKK........",
  "......KKccKKKKKKKKKKKKccKK......",
  ".....KcccccKwwwwwwwwKcccccK.....",
  "....KcCCcccKwwwwwwwwKcccCCcK....",
  "...KcCcccccKwwwwwwwwKcccccCcK...",
  "...KccKcccKwwwwwwwwwwKcccKccK...",
  "..KccK.KcKwwwwwWWwwwwwKcK.KccK..",
  "..KcK..KcKwwwwwWWwwwwwKcK..KcK..",
  ".KcK..KwwwwwwwwWWwwwwwwwwK..KcK.",
  ".KwK..KwwwwwwwWWWWwwwwwwwK..KwK.",
  "KwwwK.KwwwwwwwWWWWwwwwwwwK.KwwwK",
  "KwwwK.KwwwwwwWWWWWWwwwwwwK.KwwwK",
  ".KKK...KwwwwwWWWWWWwwwwwK...KKK.",
  "........KwwwwwWWWWwwwwwK........",
  "........KKwwwwwwwwwwwwKK........",
  "..........KKKKKKKKKKKK..........",
  "................................",
  "................................",
  "................................",
];

const KFROST_B: string[] = [
  "................................",
  "................................",
  "..........K....KK....K..........",
  ".........KcK..KccK..KcK.........",
  ".........KccK.KccK.KccK.........",
  ".........KccKKccccKKccK.........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KwwwwwwwWWwwwwwwwK.......",
  "......KwwKKwwwwwwwwwwKKwwK......",
  "......KwKbbKwwwwwwwwKbbKwK......",
  "......KwwKKwwwwwwwwwwKKwwK......",
  "......KwwwwwwKooooKwwwwwwK......",
  "......KwwwwwwwKooKwwwwwwwK......",
  ".......KwwwwwwwKKwwwwwwwK.......",
  "........KKwwwwwwwwwwwwKK........",
  "......KKccKKKKKKKKKKKKccKK......",
  ".....KcccccKwwwwwwwwKcccccK.....",
  "....KcCCcccKwwwwwwwwKcccCCcK....",
  "...KcCcccccKwwwwwwwwKcccccCcK...",
  "...KccKcccKwwwwwwwwwwKcccKccK...",
  "..KccK.KcKwwwwwWWwwwwwKcK.KccK..",
  "..KcK..KcKwwwwwWWwwwwwKcK..KcK..",
  ".KcK..KwwwwwwwwWWwwwwwwwwK..KcK.",
  ".KwK..KwwwwwwwWWWWwwwwwwwK..KwK.",
  "KwwwK.KwwwwwwwWWWWwwwwwwwK.KwwwK",
  "KwwwK.KwwwwwwWWWWWWwwwwwwK.KwwwK",
  ".KKK...KwwwwwWWWWWWwwwwwK...KKK.",
  "........KwwwwwWWWWwwwwwK........",
  "........KKwwwwwwwwwwwwKK........",
  "..........KKKKKKKKKKKK..........",
  "................................",
  "................................",
];

const KFROST_W: string[] = [
  ".........KcK..KccK..KcK.........",
  ".........KccK.KccK.KccK.........",
  ".........KccKKccccKKccK.........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KwwwwwwwWWwwwwwwwK.......",
  "......KwwKKwwwwwwwwwwKKwwK......",
  "......KwKbbKwwwwwwwwKbbKwK......",
  "......KwwKKwwwwwwwwwwKKwwK......",
  "......KwwwwwwKooooKwwwwwwK......",
  "......KwwwwwwwKooKwwwwwwwK......",
  ".......KwwwwwwwKKwwwwwwwK.......",
  "........KKwwwwwwwwwwwwKK........",
  "......KKccKKKKKKKKKKKKccKK......",
  ".....KcccccKwwwwwwwwKcccccK.....",
  "....KcCCcccKwwwwwwwwKcccCCcK....",
  "...KcCcccccKwwwwwwwwKcccccCcK...",
  "...KccKcccKwwwwwwwwwwKcccKccK...",
  "..KccK.KcKwwwwwWWwwwwwKcK.KccK..",
  "..KcK..KcKwwwwwWWwwwwwKcK..KcK..",
  ".KcK..KwwwwwwwwWWwwwwwwwwK..KcK.",
  ".KwK..KwwwwwwwWWWWwwwwwwwK..KwK.",
  "KwwwK.KwwwwwwwWWWWwwwwwwwK.KwwwK",
  "KwwwK.KwwwwwwWWWWWWwwwwwwK.KwwwK",
  ".KKK...KwwwwwWWWWWWwwwwwK...KKK.",
  "........KwwwwwWWWWwwwwwK........",
  "........KKwwwwwwwwwwwwKK........",
  "..........KKKKKKKKKKKK..........",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
];

export const FROSTPEAK: RealmSprites = {
  realm: 'frostpeak',
  palette: [OUTLINE, '#8fd8ff', '#ffffff', '#3f7fbf', '#5cc8e8', '#f4fbff', '#ff8a3d', '#e8434f', '#e6f6ff', '#4fa8ff', '#ffd23f'],
  ground: 3,
  sprites: {
    islime: { frames: [SLIME], pal: { K: OUTLINE, g: '#8fd8ff', G: '#ffffff', d: '#3f7fbf' } },
    ibat: { frames: [BAT1, BAT2], pal: { K: OUTLINE, p: '#5cc8e8', r: '#ffffff' } },
    snowman: { frames: [SNOWM], pal: { K: OUTLINE, w: '#f4fbff', o: '#ff8a3d', r: '#e8434f' } },
    bossS: { frames: [KFROST_A, KFROST_B, KFROST_W], pal: { K: OUTLINE, w: '#f4fbff', W: '#c8e0f0', c: '#8fd8ff', C: '#dff4ff', b: '#3f7fbf', o: '#ff8a3d' }, note: 'Frost King 32×32 (idle ×2, wind-up) — draft for review' },
  },
};
