// Gearspire (clockwork city, lightning): iron spider, turret, clockwork soldier, Golem King.
// Tickets 36–38 art: drafts for the owner's review in the Sprite Lab.
import { OUTLINE, type RealmSprites } from '../types';

const SPIDER1: string[] = [
  "K..K......K..K",
  ".K..K....K..K.",
  "..K..KKKK..K..",
  "KKKKKmmmmKKKKK",
  "...KmMmmmmK...",
  "KKKKmrmmrmKKKK",
  "...KmmmmmmK...",
  "..K.KKKKKK.K..",
  ".K..K....K..K.",
  "K...K....K...K",
];

const SPIDER2: string[] = [
  "...K......K...",
  "..K..K..K..K..",
  ".K...KKKK...K.",
  "KKKKKmmmmKKKKK",
  "...KmMmmmmK...",
  "KKKKmrmmrmKKKK",
  "...KmmmmmmK...",
  ".K..KKKKKK..K.",
  "..K..K..K..K..",
  "...K......K...",
];

const TURRET: string[] = [
  "......KK......",
  ".....KmmK.....",
  "....KmrrmK....",
  "...KmmrrmmK...",
  "KKKKmmmmmmKKKK",
  "KsssKmmmmKsssK",
  "KKKKmmMmmmKKKK",
  "..KmmmmmmmmK..",
  ".KmMmmmmmmmmK.",
  ".KmmmmmmmmmmK.",
  "KKKKKKKKKKKKKK",
];

const MECH1: string[] = [
  "....KKKKKK....",
  "...KmmmmmmK...",
  "...KmrrrrmK...",
  "...KmmmmmmK...",
  "..KKKKKKKKKK..",
  ".KmmKMMMMKmmK.",
  ".KmKmMyyMmKmK.",
  ".KmKmMyyMmKmK.",
  ".KmKmmmmmmKmK.",
  ".KKKKmmmmKKKK.",
  "....KmKKmK....",
  "....KmK.KmK...",
  "...KKK...KKK..",
];

const MECH2: string[] = [
  "....KKKKKK....",
  "...KmmmmmmK...",
  "...KmrrrrmK...",
  "...KmmmmmmK...",
  "..KKKKKKKKKK..",
  ".KmmKMMMMKmmK.",
  ".KmKmMyyMmKmK.",
  ".KmKmMyyMmKmK.",
  ".KmKmmmmmmKmK.",
  ".KKKKmmmmKKKK.",
  "....KmKKmK....",
  "...KmK..KmK...",
  "...KKK..KKK...",
];

const GOLEM_A: string[] = [
  "................................",
  "...........KK......KK...........",
  "..........KrrK....KrrK..........",
  "..........KrrK....KrrK..........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KmmmmmmmMMmmmmmmmK.......",
  ".......KmKKKKKKKKKKKKKKmK.......",
  ".......KmKrrrrrrrrrrrrKmK.......",
  ".......KmKrrKKrrrrKKrrKmK.......",
  ".......KmKKKKKKKKKKKKKKmK.......",
  ".......KmmmmmmmMMmmmmmmmK.......",
  "........KKKKKKKKKKKKKKKK........",
  "...KKKKKmmmmmmmmmmmmmmmmKKKKK...",
  "..KmmmmKmMMmmmmmmmmmmMMmKmmmmK..",
  ".KmMmmmKmMmmmyyyyyymmmMmKmmmMmK.",
  ".KmmmmmKmmmmyYYyyYYymmmmKmmmmmK.",
  ".KmmmmKKmmmmyYYyyYYymmmmKKmmmmK.",
  ".KmmmK.KmmmmmyyKKyymmmmmK.KmmmK.",
  ".KmmmK.KmmmmmmmMMmmmmmmmK.KmmmK.",
  ".KmmK..KMmmmmmmMMmmmmmmMK..KmmK.",
  "KmmmmK.KmMmmmmmMMmmmmmMmK.KmmmmK",
  "KmrrmK.KmmmmmmmMMmmmmmmmK.KmrrmK",
  "KmmmmK..KmmmmmmMMmmmmmmK..KmmmmK",
  ".KKKK...KKKKKKKKKKKKKKKK...KKKK.",
  "........KmmmK......KmmmK........",
  "........KmmmK......KmmmK........",
  ".......KmmmmK......KmmmmK.......",
  "......KmMmmmK......KmmmMmK......",
  "......KmmmmmK......KmmmmmK......",
  ".....KKKKKKKK......KKKKKKKK.....",
  "................................",
  "................................",
];

const GOLEM_B: string[] = [
  "................................",
  "................................",
  "...........KK......KK...........",
  "..........KrrK....KrrK..........",
  "..........KrrK....KrrK..........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KmmmmmmmMMmmmmmmmK.......",
  ".......KmKKKKKKKKKKKKKKmK.......",
  ".......KmKrrrrrrrrrrrrKmK.......",
  ".......KmKrrKKrrrrKKrrKmK.......",
  ".......KmKKKKKKKKKKKKKKmK.......",
  ".......KmmmmmmmMMmmmmmmmK.......",
  "........KKKKKKKKKKKKKKKK........",
  "...KKKKKmmmmmmmmmmmmmmmmKKKKK...",
  "..KmmmmKmMMmmmmmmmmmmMMmKmmmmK..",
  ".KmMmmmKmMmmmyyyyyymmmMmKmmmMmK.",
  ".KmmmmmKmmmmyYYyyYYymmmmKmmmmmK.",
  ".KmmmmKKmmmmyYYyyYYymmmmKKmmmmK.",
  ".KmmmK.KmmmmmyyKKyymmmmmK.KmmmK.",
  ".KmmmK.KmmmmmmmMMmmmmmmmK.KmmmK.",
  ".KmmK..KMmmmmmmMMmmmmmmMK..KmmK.",
  "KmmmmK.KmMmmmmmMMmmmmmMmK.KmmmmK",
  "KmrrmK.KmmmmmmmMMmmmmmmmK.KmrrmK",
  "KmmmmK..KmmmmmmMMmmmmmmK..KmmmmK",
  ".KKKK...KKKKKKKKKKKKKKKK...KKKK.",
  "........KmmmK......KmmmK........",
  "........KmmmK......KmmmK........",
  ".......KmmmmK......KmmmmK.......",
  "......KmMmmmK......KmmmMmK......",
  "......KmmmmmK......KmmmmmK......",
  ".....KKKKKKKK......KKKKKKKK.....",
  "................................",
];

const GOLEM_W: string[] = [
  "..........KrrK....KrrK..........",
  "..........KrrK....KrrK..........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KmmmmmmmMMmmmmmmmK.......",
  ".......KmKKKKKKKKKKKKKKmK.......",
  ".......KmKrrrrrrrrrrrrKmK.......",
  ".......KmKrrKKrrrrKKrrKmK.......",
  ".......KmKKKKKKKKKKKKKKmK.......",
  ".......KmmmmmmmMMmmmmmmmK.......",
  "........KKKKKKKKKKKKKKKK........",
  "...KKKKKmmmmmmmmmmmmmmmmKKKKK...",
  "..KmmmmKmMMmmmmmmmmmmMMmKmmmmK..",
  ".KmMmmmKmMmmmyyyyyymmmMmKmmmMmK.",
  ".KmmmmmKmmmmyYYyyYYymmmmKmmmmmK.",
  ".KmmmmKKmmmmyYYyyYYymmmmKKmmmmK.",
  ".KmmmK.KmmmmmyyKKyymmmmmK.KmmmK.",
  ".KmmmK.KmmmmmmmMMmmmmmmmK.KmmmK.",
  ".KmmK..KMmmmmmmMMmmmmmmMK..KmmK.",
  "KmmmmK.KmMmmmmmMMmmmmmMmK.KmmmmK",
  "KmrrmK.KmmmmmmmMMmmmmmmmK.KmrrmK",
  "KmmmmK..KmmmmmmMMmmmmmmK..KmmmmK",
  ".KKKK...KKKKKKKKKKKKKKKK...KKKK.",
  "........KmmmK......KmmmK........",
  "........KmmmK......KmmmK........",
  ".......KmmmmK......KmmmmK.......",
  "......KmMmmmK......KmmmMmK......",
  "......KmmmmmK......KmmmmmK......",
  ".....KKKKKKKK......KKKKKKKK.....",
  "................................",
  "................................",
  "................................",
  "................................",
];

export const GEARSPIRE: RealmSprites = {
  realm: 'gearspire',
  palette: [OUTLINE, '#8a94a8', '#c7ced9', '#6a7488', '#e8434f', '#ffd23f', '#b8c0cc', '#4a5468'],
  ground: 9,
  sprites: {
    spider: { frames: [SPIDER1, SPIDER2], pal: { K: OUTLINE, m: '#8a94a8', M: '#c7ced9', r: '#e8434f' } },
    turret: { frames: [TURRET], pal: { K: OUTLINE, m: '#8a94a8', M: '#c7ced9', r: '#e8434f', s: '#4a5468' } },
    mech: { frames: [MECH1, MECH2], pal: { K: OUTLINE, m: '#6a7488', M: '#b8c0cc', r: '#ffd23f', y: '#ffd23f' } },
    bossG: { frames: [GOLEM_A, GOLEM_B, GOLEM_W], pal: { K: OUTLINE, m: '#8a94a8', M: '#c7ced9', r: '#e8434f', y: '#ffd23f', Y: '#fff4b0' }, note: 'Golem King 32×32 (idle ×2, wind-up)' },
  },
};
