// Mirefen (swamp, poison): poison frog, spore cap, giant leech, Bog Queen.
// Tickets 36–38 art: drafts for the owner's review in the Sprite Lab.
import { OUTLINE, type RealmSprites } from '../types';
import { MUSH } from './greenvale';

const FROG1: string[] = [
  "..KK......KK..",
  ".KwwK....KwwK.",
  ".KwKgKKKKgKwK.",
  "..KggggggggK..",
  ".KgGGggggGGgK.",
  "KggggKKKKggggK",
  "KgpgggggggggpK",
  ".KggppggggggK.",
  "KgK.KKKKKK.KgK",
  "KK..........KK",
];

const FROG2: string[] = [
  "..KK......KK..",
  ".KwwK....KwwK.",
  ".KwKgKKKKgKwK.",
  "..KggggggggK..",
  ".KgGGggggGGgK.",
  "KggggKKKKggggK",
  "KgpgggggggggpK",
  ".KggppggggggK.",
  ".KgK......KgK.",
  "KgK........KgK",
];

const SPORELET: string[] = [
  "..KKKK..",
  ".KppwpK.",
  "KpwpppwK",
  "KKKKKKKK",
  ".KsssK..",
  ".KsKsK..",
  "..K.K...",
];

const LEECH: string[] = [
  "....KKKKKKKK....",
  "..KKllLLllllKK..",
  ".KllLLllllllllK.",
  "KrrKllllllllllK.",
  "KrKrKllllllllllK",
  "KrrKlllllllllllK",
  ".KKlldlldlldllK.",
  "..KKllllllllKK..",
  "....KKKKKKKK....",
];

const BOG_A: string[] = [
  "................................",
  "................................",
  "...........K...KK...K...........",
  "..........KYK.KYYK.KYK..........",
  "..........KYYKYYYYKYYK..........",
  "..........KYYYYYYYYYYK..........",
  "........KKKKKKKKKKKKKKKK........",
  "......KKggggggGGGGggggggKK......",
  ".....KgggggGGggggggGGgggggK.....",
  "....KggggGGggggggggggGGggggK....",
  "...KgKwwwKggggggggggggKwwwKgK...",
  "...KgKwKwKggggggggggggKwKwKgK...",
  "...KgKwwwKggggggggggggKwwwKgK...",
  "...KggKKKggggggggggggggKKKggK...",
  "...KggggggggggggggggggggggggK...",
  "...KgpggggggggggggggggggggpgK...",
  "...KggggKKKKKKKKKKKKKKKKggggK...",
  "....KggggggggggggggggggggggK....",
  "....KKggggggggggggggggggggKK....",
  "...KggpggggggGGGGGGggggggpggK...",
  "..KggggggggGGGGGGGGGGggggggggK..",
  ".KgggpggggGGGGGGGGGGGGggggpgggK.",
  ".KggggggggGGGGGGGGGGGGggggggggK.",
  "KggKggggggGGGGGGGGGGGGggggggKggK",
  "KgKKggggggGGGGGGGGGGGGggggggKKgK",
  "KgK.KgggggGGGGGGGGGGGGgggggK.KgK",
  ".K..KggggggGGGGGGGGGGggggggK..K.",
  "....KgggggggGGGGGGGGgggggggK....",
  "....KKggggggggggggggggggggKK....",
  "...KggKKKKKKKKKKKKKKKKKKKKggK...",
  "..KgggK..................KgggK..",
  "..KKKKK..................KKKKK..",
];

const BOG_B: string[] = [
  "................................",
  "................................",
  "................................",
  "...........K...KK...K...........",
  "..........KYK.KYYK.KYK..........",
  "..........KYYKYYYYKYYK..........",
  "..........KYYYYYYYYYYK..........",
  "........KKKKKKKKKKKKKKKK........",
  "......KKggggggGGGGggggggKK......",
  ".....KgggggGGggggggGGgggggK.....",
  "....KggggGGggggggggggGGggggK....",
  "...KgKwwwKggggggggggggKwwwKgK...",
  "...KgKwKwKggggggggggggKwKwKgK...",
  "...KgKwwwKggggggggggggKwwwKgK...",
  "...KggKKKggggggggggggggKKKggK...",
  "...KggggggggggggggggggggggggK...",
  "...KgpggggggggggggggggggggpgK...",
  "...KggggKKKKKKKKKKKKKKKKggggK...",
  "....KggggggggggggggggggggggK....",
  "....KKggggggggggggggggggggKK....",
  "...KggpggggggGGGGGGggggggpggK...",
  "..KggggggggGGGGGGGGGGggggggggK..",
  ".KgggpggggGGGGGGGGGGGGggggpgggK.",
  ".KggggggggGGGGGGGGGGGGggggggggK.",
  "KggKggggggGGGGGGGGGGGGggggggKggK",
  "KgKKggggggGGGGGGGGGGGGggggggKKgK",
  "KgK.KgggggGGGGGGGGGGGGgggggK.KgK",
  ".K..KggggggGGGGGGGGGGggggggK..K.",
  "....KgggggggGGGGGGGGgggggggK....",
  "....KKggggggggggggggggggggKK....",
  "...KggKKKKKKKKKKKKKKKKKKKKggK...",
  "..KgggK..................KgggK..",
];

const BOG_W: string[] = [
  "...........K...KK...K...........",
  "..........KYK.KYYK.KYK..........",
  "..........KYYKYYYYKYYK..........",
  "..........KYYYYYYYYYYK..........",
  "........KKKKKKKKKKKKKKKK........",
  "......KKggggggGGGGggggggKK......",
  ".....KgggggGGggggggGGgggggK.....",
  "....KggggGGggggggggggGGggggK....",
  "...KgKwwwKggggggggggggKwwwKgK...",
  "...KgKwKwKggggggggggggKwKwKgK...",
  "...KgKwwwKggggggggggggKwwwKgK...",
  "...KggKKKggggggggggggggKKKggK...",
  "...KggggggggggggggggggggggggK...",
  "...KgpggggggggggggggggggggpgK...",
  "...KggggKKKKKKKKKKKKKKKKggggK...",
  "....KggggggggggggggggggggggK....",
  "....KKggggggggggggggggggggKK....",
  "...KggpggggggGGGGGGggggggpggK...",
  "..KggggggggGGGGGGGGGGggggggggK..",
  ".KgggpggggGGGGGGGGGGGGggggpgggK.",
  ".KggggggggGGGGGGGGGGGGggggggggK.",
  "KggKggggggGGGGGGGGGGGGggggggKggK",
  "KgKKggggggGGGGGGGGGGGGggggggKKgK",
  "KgK.KgggggGGGGGGGGGGGGgggggK.KgK",
  ".K..KggggggGGGGGGGGGGggggggK..K.",
  "....KgggggggGGGGGGGGgggggggK....",
  "....KKggggggggggggggggggggKK....",
  "...KggKKKKKKKKKKKKKKKKKKKKggK...",
  "..KgggK..................KgggK..",
  "..KKKKK..................KKKKK..",
  "................................",
  "................................",
];

export const MIREFEN: RealmSprites = {
  realm: 'mirefen',
  palette: [OUTLINE, '#6fb553', '#b6f24a', '#b36bd8', '#f0d8ff', '#6b3a5a', '#8a4a6a', '#ffd23f', '#e8434f'],
  ground: 6,
  sprites: {
    frog: { frames: [FROG1, FROG2], pal: { K: OUTLINE, g: '#6fb553', G: '#b6f24a', w: '#fff4e0', p: '#b36bd8' } },
    spore: { frames: [MUSH], pal: { K: OUTLINE, r: '#b36bd8', w: '#f0d8ff', s: '#e8d8c8', b: '#6b3e26' } },
    sporelet: { frames: [SPORELET], pal: { K: OUTLINE, p: '#b36bd8', w: '#f0d8ff', s: '#e8d8c8' } },
    leech: { frames: [LEECH], pal: { K: OUTLINE, l: '#6b3a5a', L: '#9a5a7a', d: '#4a2a3a', r: '#e8434f' } },
    bossM: { frames: [BOG_A, BOG_B, BOG_W], pal: { K: OUTLINE, g: '#5f9a3a', G: '#b6d88a', w: '#fff4e0', p: '#b36bd8', Y: '#ffd23f' }, note: 'Bog Queen 32×32 (idle ×2, wind-up)' },
  },
};
