// Skyreach Isles (floating islands, lightning): cloud wisp, storm bird, griffin chick, Storm King.
// Tickets 36–38 art: drafts for the owner's review in the Sprite Lab.
import { OUTLINE, type RealmSprites } from '../types';

const CLOUD1: string[] = [
  "....KKKK......",
  "..KKwwwwKKKK..",
  ".KwwwwwwwwwwK.",
  "KwwWwwwwwwwwwK",
  "KwwKwwwwKwwwwK",
  "KwwwwwwwwwwwwK",
  ".KwwwwwwwwwwK.",
  "..KKbKKbKKbK..",
  "...b...b...b..",
];

const CLOUD2: string[] = [
  "....KKKK......",
  "..KKwwwwKKKK..",
  ".KwwwwwwwwwwK.",
  "KwwWwwwwwwwwwK",
  "KwwKwwwwKwwwwK",
  "KwwwwwwwwwwwwK",
  ".KwwwwwwwwwwK.",
  "..KKbKKbKKbK..",
  "..b...b...b...",
];

const SBIRD1: string[] = [
  "KK..........KK",
  "KyK........KyK",
  ".KyyK.KK.KyyK.",
  "..KyyKyyKyyK..",
  "...KyyYYyyK...",
  "....KyKKyK....",
  ".....KooK.....",
  "......KK......",
];

const SBIRD2: string[] = [
  "..............",
  "......KK......",
  ".....KyyK.....",
  "..KKKyyyyKKK..",
  ".KyyyYyyYyyyK.",
  "KyyK.KyyK.KyyK",
  "KK...KooK...KK",
  "......KK......",
];

const GRIFFIN1: string[] = [
  "...KKK..........",
  "..KwwwK.........",
  ".KwwKwK...KKK...",
  "KoKwwwwK.KyyyK..",
  ".KKwwwwKKyyyyyK.",
  "...KwwyyyyyyyyyK",
  "...KyyyyyyyyyyK.",
  "...KyyyyyyyyyyK.",
  "...KyyKKKKyyyyK.",
  "...KyK....KyK.KK",
  "...KK.....KK....",
];

const GRIFFIN2: string[] = [
  "...KKK..........",
  "..KwwwK.........",
  ".KwwKwK...KKK...",
  "KoKwwwwK.KyyyK..",
  ".KKwwwwKKyyyyyK.",
  "...KwwyyyyyyyyyK",
  "...KyyyyyyyyyyK.",
  "...KyyyyyyyyyyK.",
  "...KyyKKKKyyyyK.",
  "....KyK..KyK..KK",
  "....KK...KK.....",
];

const STORM_A: string[] = [
  "................................",
  "..........K....KK....K..........",
  ".........KYK..KYYK..KYK.........",
  ".........KYYKKYYYYKKYYK.........",
  "........KKKKKKKKKKKKKKKK........",
  "........KsssssSssSsssssK........",
  "........KsKKKssssssKKKsK........",
  "........KsKbKssssssKbKsK........",
  "........Kssssss..ssssssK........",
  ".......KwwsssssssssssswwK.......",
  ".......KwwwwKKKKKKKKwwwwK.......",
  "KK.....KwwwwwwwYYwwwwwwwK.....KK",
  "KcK...KKwwwwwwYYYYwwwwwwKK...KcK",
  "KccK.KbbKwwwwwwYYwwwwwwKbbK.KccK",
  "KcccKbbbbKwwwwwYYwwwwwKbbbbKcccK",
  ".KcccKbbbbKwwwwYYwwwwKbbbbKcccK.",
  "..KccKbbbbbKwwYYYYwwKbbbbbKccK..",
  "...KcKbbbbbbKwYbbYwKbbbbbbKcK...",
  "....KKbbbbbbbKYbbYKbbbbbbbKK....",
  "....KbbKbbbbbbbbbbbbbbbbKbbK....",
  "...KbbKKbbbbbbbbbbbbbbbbKKbbK...",
  "...KsK.KbbbYbbbbbbbbYbbbK.KsK...",
  "...KK..KbbbbYbbbbbbYbbbbK..KK...",
  ".......KbbbbbYbbbbYbbbbbK.......",
  ".......KbbbbbbYbbYbbbbbbK.......",
  "........KbbbbbbYYbbbbbbK........",
  "........KbbbbbbKKbbbbbbK........",
  "........KbbbKKKKKKKKbbbK........",
  ".......KbbbK........KbbbK.......",
  ".......KbbK..........KbbK.......",
  "......KKKKK..........KKKKK......",
  "................................",
];

const STORM_B: string[] = [
  "................................",
  "................................",
  "..........K....KK....K..........",
  ".........KYK..KYYK..KYK.........",
  ".........KYYKKYYYYKKYYK.........",
  "........KKKKKKKKKKKKKKKK........",
  "........KsssssSssSsssssK........",
  "........KsKKKssssssKKKsK........",
  "........KsKbKssssssKbKsK........",
  "........Kssssss..ssssssK........",
  ".......KwwsssssssssssswwK.......",
  ".......KwwwwKKKKKKKKwwwwK.......",
  "KK.....KwwwwwwwYYwwwwwwwK.....KK",
  "KcK...KKwwwwwwYYYYwwwwwwKK...KcK",
  "KccK.KbbKwwwwwwYYwwwwwwKbbK.KccK",
  "KcccKbbbbKwwwwwYYwwwwwKbbbbKcccK",
  ".KcccKbbbbKwwwwYYwwwwKbbbbKcccK.",
  "..KccKbbbbbKwwYYYYwwKbbbbbKccK..",
  "...KcKbbbbbbKwYbbYwKbbbbbbKcK...",
  "....KKbbbbbbbKYbbYKbbbbbbbKK....",
  "....KbbKbbbbbbbbbbbbbbbbKbbK....",
  "...KbbKKbbbbbbbbbbbbbbbbKKbbK...",
  "...KsK.KbbbYbbbbbbbbYbbbK.KsK...",
  "...KK..KbbbbYbbbbbbYbbbbK..KK...",
  ".......KbbbbbYbbbbYbbbbbK.......",
  ".......KbbbbbbYbbYbbbbbbK.......",
  "........KbbbbbbYYbbbbbbK........",
  "........KbbbbbbKKbbbbbbK........",
  "........KbbbKKKKKKKKbbbK........",
  ".......KbbbK........KbbbK.......",
  ".......KbbK..........KbbK.......",
  "......KKKKK..........KKKKK......",
];

const STORM_W: string[] = [
  ".........KYK..KYYK..KYK.........",
  ".........KYYKKYYYYKKYYK.........",
  "........KKKKKKKKKKKKKKKK........",
  "........KsssssSssSsssssK........",
  "........KsKKKssssssKKKsK........",
  "........KsKbKssssssKbKsK........",
  "........Kssssss..ssssssK........",
  ".......KwwsssssssssssswwK.......",
  ".......KwwwwKKKKKKKKwwwwK.......",
  "KK.....KwwwwwwwYYwwwwwwwK.....KK",
  "KcK...KKwwwwwwYYYYwwwwwwKK...KcK",
  "KccK.KbbKwwwwwwYYwwwwwwKbbK.KccK",
  "KcccKbbbbKwwwwwYYwwwwwKbbbbKcccK",
  ".KcccKbbbbKwwwwYYwwwwKbbbbKcccK.",
  "..KccKbbbbbKwwYYYYwwKbbbbbKccK..",
  "...KcKbbbbbbKwYbbYwKbbbbbbKcK...",
  "....KKbbbbbbbKYbbYKbbbbbbbKK....",
  "....KbbKbbbbbbbbbbbbbbbbKbbK....",
  "...KbbKKbbbbbbbbbbbbbbbbKKbbK...",
  "...KsK.KbbbYbbbbbbbbYbbbK.KsK...",
  "...KK..KbbbbYbbbbbbYbbbbK..KK...",
  ".......KbbbbbYbbbbYbbbbbK.......",
  ".......KbbbbbbYbbYbbbbbbK.......",
  "........KbbbbbbYYbbbbbbK........",
  "........KbbbbbbKKbbbbbbK........",
  "........KbbbKKKKKKKKbbbK........",
  ".......KbbbK........KbbbK.......",
  ".......KbbK..........KbbK.......",
  "......KKKKK..........KKKKK......",
  "................................",
  "................................",
  "................................",
];

export const SKYREACH: RealmSprites = {
  realm: 'skyreach',
  palette: [OUTLINE, '#e6f0ff', '#8fdcff', '#fff35c', '#ffd23f', '#d8a84f', '#3f7fbf', '#f2d6a8'],
  ground: 7,
  sprites: {
    cloud: { frames: [CLOUD1, CLOUD2], pal: { K: OUTLINE, w: '#e6f0ff', W: '#ffffff', b: '#8fdcff' } },
    sbird: { frames: [SBIRD1, SBIRD2], pal: { K: OUTLINE, y: '#fff35c', Y: '#ffffff', o: '#ff8a3d' } },
    griffin: { frames: [GRIFFIN1, GRIFFIN2], pal: { K: OUTLINE, w: '#fff4e0', y: '#d8a84f', o: '#ffd23f' } },
    bossK: { frames: [STORM_A, STORM_B, STORM_W], pal: { K: OUTLINE, s: '#f2d6a8', S: '#e0b890', b: '#3f7fbf', w: '#e6f0ff', c: '#8fdcff', Y: '#fff35c' }, note: 'Storm King 32×32 (idle ×2, wind-up)' },
  },
};
