// Sunscar (desert): sand slime, scorpion, mummy, Sand King.
import { OUTLINE, type RealmSprites } from '../types';
import { SLIME } from './common';
import { GHOST } from './deepdark';
const SCORP: string[] = [
  "..KK......KK..",
  ".KrrK....KrrK.",
  ".KrK......KrK.",
  "..KK.KKKK.KK..",
  "....KrrrrK....",
  "...KrKrrKrK...",
  "...KrrrrrrK...",
  "..KrKrrrrKrK..",
  "...KKrrrrKK...",
  ".....KrrK.....",
  "......KrK.....",
  ".......KK.....",
];

const KSAND_A: string[] = [
  "................................",
  "...............KK...............",
  "..............KYYK..............",
  "............KKYYYYKK............",
  "..........KKYbYYYYbYKK..........",
  "........KKYbYbYYYYbYbYKK........",
  ".......KYbYbKKKKKKKKbYbYK.......",
  "......KYbYbKssssssssKbYbYK......",
  ".....KYbYbKsKKssssKKsKbYbYK.....",
  ".....KbYbYKsKwsssswKsKYbYbK.....",
  ".....KYbYbKssssssssssKbYbYK.....",
  ".....KbYbYKssssKKssssKYbYbK.....",
  "....KYbYbKKssssssssssKKbYbYK....",
  "....KbYbK.KssKKKKKKssK.KbYbK....",
  "....KYbK...KKssssssKK...KbYK....",
  "...KKKK...KYYYYYYYYYYK...KKKK...",
  "..KrrrrKKKYbbbbbbbbbbYKKKrrrrK..",
  ".KrRRrrrrKYYYYYYYYYYYYKrrrrRRrK.",
  ".KrRrrKrrrKrrrrrrrrrrKrrrKrrRrK.",
  ".KrrrK.KrrKrrYrrrrYrrKrrK.KrrrK.",
  ".KssK..KrrKrYYYrrYYYrKrrK..KssK.",
  "KYYYYK.KrrKrrYrrrrYrrKrrK.KYYYYK",
  "KYbbYK.KrrrKrrrrrrrrKrrrK.KYbbYK",
  "KYYYYK..KrrrKrrrrrrKrrrK..KYYYYK",
  ".KKKK...KrrrrKKKKKKrrrrK...KKKK.",
  "........KrrrrrrKKrrrrrrK........",
  "........KrrrrrrKKrrrrrrK........",
  "........KrrrKKKKKKKKrrrK........",
  ".......KrrrK........KrrrK.......",
  ".......KbbK..........KbbK.......",
  "......KKKKK..........KKKKK......",
  "................................",
];

const KSAND_B: string[] = [
  "................................",
  "................................",
  "...............KK...............",
  "..............KYYK..............",
  "............KKYYYYKK............",
  "..........KKYbYYYYbYKK..........",
  "........KKYbYbYYYYbYbYKK........",
  ".......KYbYbKKKKKKKKbYbYK.......",
  "......KYbYbKssssssssKbYbYK......",
  ".....KYbYbKsKKssssKKsKbYbYK.....",
  ".....KbYbYKsKwsssswKsKYbYbK.....",
  ".....KYbYbKssssssssssKbYbYK.....",
  ".....KbYbYKssssKKssssKYbYbK.....",
  "....KYbYbKKssssssssssKKbYbYK....",
  "....KbYbK.KssKKKKKKssK.KbYbK....",
  "....KYbK...KKssssssKK...KbYK....",
  "...KKKK...KYYYYYYYYYYK...KKKK...",
  "..KrrrrKKKYbbbbbbbbbbYKKKrrrrK..",
  ".KrRRrrrrKYYYYYYYYYYYYKrrrrRRrK.",
  ".KrRrrKrrrKrrrrrrrrrrKrrrKrrRrK.",
  ".KrrrK.KrrKrrYrrrrYrrKrrK.KrrrK.",
  ".KssK..KrrKrYYYrrYYYrKrrK..KssK.",
  "KYYYYK.KrrKrrYrrrrYrrKrrK.KYYYYK",
  "KYbbYK.KrrrKrrrrrrrrKrrrK.KYbbYK",
  "KYYYYK..KrrrKrrrrrrKrrrK..KYYYYK",
  ".KKKK...KrrrrKKKKKKrrrrK...KKKK.",
  "........KrrrrrrKKrrrrrrK........",
  "........KrrrrrrKKrrrrrrK........",
  "........KrrrKKKKKKKKrrrK........",
  ".......KrrrK........KrrrK.......",
  ".......KbbK..........KbbK.......",
  "......KKKKK..........KKKKK......",
];

const KSAND_W: string[] = [
  "..............KYYK..............",
  "............KKYYYYKK............",
  "..........KKYbYYYYbYKK..........",
  "........KKYbYbYYYYbYbYKK........",
  ".......KYbYbKKKKKKKKbYbYK.......",
  "......KYbYbKssssssssKbYbYK......",
  ".....KYbYbKsKKssssKKsKbYbYK.....",
  ".....KbYbYKsKwsssswKsKYbYbK.....",
  ".....KYbYbKssssssssssKbYbYK.....",
  ".....KbYbYKssssKKssssKYbYbK.....",
  "....KYbYbKKssssssssssKKbYbYK....",
  "....KbYbK.KssKKKKKKssK.KbYbK....",
  "....KYbK...KKssssssKK...KbYK....",
  "...KKKK...KYYYYYYYYYYK...KKKK...",
  "..KrrrrKKKYbbbbbbbbbbYKKKrrrrK..",
  ".KrRRrrrrKYYYYYYYYYYYYKrrrrRRrK.",
  ".KrRrrKrrrKrrrrrrrrrrKrrrKrrRrK.",
  ".KrrrK.KrrKrrYrrrrYrrKrrK.KrrrK.",
  ".KssK..KrrKrYYYrrYYYrKrrK..KssK.",
  "KYYYYK.KrrKrrYrrrrYrrKrrK.KYYYYK",
  "KYbbYK.KrrrKrrrrrrrrKrrrK.KYbbYK",
  "KYYYYK..KrrrKrrrrrrKrrrK..KYYYYK",
  ".KKKK...KrrrrKKKKKKrrrrK...KKKK.",
  "........KrrrrrrKKrrrrrrK........",
  "........KrrrrrrKKrrrrrrK........",
  "........KrrrKKKKKKKKrrrK........",
  ".......KrrrK........KrrrK.......",
  ".......KbbK..........KbbK.......",
  "......KKKKK..........KKKKK......",
  "................................",
  "................................",
  "................................",
];

export const SUNSCAR: RealmSprites = {
  realm: 'sunscar',
  palette: [OUTLINE, '#e0a040', '#ffe0a0', '#9a5a1a', '#d9822b', '#e8d9b0', '#ff9a2a', '#ffd23f'],
  ground: 1,
  sprites: {
    sslime: { frames: [SLIME], pal: { K: OUTLINE, g: '#e0a040', G: '#ffe0a0', d: '#9a5a1a' } },
    scorp: { frames: [SCORP], pal: { K: OUTLINE, r: '#d9822b' } },
    mummy: { frames: [GHOST], pal: { K: OUTLINE, w: '#e8d9b0' } },
    bossD: { frames: [KSAND_A, KSAND_B, KSAND_W], pal: { K: OUTLINE, Y: '#ffd23f', b: '#3f5fd1', s: '#d8a868', w: '#ffffff', r: '#c98a3a', R: '#e8b86a' }, note: 'Sand King 32×32 (idle ×2, wind-up) — draft for review' },
  },
};
