// Tidehollow (sunken city, water): jellyfish, sawfish, armor crab, Tide Queen.
// Tickets 36–38 art: drafts for the owner's review in the Sprite Lab.
import { OUTLINE, type RealmSprites } from '../types';

const JELLY1: string[] = [
  "....KKKKKK....",
  "..KKjjjjjjKK..",
  ".KjJJjjjjjjjK.",
  ".KjJjjjjjjjjK.",
  "KjjjKjjjjKjjjK",
  "KjjjjjjjjjjjjK",
  ".KKKKKKKKKKKK.",
  "..KjK.KjK.KjK.",
  "..KjK..Kj.KjK.",
  "...K...KjK.K..",
  "........K.....",
];

const JELLY2: string[] = [
  "....KKKKKK....",
  "..KKjjjjjjKK..",
  ".KjJJjjjjjjjK.",
  ".KjJjjjjjjjjK.",
  "KjjjKjjjjKjjjK",
  "KjjjjjjjjjjjjK",
  ".KKKKKKKKKKKK.",
  "..KjK.KjK.KjK.",
  "...KjKKjK..Kj.",
  "....K..K...K..",
  "..............",
];

const SAWFISH: string[] = [
  "................",
  "......KKK.......",
  ".....KbbbK......",
  "KKKKKKbbbbbKKK..",
  "KwKwKbbbbbbbbbK.",
  "KKKKKbbKbbbbbbbK",
  ".....KbbbbbbbbK.",
  "......KbbwwbbK..",
  ".......KKKKbK...",
  "...........KK...",
];

const CRAB1: string[] = [
  ".KK..........KK.",
  "KrrK........KrrK",
  "KrKrK......KrKrK",
  ".KrrK.K..K.KrrK.",
  "..KKKwKKKKwKKK..",
  "....KrrrrrrK....",
  "...KrRRrrrrrK...",
  "..KrRrrrrrrrrK..",
  "..KrrrrrrrrrrK..",
  "...KKrrrrrrKK...",
  "..KrKKKKKKKKrK..",
  ".KrK.KrK.KrK.KrK",
  ".KK..KK...KK..KK",
];

const CRAB2: string[] = [
  ".KK..........KK.",
  "KrrK........KrrK",
  "KrKrK......KrKrK",
  ".KrrK.K..K.KrrK.",
  "..KKKwKKKKwKKK..",
  "....KrrrrrrK....",
  "...KrRRrrrrrK...",
  "..KrRrrrrrrrrK..",
  "..KrrrrrrrrrrK..",
  "...KKrrrrrrKK...",
  "..KrKKKKKKKKrK..",
  "..KrK.KrK.KrK.K.",
  "..KK..KK..KK..K.",
];

const TIDE_A: string[] = [
  "................................",
  "...........K...KK...K...........",
  "..........KcK.KccK.KcK..........",
  "..........KccKccccKccK..........",
  "..........KccccccccccK..........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KtttttttTTtttttttK.......",
  "......KttKttttttttttttKttK......",
  ".....KtttKssssssssssssKtttK.....",
  ".....KttKsKKssssssssKKsKttK.....",
  ".....KttKsKbssssssssbKsKttK.....",
  ".....KtttKsssssSSsssssKtttK.....",
  ".....KttttKssmmmmmmssKttttK.....",
  "....KttttttKKssssssKKttttttK....",
  "....Kttt.KttKKKKKKKKttK.tttK....",
  "...Kttt..KqqqqqQQqqqqqK..tttK...",
  "...Ktt..KqqQqqqqqqqqQqqK..ttK...",
  "..Ktt..KsKqqqqqqqqqqqqKsK..ttK..",
  "..KtK.KssKqqqqqqqqqqqqKssK.KtK..",
  "..KK.KssKqqqqqqqqqqqqqqKssK.KK..",
  ".....KsK.KqqqqqqqqqqqqK.KsK.....",
  ".....KK..KqqqqqqqqqqqqK..KK.....",
  ".........KqqqqqKKqqqqqK.........",
  "........KqqqqqqKKqqqqqqK........",
  "........KqqqqqqKKqqqqqqK........",
  ".......KqqqqqqqKKqqqqqqqK.......",
  ".......KqqqqqQqqqqQqqqqqK.......",
  "......KqqqqqQQqqqqQQqqqqqK......",
  "......KqqqqQQQqqqqQQQqqqqK......",
  ".....KqqqqQQQQqqqqQQQQqqqqK.....",
  ".....KKKKKKKKKKKKKKKKKKKKKK.....",
  "................................",
];

const TIDE_B: string[] = [
  "................................",
  "................................",
  "...........K...KK...K...........",
  "..........KcK.KccK.KcK..........",
  "..........KccKccccKccK..........",
  "..........KccccccccccK..........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KtttttttTTtttttttK.......",
  "......KttKttttttttttttKttK......",
  ".....KtttKssssssssssssKtttK.....",
  ".....KttKsKKssssssssKKsKttK.....",
  ".....KttKsKbssssssssbKsKttK.....",
  ".....KtttKsssssSSsssssKtttK.....",
  ".....KttttKssmmmmmmssKttttK.....",
  "....KttttttKKssssssKKttttttK....",
  "....Kttt.KttKKKKKKKKttK.tttK....",
  "...Kttt..KqqqqqQQqqqqqK..tttK...",
  "...Ktt..KqqQqqqqqqqqQqqK..ttK...",
  "..Ktt..KsKqqqqqqqqqqqqKsK..ttK..",
  "..KtK.KssKqqqqqqqqqqqqKssK.KtK..",
  "..KK.KssKqqqqqqqqqqqqqqKssK.KK..",
  ".....KsK.KqqqqqqqqqqqqK.KsK.....",
  ".....KK..KqqqqqqqqqqqqK..KK.....",
  ".........KqqqqqKKqqqqqK.........",
  "........KqqqqqqKKqqqqqqK........",
  "........KqqqqqqKKqqqqqqK........",
  ".......KqqqqqqqKKqqqqqqqK.......",
  ".......KqqqqqQqqqqQqqqqqK.......",
  "......KqqqqqQQqqqqQQqqqqqK......",
  "......KqqqqQQQqqqqQQQqqqqK......",
  ".....KqqqqQQQQqqqqQQQQqqqqK.....",
  ".....KKKKKKKKKKKKKKKKKKKKKK.....",
];

const TIDE_W: string[] = [
  "..........KcK.KccK.KcK..........",
  "..........KccKccccKccK..........",
  "..........KccccccccccK..........",
  "........KKKKKKKKKKKKKKKK........",
  ".......KtttttttTTtttttttK.......",
  "......KttKttttttttttttKttK......",
  ".....KtttKssssssssssssKtttK.....",
  ".....KttKsKKssssssssKKsKttK.....",
  ".....KttKsKbssssssssbKsKttK.....",
  ".....KtttKsssssSSsssssKtttK.....",
  ".....KttttKssmmmmmmssKttttK.....",
  "....KttttttKKssssssKKttttttK....",
  "....Kttt.KttKKKKKKKKttK.tttK....",
  "...Kttt..KqqqqqQQqqqqqK..tttK...",
  "...Ktt..KqqQqqqqqqqqQqqK..ttK...",
  "..Ktt..KsKqqqqqqqqqqqqKsK..ttK..",
  "..KtK.KssKqqqqqqqqqqqqKssK.KtK..",
  "..KK.KssKqqqqqqqqqqqqqqKssK.KK..",
  ".....KsK.KqqqqqqqqqqqqK.KsK.....",
  ".....KK..KqqqqqqqqqqqqK..KK.....",
  ".........KqqqqqKKqqqqqK.........",
  "........KqqqqqqKKqqqqqqK........",
  "........KqqqqqqKKqqqqqqK........",
  ".......KqqqqqqqKKqqqqqqqK.......",
  ".......KqqqqqQqqqqQqqqqqK.......",
  "......KqqqqqQQqqqqQQqqqqqK......",
  "......KqqqqQQQqqqqQQQqqqqK......",
  ".....KqqqqQQQQqqqqQQQQqqqqK.....",
  ".....KKKKKKKKKKKKKKKKKKKKKK.....",
  "................................",
  "................................",
  "................................",
];

export const TIDEHOLLOW: RealmSprites = {
  realm: 'tidehollow',
  palette: [OUTLINE, '#ff9ad8', '#5c8fbf', '#e8543c', '#3fbfbf', '#bff0f0', '#ffd23f', '#f2d6a8'],
  ground: 8,
  sprites: {
    jelly: { frames: [JELLY1, JELLY2], pal: { K: OUTLINE, j: '#ff9ad8', J: '#ffd8f0' } },
    sawfish: { frames: [SAWFISH], pal: { K: OUTLINE, b: '#5c8fbf', w: '#dff0ff' } },
    crab: { frames: [CRAB1, CRAB2], pal: { K: OUTLINE, r: '#e8543c', R: '#ff9a7a', w: '#ffffff' } },
    bossT: { frames: [TIDE_A, TIDE_B, TIDE_W], pal: { K: OUTLINE, t: '#3fbfbf', T: '#8fe0e0', s: '#f2d6a8', S: '#e0b890', b: '#1e6f8f', m: '#e8434f', q: '#2f8f9f', Q: '#bff0f0', c: '#ffd23f' }, note: 'Tide Queen 32×32 (idle ×2, wind-up)' },
  },
};
