-- Ticket 53: new Balance Config field shared.awaken.lineSlots (Awakened-only attack slots: after Awakening the Hero gets
-- this many extra slots that hold only Skill Line skills, which then never take a normal attack slot). Patched into the
-- live config_schema so publish_config accepts it; every live awaken key is carried over unchanged. Its default 0 keeps
-- the current behaviour (Awakened skills share the normal attack slots) until an admin publishes the pass that turns it
-- on (Admin → Balance → 2026-09h: lineSlots 3, slots 0).
update public.config_schema set schema = jsonb_set(schema,
  '{properties,shared,properties,awaken}',
  $j${"description":"Awakening","default":{},"type":"object","properties":{"links":{"default":2,"description":"Max-level Links needed (consumed unless keep is 1)","type":"number","minimum":1,"maximum":3},"stages":{"default":1,"description":"Full Stages the Links must have been max level and equipped","type":"number","minimum":1,"maximum":5},"sigDmg":{"default":1.3,"description":"Awakened Signature Skill damage ×","type":"number","minimum":0,"maximum":10},"grant":{"default":0,"description":"Skill Line skills given right away when Awakening (in listed order, into free attack slots)","type":"number","minimum":0,"maximum":3},"grantLv":{"default":1,"description":"Level of the Skill Line skills given at Awakening","type":"number","minimum":1,"maximum":8},"wLine":{"default":1,"description":"Level-up offer weight × for Skill Line skills after Awakening","type":"number","minimum":0,"maximum":10},"keep":{"default":0,"description":"Awakening keeps the Links equipped (1) or consumes them (0)","type":"number","minimum":0,"maximum":1},"slots":{"default":0,"description":"Extra attack slots after Awakening","type":"number","minimum":0,"maximum":2},"lineSlots":{"default":0,"description":"Attack slots after Awakening that hold only Skill Line (Awakened) skills; they then never take a normal attack slot (0 = they share the normal slots)","type":"number","minimum":0,"maximum":3},"form":{"default":0,"description":"Awakened Signature takes a new form and the Skill Line skills combo with it (1), or it only hits harder (0)","type":"number","minimum":0,"maximum":1},"mark":{"default":1.5,"description":"Skill Line skills aim at the Awakened Signature's latest strike when it is this recent (s)","type":"number","minimum":0,"maximum":600}}}$j$::jsonb)
where id = 1;
