-- Ticket 58: forge levels also add Ultimate damage and raise the boss caps (owner, 2026-09-27).
-- New Balance Config fields shared.forge.{dmg,bossCap,umbraCap}. 0036 is live, so this replaces the whole shared.forge
-- subtree of the live config_schema with the zod-generated one: every key of 0036 unchanged, plus the three new ones.
-- Only the sim reads them (forge_weapon prices are unchanged). Published versions without them read the built-in defaults.

update public.config_schema set schema = jsonb_set(schema,
  '{properties,shared,properties,forge}',
  $j${"description":"Weapon forge (special shop, after the first win)","default":{},"type":"object","properties":{"max":{"default":5,"description":"Forge: levels per Weapon","type":"number","minimum":0,"maximum":20},"base":{"default":400,"description":"Forge: price of the first level (Gold)","type":"number","minimum":0,"maximum":4000},"growth":{"default":1.6,"description":"Forge: price × per level","type":"number","minimum":0,"maximum":10},"dmg":{"default":0.2,"description":"Forge: Ultimate damage + per level (× the base strike)","type":"number","minimum":0,"maximum":2},"bossCap":{"default":0.01,"description":"Forge: King / Guardian cap + per level (share of max HP)","type":"number","minimum":0,"maximum":0.2},"umbraCap":{"default":0.005,"description":"Forge: Umbra cap + per level (share of max HP)","type":"number","minimum":0,"maximum":0.2},"judgement":{"default":0.2,"description":"Forge Judgement: monsters that survive the strike are stunned (s per level; bosses never)","type":"number","minimum":0,"maximum":2},"thornwhip":{"default":0.15,"description":"Forge Thornwhip: root time + per level","type":"number","minimum":0,"maximum":1},"sunblade":{"default":0.15,"description":"Forge Sunblade: Burning time + per level","type":"number","minimum":0,"maximum":1},"boneScythe":{"default":0.15,"description":"Forge Bone Scythe: reap threshold + per level","type":"number","minimum":0,"maximum":1},"glacierLance":{"default":0.15,"description":"Forge Glacier Lance: freeze time + per level","type":"number","minimum":0,"maximum":1},"magmaMaul":{"default":0.15,"description":"Forge Magma Maul: knockback + per level","type":"number","minimum":0,"maximum":1},"plagueCenser":{"default":0.15,"description":"Forge Plague Censer: poison damage + per level","type":"number","minimum":0,"maximum":1},"stormBow":{"default":0.15,"description":"Forge Storm Bow: Shocked time + per level","type":"number","minimum":0,"maximum":1},"coralTrident":{"default":0.15,"description":"Forge Coral Trident: push + per level","type":"number","minimum":0,"maximum":1},"gearCannon":{"default":0.15,"description":"Forge Gear Cannon: turret time + per level","type":"number","minimum":0,"maximum":1},"lichTome":{"default":0.15,"description":"Forge Lich Tome: healing (and its limit) + per level","type":"number","minimum":0,"maximum":1}}}$j$::jsonb)
where id = 1;
