-- Balance follow-up 2026-09b: new Balance Config fields shared.awaken.{keep,slots} (Awakening keeps the Links
-- and adds attack slots), shared.scaling.{lvCapBase,lvCapPerCh} (monster formulas count the player level only up
-- to the usual level), shared.skills.hawk.{guardN,guardR} (the Hawk defends Kit) and shared.heroes.ranger.hp.
-- Also the reworded descriptions of awaken.links / awaken.grant. Patched into the live config_schema so
-- publish_config accepts them; their defaults keep the current behaviour until an admin publishes the
-- recommended values (Admin → Balance → 2026-09b).
update public.config_schema set schema = jsonb_set(jsonb_set(jsonb_set(jsonb_set(schema,
  '{properties,shared,properties,awaken}',
  $j${"description":"Awakening","default":{},"type":"object","properties":{"links":{"default":2,"description":"Max-level Links needed (consumed unless keep is 1)","type":"number","minimum":1,"maximum":3},"stages":{"default":1,"description":"Full Stages the Links must have been max level and equipped","type":"number","minimum":1,"maximum":5},"sigDmg":{"default":1.3,"description":"Awakened Signature Skill damage ×","type":"number","minimum":0,"maximum":10},"grant":{"default":0,"description":"Skill Line skills given right away when Awakening (in listed order, into free attack slots)","type":"number","minimum":0,"maximum":3},"grantLv":{"default":1,"description":"Level of the Skill Line skills given at Awakening","type":"number","minimum":1,"maximum":8},"wLine":{"default":1,"description":"Level-up offer weight × for Skill Line skills after Awakening","type":"number","minimum":0,"maximum":10},"keep":{"default":0,"description":"Awakening keeps the Links equipped (1) or consumes them (0)","type":"number","minimum":0,"maximum":1},"slots":{"default":0,"description":"Extra attack slots after Awakening","type":"number","minimum":0,"maximum":2}}}$j$::jsonb),
  '{properties,shared,properties,scaling}',
  $j${"description":"Enemy scaling","default":{},"type":"object","properties":{"hpGrowth":{"default":1.5,"description":"Enemy HP × per stage","type":"number","minimum":0,"maximum":10},"hpProg":{"default":0.7,"description":"Enemy HP + at stage end","type":"number","minimum":0,"maximum":10},"hpPerLv":{"default":0.08,"description":"Enemy HP + per player level","type":"number","minimum":0,"maximum":1},"lvCapBase":{"default":0,"description":"Highest player level the monster formulas count at the start of Chapter 1 (0 with lvCapPerCh 0 = no cap)","type":"number","minimum":0,"maximum":100},"lvCapPerCh":{"default":0,"description":"That counted-level cap grows by this much over each Chapter; levels above it add no monster HP, damage or armor","type":"number","minimum":0,"maximum":50},"hpDirBase":{"default":0.85,"description":"Enemy HP Director base","type":"number","minimum":0,"maximum":10},"hpDirK":{"default":0.15,"description":"Enemy HP per Director point","type":"number","minimum":0,"maximum":10},"dmgGrowth":{"default":1.18,"description":"Enemy damage × per stage","type":"number","minimum":0,"maximum":10},"dmgProg":{"default":0.5,"description":"Enemy damage + at stage end","type":"number","minimum":0,"maximum":10},"dmgPerLv":{"default":0.015,"description":"Enemy damage + per player level","type":"number","minimum":0,"maximum":1},"spdPerStage":{"default":0.04,"description":"Enemy speed + per stage","type":"number","minimum":0,"maximum":1},"spdJitter":{"default":0.1,"description":"Enemy speed random ±","type":"number","minimum":0,"maximum":1},"eliteHp":{"default":7,"description":"Elite HP ×","type":"number","minimum":0,"maximum":10},"eliteSpd":{"default":0.85,"description":"Elite speed ×","type":"number","minimum":0,"maximum":10},"eliteDmg":{"default":1.6,"description":"Elite damage ×","type":"number","minimum":0,"maximum":10},"eliteXp":{"default":6,"description":"Elite XP ×","type":"number","minimum":0,"maximum":10},"eliteR":{"default":2,"description":"Elite size ×","type":"number","minimum":0,"maximum":10},"armorFrom":{"default":3,"description":"First stage with armored enemies","type":"number","minimum":1,"maximum":99},"armorChance":{"default":0.03,"description":"Armor chance","type":"number","minimum":0,"maximum":1},"armorChancePerStage":{"default":0.015,"description":"Armor chance per stage","type":"number","minimum":0,"maximum":1},"armorBase":{"default":10,"description":"Armor (flat reduction) at stage 1","type":"number","minimum":0,"maximum":100},"armorGrowth":{"default":1.4,"description":"Armor × per stage","type":"number","minimum":0,"maximum":10},"armorPerLv":{"default":0.05,"description":"Armor + per player level","type":"number","minimum":0,"maximum":1},"hitVariance":{"default":0.15,"description":"Enemy hit damage random ±","type":"number","minimum":0,"maximum":1},"wobble":{"default":0.5,"description":"Path wobble (rad)","type":"number","minimum":0,"maximum":1}}}$j$::jsonb),
  '{properties,shared,properties,skills,properties,hawk}',
  $j${"description":"Kit: Hawk Companion","default":{},"type":"object","properties":{"max":{"default":7,"description":"Max level","type":"number","minimum":1,"maximum":20},"dmg":{"description":"Dive damage","default":{},"type":"object","properties":{"base":{"default":34,"description":"Value before levels","type":"number","minimum":-1000000,"maximum":1000000},"perLv":{"default":16,"description":"Added per skill level","type":"number","minimum":-10000,"maximum":10000},"min":{"description":"Lower limit","type":"number","minimum":-1000000,"maximum":1000000},"max":{"description":"Upper limit","type":"number","minimum":-1000000,"maximum":1000000}}},"cd":{"description":"Cooldown (s)","default":{},"type":"object","properties":{"base":{"default":2.2,"description":"Value before levels","type":"number","minimum":-1000000,"maximum":1000000},"perLv":{"default":-0.14,"description":"Added per skill level","type":"number","minimum":-10000,"maximum":10000},"min":{"default":0.9,"description":"Lower limit","type":"number","minimum":-1000000,"maximum":1000000},"max":{"description":"Upper limit","type":"number","minimum":-1000000,"maximum":1000000}}},"range":{"default":230,"description":"Hunting range","type":"number","minimum":0,"maximum":2300},"flight":{"default":0.35,"description":"Dive time (s)","type":"number","minimum":0,"maximum":600},"kb":{"default":40,"description":"Knockback","type":"number","minimum":0,"maximum":400},"r":{"default":0,"description":"Dive splash radius: monsters this close to the prey are hit too (0 = prey only)","type":"number","minimum":0,"maximum":200},"guardN":{"default":0,"description":"Monsters this close to Kit that make the Hawk defend: it dives the nearest one instead of the biggest (0 = never)","type":"number","minimum":0,"maximum":50},"guardR":{"default":40,"description":"Hawk defend radius around Kit","type":"number","minimum":0,"maximum":400},"evo":{"description":"Changes applied when the skill evolves","default":{},"type":"object","properties":{"n":{"default":2,"description":"Hawks","type":"number","minimum":1,"maximum":4},"stun":{"default":0.8,"description":"Stun (s); bosses are slowed","type":"number","minimum":0,"maximum":600}}}}}$j$::jsonb),
  '{properties,shared,properties,heroes,properties,ranger}',
  $j${"description":"Kit","default":{},"type":"object","properties":{"cost":{"default":500,"description":"Unlock price","type":"number","minimum":0,"maximum":5000},"spd":{"default":0.12,"description":"Speed bonus","type":"number","minimum":0,"maximum":1},"pick":{"default":0.3,"description":"Pickup range bonus","type":"number","minimum":0,"maximum":10},"hp":{"default":0,"description":"Max HP bonus","type":"number","minimum":0,"maximum":200}}}$j$::jsonb)
where id = 1;
