-- Balance pass 2026-09: new Balance Config fields shared.awaken.{grant,grantLv,wLine} (Skill Line
-- skills given at Awakening, their level, their level-up weight) and shared.skills.hawk.r (dive splash).
-- Patched into the live config_schema so publish_config accepts them; their defaults keep the
-- original behaviour until an admin publishes the recommended values (Admin → Balance).
update public.config_schema set schema = jsonb_set(jsonb_set(schema,
  '{properties,shared,properties,awaken}',
  $j${"description":"Awakening","default":{},"type":"object","properties":{"links":{"default":2,"description":"Max-level Links needed (and consumed)","type":"number","minimum":1,"maximum":3},"stages":{"default":1,"description":"Full Stages the Links must have been max level and equipped","type":"number","minimum":1,"maximum":5},"sigDmg":{"default":1.3,"description":"Awakened Signature Skill damage ×","type":"number","minimum":0,"maximum":10},"grant":{"default":0,"description":"Skill Line skills given right away when Awakening (in listed order, into the freed slots)","type":"number","minimum":0,"maximum":3},"grantLv":{"default":1,"description":"Level of the Skill Line skills given at Awakening","type":"number","minimum":1,"maximum":8},"wLine":{"default":1,"description":"Level-up offer weight × for Skill Line skills after Awakening","type":"number","minimum":0,"maximum":10}}}$j$::jsonb),
  '{properties,shared,properties,skills,properties,hawk}',
  $j${"description":"Kit: Hawk Companion","default":{},"type":"object","properties":{"max":{"default":7,"description":"Max level","type":"number","minimum":1,"maximum":20},"dmg":{"description":"Dive damage","default":{},"type":"object","properties":{"base":{"default":34,"description":"Value before levels","type":"number","minimum":-1000000,"maximum":1000000},"perLv":{"default":16,"description":"Added per skill level","type":"number","minimum":-10000,"maximum":10000},"min":{"description":"Lower limit","type":"number","minimum":-1000000,"maximum":1000000},"max":{"description":"Upper limit","type":"number","minimum":-1000000,"maximum":1000000}}},"cd":{"description":"Cooldown (s)","default":{},"type":"object","properties":{"base":{"default":2.2,"description":"Value before levels","type":"number","minimum":-1000000,"maximum":1000000},"perLv":{"default":-0.14,"description":"Added per skill level","type":"number","minimum":-10000,"maximum":10000},"min":{"default":0.9,"description":"Lower limit","type":"number","minimum":-1000000,"maximum":1000000},"max":{"description":"Upper limit","type":"number","minimum":-1000000,"maximum":1000000}}},"range":{"default":230,"description":"Hunting range","type":"number","minimum":0,"maximum":2300},"flight":{"default":0.35,"description":"Dive time (s)","type":"number","minimum":0,"maximum":600},"kb":{"default":40,"description":"Knockback","type":"number","minimum":0,"maximum":400},"r":{"default":0,"description":"Dive splash radius: monsters this close to the prey are hit too (0 = prey only)","type":"number","minimum":0,"maximum":200},"evo":{"description":"Changes applied when the skill evolves","default":{},"type":"object","properties":{"n":{"default":2,"description":"Hawks","type":"number","minimum":1,"maximum":4},"stun":{"default":0.8,"description":"Stun (s); bosses are slowed","type":"number","minimum":0,"maximum":600}}}}}$j$::jsonb)
where id = 1;
