-- Base difficulty (ticket 48): the difficulty presets are gone (shared.presets). The old Relaxed preset is now the
-- game's base (owner choice C, 2026-09-27) as a new Balance Config group shared.difficulty: multipliers the game applies
-- on top of the numbers in the config, with Gold ×0.2 so a fresh account earns about what old Balanced paid per Run.
-- Published versions without the group use these defaults, so the live game changes as soon as the new client ships;
-- publish_config accepts the group (and no longer lists presets).
update public.config_schema set schema = jsonb_set(schema #- '{properties,shared,properties,presets}',
  '{properties,shared,properties,difficulty}',
  $j${"description":"Base difficulty: multipliers on the numbers in this config (1 = as written)","default":{},"type":"object","properties":{"mobHp":{"default":0.6,"description":"Normal monster HP ×","type":"number","minimum":0,"maximum":10},"mobDmg":{"default":0.45,"description":"Normal monster damage ×","type":"number","minimum":0,"maximum":10},"bossHp":{"default":0.55,"description":"King, Guardian, Rival and Umbra HP ×","type":"number","minimum":0,"maximum":10},"bossDmg":{"default":0.45,"description":"King, Guardian, Rival and Umbra damage ×","type":"number","minimum":0,"maximum":10},"spawn":{"default":0.85,"description":"Spawn rate and swarm size ×","type":"number","minimum":0,"maximum":10},"xp":{"default":1.3,"description":"EXP gained ×","type":"number","minimum":0,"maximum":10},"warn":{"default":1.4,"description":"Boss move warning time ×","type":"number","minimum":0,"maximum":10},"kingPace":{"default":1.35,"description":"Pause between King moves ×","type":"number","minimum":0,"maximum":10},"hp":{"default":1.3,"description":"Player max HP ×","type":"number","minimum":0,"maximum":10},"hearts":{"default":2,"description":"Heart drop chance ×","type":"number","minimum":0,"maximum":10},"ultFill":{"default":0.8,"description":"Ultimate charge time ×","type":"number","minimum":0,"maximum":10},"director":{"default":0.75,"description":"Director maximum ×","type":"number","minimum":0,"maximum":10},"gold":{"default":0.2,"description":"Gold earned in a Run × (coins, chests, Kings, Rival, Gold bags, Umbra bonus)","type":"number","minimum":0,"maximum":10}}}$j$::jsonb)
where id = 1;
