-- Kit late game (balance pass 2026-09k): new Balance Config fields for Kit's Awakened (Skill Line) skills, crowd clear
-- and control around Kit: shared.skills.arrowRain.{near,slow} (the rain lands on the thickest crowd near Kit and slows
-- it) and shared.skills.galeStep.{slow,burstN,burstR,burstMul,burstKb,burstCd} (blades slow; Gale Burst when Kit is
-- surrounded). Defaults keep today's game (near 0, slow 0, burstN 0) until the pass is published. Patches only these
-- two shared.skills subtrees of the live config_schema, carrying every existing key.
update public.config_schema set schema = jsonb_set(schema,
  '{properties,shared,properties,skills,properties,arrowRain}',
  $j${"description":"Kit line: Arrow Rain","default":{},"type":"object","properties":{"max":{"default":8,"description":"Max level","type":"number","minimum":1,"maximum":20},"dmg":{"description":"Damage per volley","default":{},"type":"object","properties":{"base":{"default":12,"description":"Value before levels","type":"number","minimum":-1000000,"maximum":1000000},"perLv":{"default":6,"description":"Added per skill level","type":"number","minimum":-10000,"maximum":10000},"min":{"description":"Lower limit","type":"number","minimum":-1000000,"maximum":1000000},"max":{"description":"Upper limit","type":"number","minimum":-1000000,"maximum":1000000}}},"cd":{"description":"Cooldown (s)","default":{},"type":"object","properties":{"base":{"default":3.2,"description":"Value before levels","type":"number","minimum":-1000000,"maximum":1000000},"perLv":{"default":-0.2,"description":"Added per skill level","type":"number","minimum":-10000,"maximum":10000},"min":{"default":1.5,"description":"Lower limit","type":"number","minimum":-1000000,"maximum":1000000},"max":{"description":"Upper limit","type":"number","minimum":-1000000,"maximum":1000000}}},"r":{"description":"Radius","default":{},"type":"object","properties":{"base":{"default":40,"description":"Value before levels","type":"number","minimum":-1000000,"maximum":1000000},"perLv":{"default":4,"description":"Added per skill level","type":"number","minimum":-10000,"maximum":10000},"min":{"description":"Lower limit","type":"number","minimum":-1000000,"maximum":1000000},"max":{"description":"Upper limit","type":"number","minimum":-1000000,"maximum":1000000}}},"dur":{"description":"Lasts (s)","default":{},"type":"object","properties":{"base":{"default":2,"description":"Value before levels","type":"number","minimum":-1000000,"maximum":1000000},"perLv":{"default":0.15,"description":"Added per skill level","type":"number","minimum":-10000,"maximum":10000},"min":{"description":"Lower limit","type":"number","minimum":-1000000,"maximum":1000000},"max":{"description":"Upper limit","type":"number","minimum":-1000000,"maximum":1000000}}},"tick":{"default":0.2,"description":"Volley interval (s)","type":"number","minimum":0,"maximum":600},"range":{"default":200,"description":"Range","type":"number","minimum":0,"maximum":2000},"near":{"default":0,"description":"Arrow Rain lands on the thickest crowd this close to Kit (0 = on a random monster in range)","type":"number","minimum":0,"maximum":400},"slow":{"default":0,"description":"Every volley slows the non-boss monsters under it this long (s; 0 = no slow)","type":"number","minimum":0,"maximum":600}}}$j$::jsonb)
where id = 1;
update public.config_schema set schema = jsonb_set(schema,
  '{properties,shared,properties,skills,properties,galeStep}',
  $j${"description":"Kit line (survival): Gale Step","default":{},"type":"object","properties":{"max":{"default":8,"description":"Max level","type":"number","minimum":1,"maximum":20},"dmg":{"description":"Damage","default":{},"type":"object","properties":{"base":{"default":14,"description":"Value before levels","type":"number","minimum":-1000000,"maximum":1000000},"perLv":{"default":7,"description":"Added per skill level","type":"number","minimum":-10000,"maximum":10000},"min":{"description":"Lower limit","type":"number","minimum":-1000000,"maximum":1000000},"max":{"description":"Upper limit","type":"number","minimum":-1000000,"maximum":1000000}}},"every":{"default":0.3,"description":"Blade every (s) while walking","type":"number","minimum":0.05,"maximum":2},"dur":{"description":"Blade lasts (s)","default":{},"type":"object","properties":{"base":{"default":1.4,"description":"Value before levels","type":"number","minimum":-1000000,"maximum":1000000},"perLv":{"default":0.1,"description":"Added per skill level","type":"number","minimum":-10000,"maximum":10000},"min":{"description":"Lower limit","type":"number","minimum":-1000000,"maximum":1000000},"max":{"description":"Upper limit","type":"number","minimum":-1000000,"maximum":1000000}}},"r":{"default":10,"description":"Blade radius","type":"number","minimum":0,"maximum":100},"slow":{"default":0,"description":"Gale Step blades slow the non-boss monsters they cut (s; 0 = no slow)","type":"number","minimum":0,"maximum":600},"burstN":{"default":0,"description":"Gale Burst: this many monsters within its radius make the wind burst out from Kit (0 = never)","type":"number","minimum":0,"maximum":50},"burstR":{"default":48,"description":"Gale Burst radius around Kit","type":"number","minimum":0,"maximum":480},"burstMul":{"default":2,"description":"Gale Burst damage × blade damage","type":"number","minimum":0,"maximum":10},"burstKb":{"default":120,"description":"Gale Burst knockback (elites and bosses by player.kbElite / kbBoss)","type":"number","minimum":0,"maximum":1200},"burstCd":{"default":3,"description":"Gale Burst: at most one burst every (s)","type":"number","minimum":0,"maximum":600}}}$j$::jsonb)
where id = 1;
